### ISSUE TITLE
Lego The incredibles (818320)

### ISSUE THREAD

**Issue by eeyrjmr** [ValveSoftware/Proton#1186]
Generally the game runs smoothly. Sound issues, as in background music only (sound effect stop functioning fairly often). The minimap has graphic glitches (red tearing) but there is a game breaking bug when you are jackjack vs racoon. 

Fight for a period and then when you are bashing X then B and kick the racoon into the pool the screen just holds on a poolside view... its not frozen as such as aspects of the scene are moving ("steam" from the pool etc...)  can be seen BUT no way to progress.

Below is a screenshot of the scene where it just holds
https://steamuserimages-a.akamaihd.net/ugc/966474320530706991/52AF2865C2CE33F9253D216B88FB55C2A6B46825/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C1024%3A576&composite-to=*,*%7C1024%3A576&background-color=black

Tried with proton 3.7.3 and 3.7-5 beta, same result. cannot proceed

**Comment by eeyrjmr** [comment]
https://youtu.be/zNoO-n-xQYQ?t=290

This is the exact moment it "freezes" at. Its a cut scene so I wonder if it is some video playback issue?  NOTE: this isn't frozen here as I stated (the steam is moving) but the audio carries on playing until it is obviously expecting some input from me

**Comment by eeyrjmr** [comment]
Update: 
New proton beta ( 3.16-5 beta ) has fixed the two issues mentioned
#1 audio 
#2 the apparent lockup during jackjack fight 

This is also using nvidia 415.22 (includes some Vulkan improvements: VK_EXT_transform_feedback)

Not saying this game is ready to be whitelisted, but this is a good sign. Hopefully I can continue and complete the game with the family. If it does complete without issue this is a good candidate for whietlisting

**Comment by kisak-valve** [comment]
[Whitelist] Lego Incredibles 

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2188.
@eeyrjmr posted on 2019-01-03T20:42:43:

# Whitelist Request
- Lego Incredibles
- 818320

## System Information
- GPU: [GeForce GTX 970
- Driver/LLVM version: NVIDIA 415.25
- Distro version: Gentoo
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/eeyrjmr/446c791fdd0e0860cbcb3102dbd01373
- Proton version: 3.16-6 Beta 

## I confirm:
- [ x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

I have completed Lego:Incredibles completley in linux, using steam controllers and all via steam link with no issues since Proton 3.16-6

**Comment by ghost** [comment]
# Whitelist Request :

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa 19.0.0 & LLVM 7.0.1
- Distro: Sabayon
- Link to full system information report as [Gist](https://gist.github.com/Alexander88207/72c104e4d0f59898cc4ede2fce2de25a)
- Proton version: 3.16-8 Beta

## I confirm:
- [✔] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [✔] I haven't experienced any issues.
