### ISSUE TITLE
NaissancE (265690)

### ISSUE THREAD

**Issue by Simmonz** [ValveSoftware/Proton#1231]
I tried running NaissanceE under Steam Play but it crashed at launch. It said "running" but crashed before any window opened. My system specs:

AMD Ryzen 5 2600X | 16GB DDR4-3000 CL15 | MSI RX 580 8GB Gaming X | Mesa 18.1.6 | Solus 3.9999 | Kernel 4.18.5-90.current | Proton 3.7-3

**Comment by glubsy** [comment]
You should post what Steam reports as system information: in the Steam client go to help menu -> System information -> right click copy all, paste into a [gist](https://gist.github.com/) or pastebin.

Also try to include any relevant log that you can find. If you use launch options for the game (right click,  properties, set launch options) such as `PROTON_LOG=1 PROTON_DUMP_DEBUG_COMMANDS=1 DXVK_HUD=1 %command%` you can find proton specific log in your /home/ directory.

There might also be some Unreal Engine 3 logs somewhere too, look it up.

Also include the Steam AppId in the title, in this case it should be NaissancE (265690). 

Since we're using only one thread per title, you can probably keep the title just that way.

**Comment by Simmonz** [comment]
https://gist.github.com/Simmonz/52713185a5e0abe7d3686717467cdff9

Couldn't find any crash logs even after adding the launch command you provided.

**Comment by glubsy** [comment]
Here's a [proton log](https://gist.github.com/glubsy/b63dd93a680ccbcbb643e245f8ea1a8c) (/home/user/steam-265690.log) with `PROTON_LOG=1 PROTON_DUMP_DEBUG_COMMANDS=1 DXVK_HUD=1 %command%` 

`PROTON_USE_WINED3D11=1` doesn't change much it seems.

The game uses Unreal Development Kit (UDK). Didn't find any relevant log either.

The redistributable packages seem to install fine (`../SteamLibrary/steamapps/compatdata/265690/pfx/drive_c/users/steamuser/My Documents/runprocess_log.txt`):

```
09/04/18 18:25:44 [AppID 265690] Exit Code (0) :  "Z:\data\SteamLibrary\steamapps\common\NaissanceE\_CommonRedist\vcredist\2010\vcredist_x86.exe" /quiet /norestart GLE 0
09/04/18 18:25:51 [AppID 265690] Exit Code (0) :  "Z:\data\SteamLibrary\steamapps\common\NaissanceE\_CommonRedist\vcredist\2010\vcredist_x64.exe" /quiet /norestart GLE 0
09/04/18 18:27:12 [AppID 265690] Exit Code (0) :  "Z:\data\SteamLibrary\steamapps\common\NaissanceE\_CommonRedist\DirectX\Jun2010\DXSETUP.exe" /silent GLE 0 
```

By the way the title is "NaissanceE".

**Comment by DarkFenX** [comment]
This is strange because it used to work under vanilla wine (steam launched from within wine).

Also worth to mention that its still doesn't work with proton 4.2-1.

**Comment by DarkFenX** [comment]
Starts in 4.2-7, i suppose issue can be closed.

**Comment by Simmonz** [comment]
I can confirm it launched and played for me in Proton 4.2-7 as well. It did freeze after changing the resolution and AA but after killing the process and relauching the game it was fine. I've since relaunched multiple times and played without issue.

Distro: Manjaro

GPU: RX 580 8GB

Driver/LLVM version: Mesa 19.0.6/8.0.0

Kernel version: 5.1.8-1-MANJARO

Proton version: 4.2-7

https://gist.github.com/Simmonz/b7ed30c603491054905dc2654e381d9f
