### ISSUE TITLE
Farming Simulator 17 (447020)

### ISSUE THREAD

**Issue by cameronthecoder** [ValveSoftware/Proton#1361]
# Whitelist Request
- Name of the game to be whitelisted: Farming Simulator 17
- Steam AppID of the game: 447020

## System Information
- GPU: GTX 970
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.15.0-33-generic
- Link to full system information report: [Gist](https://gist.github.com/Camnooten/2872ae4282321963664d048910611f98):
- Proton version: 3.7-3

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that no [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [x] Although I consider the gaming experience equal to Windows there are
      remaining issues:

- FPS drops when alot of textures have to load in at once, but after a couple of seconds it is fine.

**Comment by framingnoone** [comment]
Proton 3.16-4 and Vulkan 0.94, on older nVidia cards, give a black screen after alt-tabbing out and back.

Proton and wine's d3d11, render very slowly 3-5 fps, but alt-tabbing works.

Don't know whether that prevents white-listing, or not, but thought it should be reported. Will open a new issue later once I figure out what is needed.

**Comment by kisak-valve** [comment]
Hello @framingnoone, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by kisak-valve** [comment]
Farming Simulator 17 (447020)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2150.
@framingnoone posted on 2018-12-28T00:33:05:

# Compatibility Report
Farming Simulator 17
447020

## System Information
- GPU: GTX 650
- Driver/LLVM version: 415.18
- Kernel version: 4.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/framingnoone/0df32aa1017412a9482b40bf94724a22
- Proton version: 3.16-4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Proton Log
[steam-447020.log](https://github.com/ValveSoftware/Proton/files/2713632/steam-447020.log)

## Symptoms
Can't alt-tab without graphics rendering failure. Gameplay and fps otherwise is fine.

## Reproduction
Start game
load save game so you've got a farm visible
alt-tab out, alt-tab back in
Screen is now black, nothing visible.

I believe this also occurs in the main menu of Farming Simulator, though the proton log is of the previous described steps.

**Comment by kisak-valve** [comment]
@doitsujin, happen to know 1GB of vram could lead to this scenario?

**Comment by framingnoone** [comment]
I have found an issue that may be tangentially related, as the below "mostly black screen" issue happens on my machine as well. Don't have the expertise to be sure though.
https://github.com/doitsujin/dxvk/issues/775
