### ISSUE TITLE
[Whitelist] Overcooked (448510)

### ISSUE THREAD

**Issue by hzulla** [ValveSoftware/Proton#1391]
# Whitelist Request
- Name of the game to be whitelisted: Overcooked
- Steam AppID of the game: 448510

## System Information
- GPU: `GeForce GTX 1050 Ti/PCIe/SSE2`
- Driver/LLVM version: `4.6.0 NVIDIA 396.54` / `llvm 7~+rc2-1~exp3~oibaf~`
- Kernel version: `4.15.0-33-generic #396` 
- [system information](https://gist.github.com/hzulla/84e97a85141ad87f2b7f92914d19778b)
- Proton version: `3.7.3`

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that no runtime config options are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] Although I consider the gaming experience equal to Windows there are remaining issues:
  *No rumble effects on my linux-compatible gamepad*

**Comment by davernos** [comment]
I second this. Performance differs a little as usual (didn't measure the FPS), but it just works out of the box.

**Comment by pmykc1** [comment]
I get the following error log after crash on startup running from a clean 18.04 install:
https://gist.github.com/pmykc1/99f0a67b61fdb6cd4765f030147bf372
my system details are here:
https://gist.github.com/pmykc1/5c6eedd49b631980f3718aa3dc530b98

Edit: given that Overcooked is a unity game and I have an intel graphics card, I think that my issue is a specific case of this one:
https://github.com/ValveSoftware/Proton/issues/537

Second Edit: Problem solved with method in the linked issue thread. Whitelist definitely.

**Comment by kisak-valve** [comment]
Found in the 2018-10-05 white list update.

**Comment by gwemmie** [comment]
I'm hardcore not finding a way to get this working on AMD. AMD cards also have #537 (so it's an entire open-source drivers issue), and that workaround means you *have* to use DX11 just to run the game. From there, Intel works, but on AMD, the brightness on 3D objects is nonexistent. Screenshot attached:

![screenshot_2019-03-06_17-31-42](https://user-images.githubusercontent.com/5751606/53925729-cc819700-4035-11e9-9943-7be6915ddac6.png)

This seems to be a recurring issue with Unity games in WINE/Proton on... maybe just AMD for all I know? Definitely on mesa. But I don't understand it, because I don't know how to describe it in a way that a search engine understands (like maybe a specific term for it)? On top of that, I don't even know where to start--on the other Unity game I've dealt with this issue on, I fixed this issue by installing DXVK in that wine bottle and switching *from* DX9 to 11. The exact same switch that *caused* it here.

**Comment by kisak-valve** [comment]
Hello @Jimi-James, please open a new issue report with the compatibility report template.

**Comment by dlove67** [comment]
@Jimi-James I'm using AMD CPU and GPU and I'm having no issues with Overcooked working out of the box on Mesa(performance is lower than I expect it should be, but I don't have a similar build on windows to test): 
![image](https://user-images.githubusercontent.com/8529044/53926109-e62bda00-4047-11e9-9058-eaf4020cf449.png)

Make sure that you have vulkan installed (both x86_64 and i386 versions). Here's a gist of my build if you'd like it: 
https://gist.github.com/dlove67/37b9ebf3b64dee7bcbd555e7c1fee661

**Comment by gwemmie** [comment]
Vulkan was already installed, but oof, you're on mesa 19. Even Arch Linux, considered a bleeding edge distro, is on 18 because newer versions haven't finished going through proper testing. That's the only software difference between our systems, so I'll try it later (running out of time now).

But if that works, it's a problem. I don't feel comfortable having to run untested packages that are as crucial to my system in general (not just games) as mesa, just to play such a not-that-new, not-that-demanding game. In my case I'd have to switch to the AUR package that just pulls straight from mesa's git to have a version *almost* as new as yours (19.1). That's just not what the Whitelist should mean when it promises no unknown workarounds--a promise that's already being broken by just blindly adding games left and right whenever one person says it works on NVidia, before taking Intel or AMD into the equation at all.

**Comment by gwemmie** [comment]
Switching to mesa-git and llvm-libs-svn and everything else related didn't fix it. RADV and AMDVLK had identical results. Steam or native runtime made no difference. I took a big look at our differences with my Steam system info, comparing side-by-side. The only differences left are kernel version (even though I'm also on 4.19, and a newer 4.19.28-lts), and SSE4a support. But the only reason I'm not already rocking a Ryzen is I have yet to financially afford a switch from my old i7-5820k. And I already tried every proton version including betas back before my original comment and just forgot to mention it, sorry.

I doubt a missing obscure CPU instruction set could be the cause, so I'll open a bug report if downgrading my kernel the next time I get a chance doesn't do it. Whatever is the reason you don't have any issues, the one fatal difference, you're clearly an extremely lucky gamer, and I would call Overcooked's AMD support on proton still shaky as hell right now.
