### ISSUE TITLE
Proton Prerequired Driver's cause crash Cinnamon

### ISSUE THREAD

**Issue by terrestrian** [ValveSoftware/Proton#1439]
Firstly, I don't know if my problem is related or should be posted here. Remove if it isn't. Anyway. I am using very old AMD graphic card which is HD4850 (RV770). As normal:

-I went to Proton/PREREQS.md page and added required AMD drivers repository to my system and installed it.
-After installation it works fine but then I checked for updates and found some with Update Manager. 
-I installed them and rebooted my pc.

This is the problem. Now whenever I open my pc Cinnamon crashes. I am using Linux Mint 19 (Tara) and I don't know why this is happening. Is is something because my graphics card is very old and this repository doesn't support my card or something else?

**Comment by dreamer** [comment]
This really looks like Cinnamon issue and not Proton issue, but let's investigate:
Can you post logs here? (as gist, preferably) Reboot, and after crash get to terminal (e.g. with ctrl+alt+f3).
Xorg log from the last start is in `/var/log/Xorg.0.log`. Syslog since boot can be obtained with `$ journalctl --boot > ~/log`.

**Comment by terrestrian** [comment]
When this happened yesterday, I couldn't revert to original drivers so I formatted my system. Right now, I installed this drivers again and it worked fine. I also checked log life and found anything wrong. Seems like it is solved all by itself. 
Edit: Thanks for your comment and your help.

**Comment by dreamer** [comment]
@terrestrian can you close the issue then, please?
