### ISSUE TITLE
Games do not run without Python 2.7

### ISSUE THREAD

**Issue by MrQueeba** [ValveSoftware/Proton#15]
I attempted to run some games using Proton (including Quake 3 and Audiosurf, both of which are rated "Platinum" on WineHQ and run normally under normal Wine), and they do not run at all. After clicking "Play", steam will show in the friends list that I am playing the game for a fraction of a second, and then it will immediately change back to "Online". The games do not show up at all, with no windows appearing. I tested using Ubuntu 18.04.1 LTS, with a Radeon R9 270X GPU, and the latest mesa drivers installed from the PPA shown in the guide. I ran Steam via the terminal in order to check if there were any errors, and I saw no errors at all after running the games.
UPDATE: It turns out that after installing the python2.7 package, Proton functions properly. It seems that on some installs, Python 2.7 is not present, which causes Proton to not function.

**Comment by Mikerr1111** [comment]
What kernel version are you running?

**Comment by swick** [comment]
This doesn't sound like a driver problem. I had the same behavior and it turned out to be a missing dependency on python2.7. Just post the console output from when you launch the game.

**Comment by MrQueeba** [comment]
Can confirm that Python 2.7 not being installed is the issue. After installing the python2.7 package, Proton works properly.

**Comment by swick** [comment]
See also #9.

**Comment by Warrengbrn** [comment]
I had the same issue here and installing python 2.7 fixed the issue for me. I was using a gtx 1070 and driver 396 that I installed using Valve's guide.

**Comment by tcarrio** [comment]
Seems like the instructions should include installing Python 2.7, or confirming it already is.

Would be interesting to see this reworked perhaps, so it doesn't rely on an interpreter or libraries that may not be available. 

For now, I or someone can add some notes for Python in the README to make sure people don't miss it :+1:

**Comment by NoXPhasma** [comment]
The best way would be to write the python scripts 2.7 and 3.x compliant and remove the python 2.7 shebang.

**Comment by Warrengbrn** [comment]
Games still don't run for me without python 2.7 despite using proton 3.7-4 beta.

**Comment by Kira-PH** [comment]
It's been suggested that this is not the responsibility of Proton. However, the "Not my problem" and "Figure it out yourself" ethae are what drive many people away from using Linux _at all_.

Steam provides a fantastic end user experience that does not required users to feel around in the dark figure out why Steam isn't starting, and as this project moves forwards, it would be sensible for Proton to buy into the "responsible" principle of at the very least checking for its dependencies and alerting users when they are not fulfilled rather than quietly dumping a message in a log somewhere - if at all.

Ideally Proton would be bundled with all that it needs and have its environment variables set appropriately - or run in a container or chroot context.

This responsible delivery of fully working solutions is a step that is being taken, slowly, but needs to be adopted by many more developers if they truly hope for Linux-based operating systems to be seen as viable for desktop users both in the office and home.
