### ISSUE TITLE
[Whitelist] BUTCHER (474210)

### ISSUE THREAD

**Issue by s-m-k** [ValveSoftware/Proton#1517]
# Whitelist Request
- Name of the game to be whitelisted: BUTCHER
- Steam AppID of the game: 474210

## System Information
- GPU: NVIDIA Corporation GeForce GTX 970M/PCIe/SSE2
- Driver/LLVM version: NVIDIA 396.54
- Kernel version: 4.18.6
- Link to full system information report as [Gist]: https://gist.github.com/furai/c8ce8a1c183c5ed769f72aefba0513dd
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] I haven't experienced any issues.

**Comment by glubsy** [comment]
No reason to use Proton for this game, there is a native build already.

**Comment by s-m-k** [comment]
Sorry, you're wrong. I am the developer of the game. The native build doesn't work due to some incompatible update on Linux and we have no sane way to fix it at this point (I moved on to another project and have no time for that game anymore). Hence, we want to try the Steam Play feature instead,

Here's the details:
https://steamcommunity.com/games/474210/announcements/detail/1684800028906686550

And the "Technical support" discussion:
https://steamcommunity.com/app/474210/discussions/1/1733210552670627173/

In other words, we pretty much RELY on the Steam Play at this point to make the game work on newly updated Linux machines and to make our playerbase happy. There's literally no manpower left to fix the issues, as upgrading to a newer Unity version is too dangerous for everyone else (it's been proven to be backward-incompatible - i.e., spawning tons of bugs to fix - most of the time).

And no, releasing the source is legally impossible yet (the game is maintained by third party companies on other platforms). Got it?

**Comment by glubsy** [comment]
Thanks for taking the time to reply.

Is there a particular reason why the DRM-free build from the Humble Store works just fine for me? 

Specs: 
Kernel: 4.14.67-1-lts x86_64
Desktop Env: i3 4.15
Distro: Antergos Linux (Arch Linux based)
Device: laptop System: CLEVO Mobo: P370EM
CPU:    Quad core Intel Core i7-3740QM (-MT-MCP-) 3700 MHz
Graphics:
GPU: NVIDIA GK104M [GeForce GTX 670MX]
Display Server: X.Org 1.20.1 Resolution: 1920x1080 60.02hz
Nvidia driver version: 4.6.0 NVIDIA 396.54
OpenGL: renderer: GeForce GTX 670MX/PCIe/SSE2
Memory: 16 GB

**Comment by dubigrasu** [comment]
@s-m-k 
Whitelisted or not, you can still keep the old build on a separated branch for those still able play it (natively).

**Comment by s-m-k** [comment]
That's a good idea if it really works like that. Then most people will be happy that way, hopefully.

**Comment by dreamer** [comment]
@s-m-k In that thread you mentioned, that original bug in Linux build of your game is in specific Unity version - can you give us more details? Which Unity version is that?

[edit]
Latest Unity version in 5.6 branch is 5.6.5p3 - is this the one causing issues?

**Comment by s-m-k** [comment]
I had to re-check the sources - it seems that the game used 5.5.1f1 - even older than I somehow remembered.

**Comment by dreamer** [comment]
@s-m-k by you pulling Linux version off steam you accidentally made demo not playable (it still is advertised with Linux support). Since I can't test Linux version, I tested full version using Proton - game works on [my desktop](https://gist.github.com/dreamer/03179db6f82b01e06ec8fa41faf09f00), but crashes on [laptop](https://gist.github.com/dreamer/4f3773020ded88d4612e41de4dd67b7e), leaving zombie process behind. Additionally, the level editor is missing fonts (I needed to install `corefonts` to game prefix to fix that).

Crashdump: [2018-09-21_164542.zip](https://github.com/ValveSoftware/Proton/files/2405834/2018-09-21_164542.zip)

Can you put Linux version maybe into Beta branch, so I could retest if same problems happen to me on Linux version?

Also, I looked through release notes for Unity [5.5.2](https://unity3d.com/unity/whats-new/unity-5.5.2) to [5.5.6](https://unity3d.com/unity/whats-new/unity-5.5.6) and there were a lot of fixes in there - are you sure this crash does not happen to your Windows users as well?

**Comment by s-m-k** [comment]
We're putting the Linux binaries in a separate branch already, please be a little patient since I can't do it myself at the moment.

The game should work on Windows just fine, we haven't received any complaints and even tested it recently (and it sits there for months, if not more than a year).

**Comment by s-m-k** [comment]
We changed our mind:
https://steamcommunity.com/app/474210/discussions/1/1733210552670627173/?ctp=2#c1732087824995780002
