### ISSUE TITLE
Please show 'Steam Play Compatibility: Completely|Stable Stable|Unstable|Unplayable|Crashes|Won't Start" to Store

### ISSUE THREAD

**Issue by ShannonVanWagner** [ValveSoftware/Proton#1672]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

**Comment by lucifertdark** [comment]
There's already something similar to what you want
https://addons.mozilla.org/en-CA/firefox/addon/spcr-for-steam/
it adds onto the steam page the spcr rating for quite a few games.

**Comment by tr37ion** [comment]
The intention is good. From a marketing perspective it is not so good idea to show mostly negative information of games not running on Steam. It might be something to add to dev's backend interface.

PS: Please don't use bold fonts often. This might be counter-productive to your intention. Keep your writing simple and lean on Github.

**Comment by HonkingGoose** [comment]
Would adding a rating from SPCR really be helpful though? I feel that a rating on its own is no use, because you need to look at the reports themselves, to see if your similar configuration will work. 

A Platinum rating for example might only be relevant for users on Ubuntu 18.04, with Nvidia cards, with the proprietary 396.54 drivers. If you're using Fedora with an AMD gpu with MESA drivers things might not work. So a Fedora user sees the Platinum rating for Ubuntu and thinks, oh it works, buys game, and then finds out that the game doesn't work for them.
So any kind of rating system, I feel, should only show ratings for as close to your system as possible, to be of any use...

So blanket ratings are not really helpful after all, because those ratings are generally only relevant for precisely that configuration reported.

@ShannonVanWagner I think you made a mistake with filling in the pre-filled report. You have made one big header instead of header and then text.

I think if you edit your report to show this, it will show up like you wanted it to show up:


>\# Description
Please show 'Steam Play Compatibility: Completely|Stable Stable|Unstable|Unplayable|Crashes|Won't Start" + a link to the compatibility page for the game to Store pages for all games in the steam interface. This would enable me to quickly decide if I want to purchase the game or not, based on compatibility with my Linux via Steam Play.
>\# Justification
When I search through the steam store, I'm looking for games that work with my Linux OS.

Basically after a # sign, you should type the text for the header, and then press ENTER for a newline.

There is also a very handy [tutorial](https://commonmark.org/help/tutorial/)  for common Markdown, only takes 10 minutes and you're up to speed for the most part. Also try looking at: https://help.github.com/articles/basic-writing-and-formatting-syntax/

**Comment by kisak-valve** [comment]
Hello @ShannonVanWagner, this is a feature request for the Steam Store instead of Proton itself, so I've transferred this request to https://github.com/ValveSoftware/steam-for-linux/issues/5808.
