### ISSUE TITLE
[issue, too slow ~0.2fps] Droplitz (23120)

### ISSUE THREAD

**Issue by DoubyCz** [ValveSoftware/Proton#1679]
# Compatibility Report
- Name of the game with compatibility issues: Droplitz
- Steam AppID of the game: 23120

## System Information
- GPU: GeForce GTX 680/PCIe/SSE2
- Driver/LLVM version: 4.6.0 NVIDIA 390.48
- Kernel version: 4.15.0-34-generic
- Link to full system information report as [Gist](https://gist.github.com/DoubyCz/ddfa8a99e121fc3213206aa2db8a1ff3):
- Proton version: 3.7-6

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[PROTON LOG Included](https://ghostbin.com/paste/xhsn8)

## Symptoms
game is too slow, really slow one frame per 5 seconds

**Comment by HonkingGoose** [comment]
Hi @DoubyCz 
I already made a report on this game, could you add your report to my issue? #874 
We only use one report per unofficially supported game. 

It's always good to get verification that on a different system its also not working right, that way we can rule out a problem with my system specifically. :+1: 

By the way, did you get to actually "play" the game? On my system it just doesn't get to the main screen, because it crashes eventually. And it loads at like one frame per second or even less.

**Comment by kisak-valve** [comment]
Hello @DoubyCz, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/874#issuecomment-426435232.
