### ISSUE TITLE
Proton 3.16-2 compiled DXVK in debug mode?

### ISSUE THREAD

**Issue by LeJimster** [ValveSoftware/Proton#1766]
@Plagman @doitsujin 
A couple of users over at [GamingOnLinux](https://www.gamingonlinux.com/articles/proton-beta-316-2-is-out-for-valves-steam-play-system.12764/page=1#r137755) noticed the performance has reduced and the file size of Proton 3.16 has increased quite a bit.  It looks like a reoccurence of this issue #192.  The DXVK dll's are much larger than they should be and I have tested one title I know well with noticeable reduced performance compared to 3.7-8.

**Comment by aeikum** [comment]
Sigh, you're right.   Looks like the fix for #192 was dropped in the move to the new build system. Thanks for reporting, will fix soon.

**Comment by dubigrasu** [comment]
If we strip the existing ones, which command would be the proper one?
"strip --strip-debug", "strip --strip-unneeded",etc?

**Comment by LeJimster** [comment]
@aeikum does the bug affect Proton as a whole or just DXVK?  [adamhm](https://www.gamingonlinux.com/articles/proton-beta-316-2-is-out-for-valves-steam-play-system.12764/comment_id=137772) over at GoL seems to think each Proton update since 3.7-6 are quite bloated and they do seem to be compared to his 3.7-6.

**Comment by aeikum** [comment]
Yeah, I read those comments. We do purposely ship Wine with debug symbols included, so the binaries are large. However, Wine does correctly have -O2 optimizations enabled (and more incoming), so it shouldn't be impacted in the same way that DXVK is when built in debug mode. There was a bad build uploaded a long time ago that had symbols accidentally stripped and some other problems. That was build 3.7-2. My guess is that user snagged that and mis-labeled it as 3.7-6? Otherwise I don't know where they would've gotten a stripped wineserver from.

**Comment by Plagman** [comment]
This should be fixed, sorry about that.
