### ISSUE TITLE
Half-Life (70) - Mods under Proton

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1858]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Allow us to play Windows only Half-Life mods with Proton.

## Justification [optional] 
There are many older mods that simply do not have Linux binaries, this will allow us to play older mods without having to install Steam on a separate Wine prefix. Since Steam already ships libraries for all platforms with Half-Life, it might be feasible to detect whenever the mod doesn't contain the `gamedll_linux` line in its `liblist.gam` file to run under Proton.

## Risks [optional]
The only risk is I can see it's VAC with multiplayer mods, but Proton has proven to be VAC secure.

**Comment by kisak-valve** [comment]
Hello @LucesEnBabel, this is a feature request for the steam client rather than Proton itself. Between https://github.com/ValveSoftware/steam-for-linux/issues/5638, https://github.com/ValveSoftware/steam-for-linux/issues/5766, and https://github.com/ValveSoftware/steam-for-linux/issues/5677 this request is already covered.

Closing in favor of the existing feature requests.
