### ISSUE TITLE
[Bug] Age of Empires 2 HD has a input area that after typing a word it just dissapear in a black blackground (221380)

### ISSUE THREAD

**Issue by felisucoibi** [ValveSoftware/Proton#1868]
Hi, i'be been a bug mantainer of age of empires 2 in winehq for a few years, after all the fixes made this week to age of empires, there is only one more bug to be fixed, and the game will be completely fixed for proton.
To test it, just create a multiplayer room to play a match.
![imagen](https://user-images.githubusercontent.com/1285303/47839839-79ac8000-ddb4-11e8-9671-5a2b565ed45e.png)

In the photo there is a black input area, where you write things, but you can't read what you wrote, because font turns balck, and blinks a lot while writing.

This bug has been there since ever, since age of empires 2 no steam version and other old wine versions.

Bests

**Comment by kisak-valve** [comment]
Hello @felisucoibi, thanks for following @nsivov's request at https://github.com/ValveSoftware/Proton/issues/72#issuecomment-434960156.

@nsivov, I've adjusted #72 to reflect it is for the game in general. Since this is a general wine issue and unlikely to be proton-specific. I'm closing it in favor of https://github.com/ValveSoftware/Proton/issues/72#issuecomment-434959771.

The general idea here is that the benefits of having everyone discussing the same game together outweighs the noise for games that do not have official support. (And of course we want one issue per issue report for officially supported games.)
