### ISSUE TITLE
Doom 2016 with OpenGL is unplayable due to flickering (379720)

### ISSUE THREAD

**Issue by Warrengbrn** [ValveSoftware/Proton#201]
By default Doom starts in OpenGL. Switching to vulkan fixes this issue and gives essentially native performance, but the flickering was so bad I could not navigate to the options menu. Fixed this by forcing the game to switch to vulkan by adding "+r_renderAPI 1" to the launch options.

Tested on GTX 1070 with driver 396.51.

**Comment by LeJimster** [comment]
I experienced bad flickering also on the first launch but it was related to incorrect resolution in my case (I think I managed to confuse the client by switching displays).
I believe I Alt+Enter to go window mode and the set the correct resolution. After applying the correct resolution OpenGL worked perfectly for me.  Vulkan is the better option however.  Works flawlessly.

I'm running an RX Vega 56.

**Comment by adamkewley** [comment]
For followup information, I also had this issue with a 1900x1200 monitor (note: non-standard aspect ratio). DOOM was assuming I had a 1080p monitor. The issues went away as soon as I followed @LeJimster 's advice (put into a window) followed by altering the resolution manually.

**Comment by Warrengbrn** [comment]
Side note, I was playing on a 3440x1440 monitor. Maybe that had something to do with this as well.

**Comment by rkfg** [comment]
Oh, that's really the culprit! I don't have flickering but the screen is just black and the only flickering thing is the Steam overlay's FPS counter and notifications in the corner. It appears when I select OpenGL renderer AND 16:9 resolution while my display is 16:10 (1920x1200). OpenGL + correct resolution and Vulkan + incorrect resolution (and correct as well) are fine. Since the game defaults to 1920x1080 + OpenGL on first launch I had to apply the r_renderAPI workaround. I think Valve, being in control of depots and other metadata, could add a simple resolution detecting script (via xrandr) as a launcher that would fix the game config prior to starting the actual game.

**Comment by Plagman** [comment]
This should be fixed now. Can affected users confirm the flickering when doing fullscreen scaling in OpenGL is gone with Proton 3.7-6?

**Comment by Warrengbrn** [comment]
@kisak-valve Yes the issue is now fixed. I uninstalled the game and reinstalled it to reset the settings and when I started it, there was no flickering on the default settings this time when using opengl. Thank you.
