### ISSUE TITLE
Automatic creation of symlink of GameName to appid in compat folder.

### ISSUE THREAD

**Issue by greydmiyu** [ValveSoftware/Proton#2049]
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description
Automatic creation of symlink of GameName to appid in compat folder.

## Justification [optional]
Since the wine environment is stored in a directory named after the appid if and when we want to look at or adjust files in a given game's compat folder we need to either know the appid, know how to look up the appid, or just poke around the directories until we find it.  Furthermore, as the wine environments contain symlinks to ~ they stymie any reasonable attempt to use find or similar GUI tool.

## Risks [optional]

Possibility of orphan symlinks.

**Comment by kisak-valve** [comment]
Hello @greydmiyu, I think the most sensible implementation of this feature request would need to be handled on Steam's side so that the symlink can be cleaned up by Steam's game uninstall.

This is really close to the feature request at https://github.com/ValveSoftware/steam-for-linux/issues/5655 and I'm closing this in favor of the existing feature request.

**Comment by greydmiyu** [comment]
Ah, wrong layer, my apologies.
