### ISSUE TITLE
[686600] Rapture Rejects

### ISSUE THREAD

**Issue by Zlopez** [ValveSoftware/Proton#2062]
# Compatibility Report
- Name of the game with compatibility issues: Rapture Rejects
- Steam AppID of the game: 686600

## System Information
- GPU: NVIDIA GeForce GTX 960
- Driver/LLVM version: 4.6.0 NVIDIA 415.18
- Kernel version: 4.19.5-300.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/Zlopez/1433022f5f75aebc3155a622997b2997
- Proton version: Beta (3.16-4)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
The game crashes when started with this error:
![screenshot from 2018-12-06 19-08-18](https://user-images.githubusercontent.com/6943409/49603554-e30f4800-f98b-11e8-9940-01a1186c6921.png)

## Reproduction
1. Start the game

[steam-686600.log](https://github.com/ValveSoftware/Proton/files/2654307/steam-686600.log)

**Comment by GloriousEggroll** [comment]
i think this is a unity related nvidia bug: https://devtalk.nvidia.com/default/topic/1044264/415-13-415-18-amp-415-18-02-breaking-unity-engine-games-in-wine/?offset=12

supposedly fixed in 415.18.04
https://www.gamingonlinux.com/articles/nvidia-have-released-another-new-beta-vulkan-driver-fixes-issues-with-unity-games.13095

**Comment by kisak-valve** [comment]
Hello @Zlopez, as mentioned by @GloriousEggroll, this is a known video driver regression. Please downgrade to nvidia 410.xx (or older) or upgrade to nvidia 415.18.04.
