### ISSUE TITLE
Farming Simulator 19 Black Screen (787860)

### ISSUE THREAD

**Issue by srtomy** [ValveSoftware/Proton#2102]
# Compatibility Report
- Name of the game with compatibility issues: Farming Simulator 2019
- Steam AppID of the game: 787860

## System Information
- GPU: Geforce 840m
- Driver/LLVM version: nvidia 415.23
- Kernel version: 4.15.0-20-generic
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/srtomy/7e35a08e25f6028037f92426500c6c14)
- Proton version: 3.16-5 Beta

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-787860.log](https://github.com/ValveSoftware/Proton/files/2683781/steam-787860.log)

## Symptoms
black screen

## Reproduction
start the game on D3D_11

**Comment by Guy1524** [comment]
This is fixed in DXVK 0.94, you can either manually upgrade or wait for the next proton version, which will probably update to it.

**Comment by srtomy** [comment]
Ok, it worked.

**Comment by gruo** [comment]
There is a problem when using the Thrustmaster T.16000M FSC joystick with this game. The game will detect this stick properly (in gamepad settings, the joystick name is readable and there is a preset configuration which maps all keys) without manually intervention. However, once in the game using the default settings the camera constantly spins. When I want to manually configure the mapping the entered keys are completely wrong (hitting the d-pad right inserts key 10, which is another one). That's why I assume the mapping in the background is broken. Any ideas how to fix this? I am using proton version 5.0-7.

Also note that testing with a different game ([Starpoint Gemini 2](https://www.protondb.com/app/236150)) the controller works without flaw. Using _jstest_ it is working fine under linux too.

I am aware of https://github.com/ValveSoftware/Proton/issues/3188, but this did not help.

Hopefully I entered this on the right topic. (I read somewhere that there should be only one report per unofficially supported game.)

**Edit:** Please note the additional information I provided in the [Steam Techincal Discussion](https://steamcommunity.com/app/787860/discussions/1/2242174386381103256/).

**Edit2:** Can anyone please confirm that this comment was read by someone? I'm not sure if it is the right place because the issue is already closed.
