### ISSUE TITLE
DOOM 2016 Working with OpenGL but not Vulkan

### ISSUE THREAD

**Issue by gralco** [ValveSoftware/Proton#219]
The game runs fine when using OpenGL 4.5 but fails to even start when I try to run it using Vulkan.

If I enter the launch option "+r_renderAPI 1" then I get the following error "DOOM Console" pop up: https://i.imgur.com/ccaMK0J.png

My Crash html file: https://pastebin.com/raw/1dmRPH2Q

My ErrorLog txt file: https://pastebin.com/raw/UQFv1KgB

In my terminal emulator it says `INTEL-MESA: warning: Haswell Vulkan support is incomplete` when it crashes, however, I am not using my integrated GPU to run the game.

Specs:
Fedora 28 with Linux 4.17.14-202.fc28.x86_64
Driver Version 396.54 (from https://negativo17.org/nvidia-driver/)
MSI GTX 970
Intel i5 4690K
16GB @ 1866MHz SDRAM

Here's my "vulkaninfo" output: https://pastebin.com/raw/71JGZuW9

**Comment by GabrielMajeri** [comment]
It looks like you also have installed the Vulkan driver for your Intel HD integrated graphics. It seems the game tries to run with that (since it's first in the list) and it fails.

Could you try setting the global environment variable `VK_ICD_FILENAMES` to point to your NVIDIA Vulkan ICD file?
It should be something like `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`, and then re-run the game.

**Comment by gralco** [comment]
@GabrielMajeri this fixed my issue, the file was specifically `/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json`.

Thank you!

**Comment by gralco** [comment]
By default, `VK_ICD_FILENAMES` on my system is empty.

Maybe Steam can somehow automatically select the prefered Vulkan GPU? A new issue can be opened regarding this.

I can close this issue since it is resolved from my end.
