### ISSUE TITLE
Nier:Automata Not starting due to network errors with whitelisted proton version (524220)

### ISSUE THREAD

**Issue by MayeulC** [ValveSoftware/Proton#2247]
# Compatibility Report
- Name of the game with compatibility issues: Nier:Automata
- Steam AppID of the game: 524220

## System Information
- GPU: R9 Fury
- Driver/LLVM version: Mesa 18.3.1, LLVM 7.0.0
- Kernel version: 4.20.3-arch1-1-ARCH
- Full system information report: [Gist](https://gist.github.com/MayeulC/850223e7a821483dce5eb37a3a96b270)
- Proton version: 3.7-8 (as whitelisted) and 3.16-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. (N/A, this specific issue doesn't seem to exist)
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
The game displays a dialog box (will put a screenshot here as soon as possible) stating that the servers could not be contacted. The available options are to retry and open a web browser.

This occurs when the proton version whitelisted by valve (3.7-8) is selected. Forcing 3.16-6 allows the game to be played flawlessly.

## Reproduction
This can probably be reproduced on any system affected by the previous gnutls issues, that were subsequently fixed in Proton. This was reproduced on Arch Linux (native libraries).

**Comment by aeikum** [comment]
I'm also on Arch Linux. I don't have any problem launching Nier and getting to the main menu from `steam`. I do see the same failure when using `steam-native`. This is expected since Arch doesn't provide libgnutls26, which is what Proton 3.7-8 is linked against. Newer Protons link against libgnutls30, which Arch does provide. By using `steam-native`, you are preventing Proton 3.7-8 from finding the libgnutls26 that the Steam runtime provides.

Do you have a reason to prefer using `steam-native`?

**Comment by lavadrop** [comment]
Same problem on Solus 4.1
However, Denuvo appears to authenticate the license if run from bundled steam. After that, one can close the game, exit steam and restore the use of steam-native via Linux Steam Integration toggle.

Probably the issue stems from this: https://github.com/ValveSoftware/Proton/issues/1757#issuecomment-431571624

**Comment by kisak-valve** [comment]
Hello, please retest this game with Proton 6.3-6 and see if any regressions have crept in since this issue was last evaluated.
