### ISSUE TITLE
Lost In Vivo (963710)

### ISSUE THREAD

**Issue by es20490446e** [ValveSoftware/Proton#2354]
Works on Wine 4.2 with Wine Mono 4.7.5, but not on any Proton till 3.16-7 Beta.

The error is:
> load_builtin_dll: missing file: ${HOME}/.local/share/Steam/steamapps/common/Proton 3.16/dist/lib/wine/mscorlib.dll.dll.so

The game itself contains a "mscorlib.dll" file in:
> ${APP_DIR]/LIV_Data/Managed/

**Comment by kisak-valve** [comment]
Obligatory reference to #18.

**Comment by nsivov** [comment]
It's Unity based, load_builtin_dll line is a part of probing sequence that mono itself does, it shouldn't be an issue. @es20490446e could you expand your report with full log, and filling report template?

P.S. it's unlikely about .NET compatibility aka #18.

**Comment by es20490446e** [comment]
- [Proton log](https://gist.github.com/es20490446e/39b9c4d8c763e8ca9695a93c76baa83c)
- [Game log](https://gist.github.com/es20490446e/1f4ee35ee2a227b523984c464f32cf66)
- [System specs](https://gist.github.com/es20490446e/382e7cb95e24362f9d910746e9183f4c)

**Comment by nsivov** [comment]
So what happens when you start it? I get launcher running, starting in windowed mode gets me to main menu.

At what point does it fail for you and how?

**Comment by es20490446e** [comment]
If it is started with no arguments, it crashes right away with an error message telling that the attached [game log](https://gist.github.com/es20490446e/1f4ee35ee2a227b523984c464f32cf66) and a core-dump have been generated.

If you start it with the arguments posted in [ProtonDB](https://www.protondb.com/app/963710), you are presented with a window were you can choose the resolution and graphic level.

But once you click on the "launch" button it leads to a black window, no matter if you ticked the "windowed" option or not. No sound is played either.

**Comment by es20490446e** [comment]
Last update breaks the game in Wine too, from 1.x to 2.x.

After the intro, the grame crashes with a black screen.

**Comment by es20490446e** [comment]
Game added to the [Wine AppDB](https://appdb.winehq.org/objectManager.php?sClass=application&iId=19307). Tests for 2.x are pending approval.

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: Mesa 20.0.0-devel (git-acd36e4 2019-11-22 bionic-oibaf-ppa)
- Kernel version: 5.4.0-050400rc7-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-8

**Compatibility Report**

Game worked out of the box in both fullscreen and windowed mode, alt+tab between desktop and game also worked. Including log of playing through the first parts of the game.

[steam-963710-proton-4.11-8.log.zip](https://github.com/ValveSoftware/Proton/files/3882835/steam-963710-proton-4.11-8.log.zip)
[system_info.txt](https://github.com/ValveSoftware/Proton/files/3882836/system_info.txt)

Note that there is a bug with the games audio settings. You have to adjust audio level in the option first time launching the game (just move the volume slider a notch, so that the volume settings are saved). Unless you do this, the in-game audio will be completely silent (even though the volume looks maxed). This bug affects Windows users too.
