### ISSUE TITLE
[BUG] Constant up key/button press

### ISSUE THREAD

**Issue by Hacksawfred3232** [ValveSoftware/Proton#2359]
Apparently there is no template for submitting bug reports (Which is weird for this kind of software), but here we go anyway. I assume this is got to be something to do with how steam/Proton handles Xbox 360 controller (Which i will be refrencing as "game-pad" for the later of this report) and/or general input for games, but i have discovered this bug on two occasions:
Artificial Defence: Game play with mouse + keyboard is fine. But when using a game-pad, it is constantly stuck moving to the left/up.
Sonic Adventure DX: Game is unplayable due to both keyboard and possibly game-pad movement stuck moving left/up in both configuration tool and game. 
There might be more games suffering from this bug. I concluded that this is a bug with Proton by doing the following:
1. Tried both games without a game-pad. Had no effect in Sonic Adventure DX.
2. Disabling all steam-related input by blanking out all options in "guide cord" settings. Had no effect in both games.
3. Finally launching both games by targeting them with a standalone setup of WINE. The bug is gone, and the games are controllable again, despite having visual glitches due to missing files.

Can anyone shred any light on this problem?

**Comment by doublez13** [comment]
https://github.com/ValveSoftware/Proton/blob/proton_3.16/.github/ISSUE_TEMPLATE/compatibility-report.md

**Comment by Hacksawfred3232** [comment]
smh, BUG REPORT, NOT COMPATIBILITY REPORT! It is a bug with Proton itself! I clearly stated that in my first post.

**Comment by kisak-valve** [comment]
Hello @Hacksawfred3232, there's too many moving parts to generalize issues without investigating the root cause on a per-game basis. Compatibility reports are bug reports to track how Proton acts with individual games, not bugs in the games. Please open a new compatibility report for Artificial Defense and add your experience with the Sonic game to #427.

**Comment by Hacksawfred3232** [comment]
Okay, let me make this clear. This is a BUG in PROTON. not a BUG in the GAME. I clearly stated that the games work outside of Proton in WINE. Get your facts straight, and try again.
Seeing that you just re-opened this issue while i was writing this + ranting about how you misread my first post, i guess you are going to acknowledge that this is a bug in software that you or one of your co-workers have missed and you are going to fix it?

**Comment by kisak-valve** [comment]
The issue report was reopened because my request did not invalidate your feedback, but clearly you're more interested in being combative than reading what I typed.

Let me make this clear, compatibility reports are for bugs in Proton.

At this point it would be better to start over and you've earned yourself a 24 hour timeout for your behavior.

**Comment by ghost** [comment]
I've had this issue in NFS: Undercover and Thief 3: Deadly shadows. it drives me mad

**Comment by ghost** [comment]
Splinter Cell Chaos Theory, same issue

**Comment by ghost** [comment]
need for speed™ same story. i couldn't even quit the game
