### ISSUE TITLE
NieR: Automata crashes on startup

### ISSUE THREAD

**Issue by l0b0** [ValveSoftware/Proton#2428]
# Compatibility Report
- Name of the game with compatibility issues: NieR: Automata
- Steam AppID of the game: 524220

## System Information
- GPU:

    ```
    $ lspci | grep VGA
    01:00.0 VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)
    ```
- Driver/LLVM version: nvidia 418.43-7
- Kernel version:

    ```
    $ uname --kernel-release 
    5.0.2-arch1-1-ARCH
    ```
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/l0b0/b87bfad5db060bbfbce7250584b433c7
- Proton version: 3.7-8

## I confirm:
- [x] that I haven't found an existing *[and relevant](https://github.com/ValveSoftware/Proton/issues/129)* compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-524220.log](https://github.com/ValveSoftware/Proton/files/2982025/steam-524220.log)

## Symptoms 

After a few seconds a white window about 1500x1000 pixels shows up and another window displays the following error message:

> ERROR : Graphic::Startup() FAILED. No Graphic Memory

## Reproduction

1. Install Nier:Automata for the first time.
1. Run it right after it's installed.

**Comment by doitsujin** [comment]
Looks like your Nvidia driver isn't set up correctly, you currently seem to be using Nouveau:
```
    Driver:  nouveau NV120
    Driver Version:  4.3 (Compatibility Profile) Mesa 18.3.4
```

**Comment by l0b0** [comment]
I've been using Nouveau for some years now, including for games. I guess it's not supported by Proton?

**Comment by doitsujin** [comment]
Not really, the main issue in this case being that Nouveau has no Vulkan support. You need the proprietary driver for that.

**Comment by varris1** [comment]
> I've been using Nouveau for some years now, including for games. I guess it's not supported by Proton?

No. IIRC Nouveau with Maxwell still has no reclocking (and as doitsujin mentioned, no Vulkan) support. Are you sure you've played games with nouveau before? It's hard to believe.

**Comment by kisak-valve** [comment]
Hello @l0b0, you can avoid the need for need for a working vulkan driver by adding `PROTON_USE_WINED3D11=1 %command%` to the game's launch options to make it use the D3D11 to OpenGL render path, however, underwelming performance is expected when using that option compared to using vulkan and there is a lack of required signed firmware from nvidia to do reclocking with Maxwell refresh cards and nouveau.

**Comment by HonkingGoose** [comment]
@l0b0 For reference: here are the requirements to use Proton:
https://github.com/ValveSoftware/Proton/wiki/Requirements

---

The Nvidia Nouveau drivers are sadly in a very bad state for newer GPU's, because like kisak-valve said: there's no support for re-clocking the GPU, and that's necessary to get good performance out of your card. 

It's quite literally a waste of money to use the Nouveau drivers for newer Nvidia GPU's, because you're not getting the performance you paid for. So if you want to keep using your Nvidia GPU for gaming, you really should use the proprietary driver. 

See https://www.phoronix.com/scan.php?page=article&item=nouveau-nvidia-eoy2018&num=1 for a comparison between Nouveau and the proprietary drivers. You can see that Nouveau performs a lot worse in nearly all gaming benchmarks, and only wins on some compute benchmarks.

---

Now the good news is, if you want to use open-source drivers; AMD's open-source *mesa* drivers are quite good these days. So if you use a recent AMD card like a RX580/RX590 or Vega 56/64 or Radeon VII, you can use the opensource *mesa* drivers and get competitive performance. 
But to be honest, if you only care about performance; Nvidia still wins with a good margin with use of their proprietary driver.

You can check how the performance between AMD Mesa and Nvidia proprietary stacks up, so you can make a informed decision. See for example this recent benchmark of the GTX 1660 Ti versus some recent AMD cards: https://www.phoronix.com/scan.php?page=article&item=nvidia-gtx1660ti-linux&num=3

---

I hope this information proves helpful for you. To be clear, I'm not bashing on your desire to use open-source drivers. I just want to put this information out there, so that you can inform yourself, and make your own choices. :+1:

**Comment by l0b0** [comment]
Thank you all very much for this information! And a massive thank you for developing this - the last reason to keep Windows around is finally going away. I'll make sure to support a more open source-friendly GPU vendor next time. (I had naively thought that since there were open source drivers at all for both AMD and NVIDIA they would be approximately equal.)
