### ISSUE TITLE
Games not run

### ISSUE THREAD

**Issue by mstrvladi** [ValveSoftware/Proton#2438]
Hello, the problem is this: I use Steam in Ubuntu 18.04 bionic release. I recently played Doom using SteamPlay Proton 3.16_4. Everything worked fine until:

1- Due to an error, Steam was uninstalled.
2- Reinstalled Steam.
3- I configured the path of the games folder.
4- Now the games do not start, nothing just happens. Only the message "Preparing for launch DOOM" appears, disappears and the game no longer starts.
5- Cuphead was also installed, it worked well and now the same thing happens.

Before this, everything was fine.

I appreciate you can guide me. Thank you.

**Comment by kisak-valve** [comment]
Hello @mstrvladi, you're most likely experiencing https://github.com/ValveSoftware/steam-for-linux/issues/6045. Opt into Steam's beta client and/or go to Steam -> Library dropdown -> Tools and install Proton 3.16 from the list.

**Comment by mstrvladi** [comment]
It was already installed, my previous message says:

"I recently played Doom using SteamPlay Proton 3.16_4"

**Comment by romulasry** [comment]
FD LIMIT REQUIREMENTS (systemd < 240)

Proton uses the 'esync' patchset for performance improvements in multi-threaded games. It can require a higher File Descriptor limit per process than what it set up by default in some distributions. If you're not running Ubuntu, SteamOS or Debian, please follow the instructions over at https://github.com/zfigura/wine/blob/esync/README.esync to increase your FD limit. This is no longer required if you are using systemd 240 or later.

https://github.com/ValveSoftware/Proton/wiki/Requirements

Someone updated Proton 3.16 and I had a similar (or the same) bug as you. Updating systemd fixed it, but if you can't do that you have to update your fd limit otherwise it wouldn't launch Proton at all. I didn't even see anything saying that in the logfile in the console. That is a bug imho. It should say that it needs more not to exit with no console log indicating so.
