### ISSUE TITLE
Question, Running csgo windows version in proton (730)

### ISSUE THREAD

**Issue by ordinall** [ValveSoftware/Proton#2505]
Will running windows version via steam play trigger a vac ban ? I mean basically native linux version uses ToGL and steam play uses DXVK so i wanna check if the proton have any performance benifit, just wanted to make sure that doing so is safe

**Comment by sat3ll** [comment]
The game doesn't even start when Steamplay is forced on it (tested Proton: {4.2-1, 3.16-8 Beta, 3.7-8}). 
Your question would be a good follow up to the statement above.

**Comment by Leopard1907** [comment]
SteamPlay utilize DXVK for D3D10 and 11 titles.

For d3d9 titles , it uses wined3d.

I'm pretty sure if it would work on SteamPlay ; you would be seeing worse framerates compared to native CS GO.

**Comment by sat3ll** [comment]
@Leopard1907 can you try running SteamPlay csgo? Because it doesn't run for me and if it runs for you then it could indicate a problem on my side.

**Comment by ordinall** [comment]
I will try today as i have windows files of csgo

**Comment by Leopard1907** [comment]
@Ordinall Depots are shared already , only binaries are different. Rest is the same.

https://steamdb.info/app/730/depots/

Additional download size would be : 343.17 MiB

**Comment by ordinall** [comment]
i tried forcing csgo in steam proton 4.2-2 and it doesnt launch, same as @sat3ll , steam show that its running but nothing happens. here is the log file proton generated 
http://pasted.co/b8479dbf

**Comment by ghost** [comment]
I used to play CSGO through Wine for a long time, never got banned. 

CSGO uses D3D9, not 10 or 11, so DXVK will not work.

You would need an AMD card and Gallium Nine to get it to launch and run well. It uses a native D3D9 driver in mesa that only supports AMD cards.

https://github.com/iXit/wine-nine-standalone

The CSGO Linux performance was fixed earlier this year though, and it's significantly better than Wine now. So I have no need, and wouldn't recommend running CSGO in Wine anyway now.

CSGO on Linux was terrible for the last half of 2018 because of the Panaroma update which wasn't tested on Linux and destroyed performance and caused stutters.

If you're looking for a better CSGO experience then use cpupower to enable performance governor and disable all cstates but 0 and 1. Make sure you're not playing with any compositor or Vsync. Make sure raw input is on, and disable mouse acceleration even if you do because that's bad anyway. https://wiki.archlinux.org/index.php/Mouse_acceleration#Disabling_mouse_acceleration

**Comment by ordinall** [comment]
thanks for your response. I guess the native one works better by the experience of @z0z0z
