### ISSUE TITLE
Non-Steam Game launch options syntax issues remain [Steam+steamplay syntax bugs] 

### ISSUE THREAD

**Issue by jarrard** [ValveSoftware/Proton#2718]
This is a general notice to let valve know that when you add a non-steam game to the library you encounter 2 issues.

1) The added shortcut has incorrect target and application folder specified, often it will put the exe in the launch options section, this is incorrect behaviour, you can resolve this by selecting CHANGE and the game exe again (don't forget to delete nonsense in set launch options section).

2) Set Launch Options is problematic and seems it ignores %command% syntax and thus will try to set all arguments after the game exe. IT SHOULD be  +OPTIONS %exe% +ARGUMENTS however its doing %exe% +OPTIONS +ARGUMENTS

It would be nice if these 2 issues were fixed, no doubt lots of new comers to steamplay are getting flabbergasted by these issues.

**Comment by dreamer** [comment]
As for (1): this issue is for Steam client rather than Proton. If you decide to move this issue to ValveSoftware/steam-for-linux please add specific steps you took to add the Windows game from outside of Steam. There are multiple ways to install a Windows game in Linux and Steam does not support any of them out of the box (some manual tweaking is always required). Adding a Linux native game installed outside of Steam to Steam library works fine (but that's not what this issue is about).

I actually managed to reproduce a problem here (when trying to add a Windows only game from GOG, by pointing Steam directly to installed .exe file), but I am not sure if it's the same problem you are having - I am hitting bug: https://github.com/ValveSoftware/steam-for-linux/issues/5220

(2) ValveSoftware/steam-for-linux#6046

**Comment by jarrard** [comment]
Ok then I'll mention it to steam linux git
