### ISSUE TITLE
Proton games on NTFS partition fail to start due to missing lock file

### ISSUE THREAD

**Issue by BlueGoliath** [ValveSoftware/Proton#2730]
Some Proton games fail to start on NTFS partitions due to a missing lock file. All of the steps on the Wiki on setting up Proton with NTFS drives where followed. The error message is:

Traceback (most recent call last):
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/proton", line 325, in <module>
    with prefix_lock:
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/filelock.py", line 322, in __enter__
    self.acquire()
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/filelock.py", line 251, in acquire
    self._acquire()
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/filelock.py", line 383, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/ty/Windows_Linux_Shared/Steam/Windows/steamapps/compatdata/271590/pfx.lock'
Traceback (most recent call last):
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/proton", line 325, in <module>
    with prefix_lock:
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/filelock.py", line 322, in __enter__
    self.acquire()
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/filelock.py", line 251, in acquire
    self._acquire()
  File "/home/ty/.local/share/Steam/steamapps/common/Proton 4.2/filelock.py", line 383, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/ty/Windows_Linux_Shared/Steam/Windows/steamapps/compatdata/271590/pfx.loc

This happens on both Arch Linux and in Fedora 30.

**Comment by dreamer** [comment]
When it happens, does directory `/run/media/ty/Windows_Linux_Shared/Steam/Windows/steamapps/compatdata/271590` exist?

What is the output of

    $ echo foo > /run/media/ty/Windows_Linux_Shared/Steam/Windows/steamapps/compatdata/271590/bar

**Comment by TaiTair** [comment]
I have the same problem. Scrap Mechanic runs if I leave it on ext4, stops working if I move it to NTFS. All steps in the wiki were followed.

Output of the echo is nothing. It runs without errors.

**Comment by TaiTair** [comment]
Attached is the proton log for the game.
[steam-387990.log](https://github.com/ValveSoftware/Proton/files/3218799/steam-387990.log)

The only errors that seem relevant to me are:
ERROR: ld.so: object '/home/ttr/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/ttr/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/ttr/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/ttr/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

Which is very weird because I disabled the steam overlay for this test.

**Comment by dreamer** [comment]
@TaiTair empty output from that echo means that directory exists and partition is mounted read-write so it's useful information.

"ERROR: ld.so: " are not relevant in any way.

You need to look at stderr (output in terminal) while running Steam to see the problems @BlueGoliath mentioned. Your log includes this:

    Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x7b43d64d).
    0231:fixme:dbghelp:elf_search_auxv can't find symbol in module
    Register dump:

Which means it is more of a game-related problem.

**Comment by TaiTair** [comment]
If I run steam in the terminal I get this:

Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2019-06-03 09:11:09] Startup - updater built Apr 29 2019 20:58:13
[2019-06-03 09:11:09] Verifying installation...
[2019-06-03 09:11:09] Verification complete
Fatal : VkResult is "ERROR_INITIALIZATION_FAILED" in /home/pgriffais/src/Vulkan/base/VulkanSwapChain.hpp at line 210
[2019-06-03 09:11:21] Shutdown

This is without trying to run anything. I'll try running Scrap Mechanic on NFTS again with steam in terminal when I get the time.

**Comment by TaiTair** [comment]
Update: Fixed DXVK, Launched steam with terminal, moved game back to NTFS partition, verified installation files. Game launches correctly from NTFS partition.
DXVK fix might be irrelevant for this since I use PROTON_USE_WINED3D flag for this game.
I think what fixed it was:

1. Setting up the symbolic link for compatdata on the NTFS partition.
2. Verifying files after moving installation folder.
