### ISSUE TITLE
Proton stopped working

### ISSUE THREAD

**Issue by facePlanted** [ValveSoftware/Proton#2857]
Hi I'm running Debian Stable (9.9 Stretch), kernel 4.9.0-9-amd64
and nvidia drivers version 430.26.
Everything worked fine for months but after the last Proton update (on Steam beta), I can't run most proton games anymore.

Dark souls II and Tekken 7 used to work (tekken 7 with proton version 3.16-4 as per "Valve testing" and dark souls II with proton 4.2-8)

I tried to verify the files, reverted to Steam stable (not beta), install previous nvidia drivers,
delete the corresponding pfx folder in compatdata,
tried to check the proton debug files but i can't guess the problem.

I'm attaching some proton debug files for Dark Souls II, tekken 7
and deep rock galactic, which interestingly works, with proton 3.16-4 but not with 4.2-9)

[steam-389730.2.log](https://github.com/ValveSoftware/Proton/files/3364156/steam-389730.2.log)
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/3364157/steam-389730.log)
[steam-335300.2.log](https://github.com/ValveSoftware/Proton/files/3364158/steam-335300.2.log)
[steam-335300.log](https://github.com/ValveSoftware/Proton/files/3364159/steam-335300.log)
[steam-548430.2.log](https://github.com/ValveSoftware/Proton/files/3364160/steam-548430.2.log)
[steam-548430.log](https://github.com/ValveSoftware/Proton/files/3364161/steam-548430.log)

**Comment by facePlanted** [comment]
And the 'System Information' file
[systemInfo.txt](https://github.com/ValveSoftware/Proton/files/3364164/systemInfo.txt)

**Comment by facePlanted** [comment]
Oh also, when I run Steam, after logging in, I have the file / process
/home/myhome/.steam/ubuntu12_32/../ubuntu12_64/vulkandriverquery
which takes 100% load on 1 core.

No matter if I keep or kill the process, tekken 7 and dark souls 2 don't work,
which deep rock galactic keeps working.

Let me know if you want me to test other games or provide more info,
native games are working fine.

**Comment by kisak-valve** [comment]
Hello @facePlanted, in your logs: `err:plugplay:sdl_driver_init SDL installation is old! Please upgrade to >=2.0.6 to get accurate joystick information.` and `err:module:load_builtin_dll failed to load .so lib for builtin L"DINPUT8.dll": /mnt/sda1/SteamLibrary/steamapps/common/Proton 4.2/dist/bin/../lib64/wine/dinput8.dll.so: undefined symbol: SDL_JoystickGetType` hint that Proton is somehow using the distro-provided SDL2, which is too old for Proton.

Right now, Proton needs SDL 2.0.9 or newer.

**Comment by facePlanted** [comment]
Hey thanks for your help, so I've first tried to build and install SDL2-2.0.9 from source (but same result),
then I've removed the debian packages and reinstalled the sources (same result),
then I've removed also the SDL files from source (with "make uninstall") (but same result).

I'm attaching the current proton debug files for dark souls 2 and tekken 7, thank you :)

[steam-335300.log](https://github.com/ValveSoftware/Proton/files/3364200/steam-335300.log)
[steam-389730.log](https://github.com/ValveSoftware/Proton/files/3364201/steam-389730.log)

**Comment by facePlanted** [comment]
Well at least now Deep Rock Galactic runs with Proton 4.2-9 :)

**Comment by ghost** [comment]
Looks like it might be something that doesn't show up in the game logs. Logs are not always worth something. A lot of exceptions happening though in at least one log.

**Comment by facePlanted** [comment]
Upgrading to Debian 10 (Buster) solved the issues
(dark souls 2 runs again, on 4.2-9, and tekken 3 runs again, on 3.16-4, so i guess also the other games are fine)

It sucks that i've lost my save game of dark souls 2 (73 hours of progress and grinding)
as I've deleted the pfx folder (in compatdata) in the hope that proton would regenerate it correctly.

Didn't know that the save files are inside the 'proton-prefix' of the game.

**Comment by OderDochNicht** [comment]
It is said, Skyrim: TESV Special Edition should run fine out of the box.
This is why I reinstalled it with Steam on a 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux four days ago, with all the latest stable (buster) updates. No luck. The "Play", "Options", "Support" and "Exit" selector will show up and is working but a soon as I select "Play", after a short littewhile, nothing more than a black window opens.
I searched around with startpage and found some "adjustment" which I tried:
Install python-games-sdl2, xact via proton/winetricks, ...
I even installed a Linux Mint (4.15. no luck), updated&upgraded it, got the newest mesa from ppa, all that stuff (no luck). Got kernel 5.0.0-20 (fucked up gpu and usb recognition and - no luck). Just the same as with buster.
So, if all the silver, gold or platinum entries in proton.db are real, something happend to proton or packages it depends on.
32 GB of memory should be enough for SkyrimSE, I'd say.

No luck in any logs, btw.

I'm here on an older buster. That's why inxi shows mesa 18. Will update it when back to the gaming machine.

`System:    Host: monster Kernel: 4.19.0-5-amd64 x86_64 bits: 64 Desktop: Xfce 4.12.4 Distro: Debian GNU/Linux 10 (buster) 
Machine:   Type: Desktop System: Micro-Star product: MS-7A32 v: 1.0 serial: N/A 
           Mobo: Micro-Star model: X370 GAMING PRO CARBON AC (MS-7A32) v: 1.0 serial: H616140063 UEFI: American Megatrends 
           v: 2.I1 date: 05/14/2019 
CPU:       Topology: 8-Core model: AMD Ryzen 7 1700X bits: 64 type: MT MCP L2 cache: 4096 KiB 
           Speed: 1961 MHz min/max: 2200/3400 MHz Core speeds (MHz): 1: 1961 2: 1880 3: 1938 4: 2022 5: 2019 6: 1850 7: 1877 
           8: 2280 9: 1924 10: 2108 11: 1873 12: 2067 13: 1902 14: 2093 15: 2016 16: 1927 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Lexa PRO [Radeon RX 550/550X] driver: amdgpu v: kernel 
           Display: server: X.Org 1.20.4 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa resolution: 5120x1440~60Hz 
           OpenGL: renderer: Radeon 550 Series (POLARIS12 DRM 3.27.0 4.19.0-5-amd64 LLVM 7.0.1) v: 4.5 Mesa 18.3.6 
Audio:     Device-1: AMD Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k4.19.0-5-amd64 `

` lshw -c cpu
  *-cpu                     
       description: CPU
       product: AMD Ryzen 7 1700X Eight-Core Processor
       vendor: Advanced Micro Devices [AMD]
       physical id: 14
       bus info: cpu@0
       version: AMD Ryzen 7 1700X Eight-Core Processor
       serial: Unknown
       slot: AM4
       size: 1861MHz
       capacity: 3900MHz
       width: 64 bits
       clock: 100MHz
`
