### ISSUE TITLE
Monster Girl Island Prologue (943700)

### ISSUE THREAD

**Issue by Slapdax** [ValveSoftware/Proton#2889]
# Compatibility Report
- Name of the game with compatibility issues: Monster Girl Island: Prologue Not starting on Ubuntu
- Steam AppID of the game:943700

## System Information
- GPU: 
- Driver/LLVM version: 2.1 Mesa 19.2.0-devel - padoka PPA

- Kernel version: 4.15.0-54-generic
- Link to full system information report as NULL
- Proton version:4.2-9

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Symptoms 
Wont launch in Proton and gives message seen in the attached image 
https://store.steampowered.com/app/943700/
![Screenshot from 2019-07-14 08-20-36](https://user-images.githubusercontent.com/52926392/61231283-da3cdc80-a6f9-11e9-8fd3-2c660909ce57.png)

**Comment by kisak-valve** [comment]
Hello @Slapdax, your Intel Ironlake (Gen 5) graphics chipset is likely to cause most games to have trouble with Proton due to it only supporting OpenGL 2.1. It is unlikely to work, but you may have luck with setting `PROTON_USE_WINED3D=1 %command%` in the game's launch options or some of the [other env variables](https://github.com/ValveSoftware/Proton#runtime-config-options) that are available to troubleshoot Proton issues.

**Comment by Slapdax** [comment]
Thank you! That fixed it :)
