### ISSUE TITLE
DARK SOULS III (374320), Nier: Automata (524220), Sekiro: Shadows Die Twice (814380) crash with Proton 4.11

### ISSUE THREAD

**Issue by yuiiio** [ValveSoftware/Proton#2929]
# Compatibility Report
- Name of the game with compatibility issues: DARK SOULS III
- Steam AppID of the game: 374320

## System Information
- GPU: gtx1050
- Driver/LLVM version: nvidia-430.40
- Kernel version: 5.0.0-20-mfutex (from ppa:valve-experimental/kernel-bionic)
- Link to full system information report as [Gist](https://gist.github.com/yuiiio/f3b6d726f3f3819d47f59d005beaaa35):
- Proton version: 4.11-2
[steam-374320.log](https://github.com/ValveSoftware/Proton/files/3453378/steam-374320.log)

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
crash when cursor hover and show "graphics" tab in system settings.
no effects PROTON_NO_FSYNC=1.

**Comment by jomarocas** [comment]
for me crashing in proton 4.2 and 3.16 nothing new

**Comment by yuiiio** [comment]
I could play with 4.2-9.

**Comment by solenum** [comment]
Working perfectly fine for me on 4-11, I actually just finished the entire game (DLC included) at max settings.  Got through the entire thing without a single performance hitch or crash, multiplayer works fine as well and I actually did the entire thing in coop.

Should be noted that I'm using the 5.0 kernel but not the valve-experimental one, so no f-sync I suppose(?).

GTX 1070 - Nvidia 430.40.

Also why are there 6 issue threads for Dark Souls 3?  Difficult to keep track of things.

https://github.com/ValveSoftware/Proton/issues/2345
https://github.com/ValveSoftware/Proton/issues/2445
https://github.com/ValveSoftware/Proton/issues/2722
https://github.com/ValveSoftware/Proton/issues/2828
https://github.com/ValveSoftware/Proton/issues/2537

**Comment by yuiiio** [comment]
Sorry. and thank you your notification.

more description.
I play 1080p game resolution with 4k display. and optimus laptop.
Crash reproducibility is 100% for me. (with without fsync)

**Comment by yuiiio** [comment]
I fond new fact.
proton 4.11 with window mode have not crash.
proton 4.11 with fullscreenmode (in game settings) have crash.
proton 4.2 with fullscreenmode (in game settings) have not crash.

**Comment by yuiiio** [comment]
![Screenshot from 2019-09-09 19-33-49](https://user-images.githubusercontent.com/36093713/64524889-8be33d00-d33a-11e9-8ae7-99d4a31f2881.png)

**Comment by yuiiio** [comment]
@aeikum I have reverts commit this and fix this problem.
https://github.com/ValveSoftware/wine/commit/6bf75252006ffd5761430da1cf8a7414d17105b7
https://github.com/ValveSoftware/wine/commit/7185e4004f99aa65c4c9c00865eca600067c5985
https://github.com/ValveSoftware/wine/commit/2d034d48e25403105539ba219cad6ba2df56181b
https://github.com/ValveSoftware/wine/commit/4c9b5d6b9e668459699caaa8c56dce021277994c
https://github.com/ValveSoftware/wine/commit/f8a795dd545ab1446dc370e7024ec5eac50aec55
https://github.com/ValveSoftware/wine/commit/b897b017d28457bdb8a1d75b25f8758234978608

**Comment by aeikum** [comment]
@yuiiio Thanks for looking into this. Can you attach a log here of regular 4.11-3, and add `+x11settings,+x11drv,+win,+event,+xrandr` to the `WINEDEBUG` log channels?

**Comment by yuiiio** [comment]
Thanks !
[steam-374320.log](https://github.com/ValveSoftware/Proton/files/3596219/steam-374320.log)(with dxvk-git)
**update**
[steam-374320.log](https://github.com/ValveSoftware/Proton/files/3597020/steam-374320.log)(regular 4.11-3 no effect)

**Comment by ghost** [comment]
I experience crashes too since 4.11.5. It worked fine with early 4.11.x versions(like 4.11.3). It runs really badly for me: https://github.com/doitsujin/dxvk/issues/1181

**Comment by yuiiio** [comment]
looks not same problem.
try PROTON_NO_FSYNC=1.
since proton 4.11-5 has fsync problem for me.

**Comment by ghost** [comment]
It doesn't work for me on proton-4.11.6 at all. PROTON_NO_FSYNC=1 doesn't do anything.

**Comment by yuiiio** [comment]
my xrandr output
```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
HDMI-0 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
eDP-1-1 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   3840x2160     60.00*+  59.98    59.97
   3200x1800     59.96    59.94
   2880x1620     59.96    59.97
   2560x1600     59.99    59.97
   2560x1440     59.99    59.99    59.96    59.95
   2048x1536     60.00
   1920x1440     60.00
   1856x1392     60.01
   1792x1344     60.01
   2048x1152     59.99    59.98    59.90    59.91
   1920x1200     59.88    59.95
   1920x1080     60.01    59.97    59.96    59.93
   1600x1200     60.00
   1680x1050     59.95    59.88
   1600x1024     60.17
   1400x1050     59.98
   1600x900      59.99    59.94    59.95    59.82
   1280x1024     60.02
   1440x900      59.89
   1400x900      59.96    59.88
   1280x960      60.00
   1440x810      60.00    59.97
   1368x768      59.88    59.85
   1360x768      59.80    59.96
   1280x800      59.99    59.97    59.81    59.91
   1152x864      60.00
   1280x720      60.00    59.99    59.86    59.74
   1024x768      60.04    60.00
   960x720       60.00
   928x696       60.05
   896x672       60.01
   1024x576      59.95    59.96    59.90    59.82
   960x600       59.93    60.00
   960x540       59.96    59.99    59.63    59.82
   800x600       60.00    60.32    56.25
   840x525       60.01    59.88
   864x486       59.92    59.57
   800x512       60.17
   700x525       59.98
   800x450       59.95    59.82
   640x512       60.02
   720x450       59.89
   700x450       59.96    59.88
   640x480       60.00    59.94
   720x405       59.51    58.99
   684x384       59.88    59.85
   680x384       59.80    59.96
   640x400       59.88    59.98
   576x432       60.06
   640x360       59.86    59.83    59.84    59.32
   512x384       60.00
   512x288       60.00    59.92
   480x270       59.63    59.82
   400x300       60.32    56.34
   432x243       59.92    59.57
   320x240       60.05
   360x202       59.51    59.13
   320x180       59.84    59.32
DP-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-2 disconnected (normal left inverted right x axis y axis)
HDMI-1-2 disconnected (normal left inverted right x axis y axis)
```

**Comment by yuiiio** [comment]
Interesting!
Sekiro has looks same issue.

**Comment by yuiiio** [comment]
This affect me still Proton 4.11-9.
Sekiro
[steam-814380.log](https://github.com/ValveSoftware/Proton/files/3943080/steam-814380.log)
Nier Automata
[steam-524220.log](https://github.com/ValveSoftware/Proton/files/3943084/steam-524220.log)
Dark souls 3
[steam-374320.log](https://github.com/ValveSoftware/Proton/files/3943085/steam-374320.log)

**Comment by yuiiio** [comment]
xrandr --listprovides
```
Providers: number : 2
Provider 0: id: 0x253 cap: 0x1, Source Output crtcs: 4 outputs: 2 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x47 cap: 0x6, Sink Output, Source Offload crtcs: 3 outputs: 5 associated providers: 1 name:modesetting
```

**Comment by sonic2kk** [comment]
NieR:Automata is crashing for me in Proton 4.11-10 when I try try to leave the settings screen or load any of my saves. They are not corrupted as they open just fine with Proton 3.7-8, 3.16-9 and 4.2-9. I didn't get it in 4.11-9 and below, but starting with 4.11-10 the game crashes with similar error to @yuiiio's log file. I have attached my own NieR:Automata Proton crash log. Here, I ran the game with 4.21-GE-2, but the same thing happens in Proton 4.11-10. I've tried moving the game across drives and I still get the error - even on my main boot drive. If I switch to Proton 4.2-9 (the lowest version I can use at the moment, as I reinstalled) then the game works fine.

The log details an interesting error to do with a page fault: `wine: Unhandled page fault on read access to 0000032000000520 at address 00000001405C1282 (thread 006c), starting debugger...`. The interesting bit is that it says it's an unhandled _WINE_ exception, which makes me wonder. Since it worked in previous versions of Proton 4.11 - which, to my knowledge, is _always_ based on WINE 4.11 - then why is this unhandled exception suddenly becoming a problem now? I changed my hardware from an i5-6500/RX480 GB to my current specs below, but I didn't change my drives. I've updated my motherboard BIOS, too, which fixed some general issues with my system but did not impact the games I play. 

I tried deleting the shader cache folder, deleting the game's Proton prefix, and even reinstalling the game. No success, unsurprisingly as this seems to be an issue with the newer versions of Proton. Hopefully someone can come along and check the logs and give us an idea of what's wrong! ^_^

OS: Arch Linux w/ KDE Plasma
CPU: Ryzen 7 3700X
GPU: AMD RX 5700-XT 8GB
RAM: 16GB
Drivers: Mesa 19.3.1 with ACO enabled

Log: [steam-524220.log](https://github.com/ValveSoftware/Proton/files/3981616/steam-524220.log)

**Comment by sonic2kk** [comment]
Can confirm the crash still occurs with Proton 4.11-11

**Comment by alasky17** [comment]
@sonic2kk Have you tried disabling ACO?  I'm just curious if that would change the behavior at all.

**Comment by sonic2kk** [comment]
@alasky17 I have, it made no difference sadly. I've tried different versions of Proton, and the latest known working version for me was 4.11-8. Proton 4.11-9 may have worked but I don't recall. I know that Proton 4.11-10 and up don't work. A patch must have been added somewhere in the Proton versions that broke it. Versions starting with Proton 3.7-8 (the default version Valve recommends for NieR:Automata) up to Proton 4.11-8 all work with and without ACO, as I've tested on every release starting from then. The late 3.16-9, released while 4.2 was in circulation I believe, also works with and without ACO.

I tested [Proton-tkg 5](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/proton-tkg) as well (which I believe is based on WINE-Staging by default and I assume the "5" means WINE 5.0), and while it gives different results it ultimately gives the same vein of error. It softlocks the game again when trying to leave the settings menu and when trying to load a save/create a new save. However, the game's music still plays. The error I got when testing with Proton-tkg 5 was pretty much the same as with Proton 4.11-10, 4.11-11 and Proton-4.21-GE-2: `wine: Unhandled page fault on write access to 0000040000000558 at address 000000014069D59F (thread 0066), starting debugger...`

If needed, I can provide additional logs.

I should also mention that I've never ran into this error before with any other games in my library. I've tested around 150 games with Proton across my old and new PC hardware, with only 2 not working due to codec issues and 1 not working because of anti-cheat. The rest all worked fine, and did not produce this error. Suffice to say that for me only NieR:Automata is having this fault issue.

**Comment by alasky17** [comment]
@sonic2kk Thank you for trying that and for the details!  I will keep thinking about this.

**Comment by ghost** [comment]
Dark souls 3 is also crashing for me a lot: [dump](https://pastebin.com/nxYcn9KP).

**Comment by ghost** [comment]
And I also experienced another kind of crash: #3358

**Comment by yuiiio** [comment]
You can revert commits to know if it is the same or another problem.

**Comment by sonic2kk** [comment]
Crash is still present with all of the same symptoms in Proton 4.11-12. The updated DXVK has made no difference

**Comment by sonic2kk** [comment]
The same crash is also still present with Proton 5.0-1. All the symptoms are the exact same, ~~including the "unhandled exception" line~~ except the "unhandled exception" line now says:

- `wine: Unhandled page fault on write access to 0000040000000558 at address 000000014069D59F (thread 0077), starting debugger...` (Proton 5.0-1 log, line 526)
- `Unhandled exception: page fault on write access to 0x40000000558 in 64-bit code (0x000000014069d59f)` (Proton 5.0-1 log, line 603)

I compared two different log files from Proton 4.2-9 and Proton 5.0-1, and the only notable difference I could find was that Proton 5.0-1 was loading the PE overrides that were added in Proton 4.11 - However, I have definitely ran NieR:Automata with Proton 4.11, at least up to Proton 4.11-8. I've tested a number of other game since I initially commented on this issue and haven't ran into this problem with any other games. I have since acquired DARK SOULS III which is reportedly causing issue but have not gotten around to installing or testing it.

I'll attach both log files for Proton 5.0-1 and Proton 4.2-9. I have not tried going back to versions <= Proton 4.11-8, the latest version I have that I can confirm works is Proton 4.2-9. The only other time I've read someone having a similar issue was someone having issues with "Yakuza Kiwami (834530)" in the ProtonDB server. This was never resolved and was talked about almost a year ago.

I did some investigating and found [this issue](https://bugzilla.redhat.com/show_bug.cgi?id=433641) on the RedHat issue tracker from 2008. Someone suggested it was an issue with map addresses. I didn't make the file in `/etc/sysctl.conf` as it didn't exist for me and I didn't want to go creating system files willy-nilly. However I did try editing the `/proc/sys/vm/mmap_min_addr` file and setting it to `0`, this already existed for me. It didn't work either, and when I rebooted it was reset back to the original value of `65536`.

- [Proton 4.2-9 Log File](https://github.com/ValveSoftware/Proton/files/4174633/Proton.4.2-9.steam-524220.log)
- [Proton 5.0-1 Log File](https://github.com/ValveSoftware/Proton/files/4174640/Proton.5.0-1.steam-524220.log)

OS: Arch Linux w/ KDE Plasma
CPU: Ryzen 7 3700X
GPU: AMD RX 5700-XT 8GB
RAM: 16GB
Drivers: Mesa 19.3.3 with ACO enabled

**Comment by sonic2kk** [comment]
As expected, NieR:Automata still crashes with Proton 5.0-2 with all of the same symptoms. I'm also currently running on Mesa 19.3.4. I also tested GloriousEggroll's Proton-GE-5.1 release, with no luck. Again, crashes in the same way.

Proton 4.2-9 still works, but it is perplexing that only a handful of people are reporting this issue.

**Comment by yuiiio** [comment]
```
6915.843:0034:0072:trace:seh:raise_exception code=c0000005 flags=0 addr=0x1405c1282 ip=1405c1282 tid=0072
6915.843:0034:0072:trace:seh:raise_exception  info[0]=0000000000000000
6915.843:0034:0072:trace:seh:raise_exception  info[1]=00000384000005c0
6915.843:0034:0072:trace:seh:raise_exception  rax=00000001418f8b50 rbx=00000384000005a0 rcx=0000000141106340 rdx=0000000140000000
6915.843:0034:0072:trace:seh:raise_exception  rsi=00000000156cc958 rdi=0000000000000000 rbp=0000000038beffd0 rsp=0000000038befc30
6915.843:0034:0072:trace:seh:raise_exception   r8=00000001418b6d7c  r9=0000000141911a40 r10=0000000000000000 r11=0000000000000002
6915.843:0034:0072:trace:seh:raise_exception  r12=0000000000000000 r13=0000000000000000 r14=0000000000000000 r15=0000000000000000
6915.843:0034:0072:trace:seh:call_vectored_handlers calling handler at 0x69060aa0 code=c0000005 flags=0
6915.843:0034:0072:trace:seh:call_vectored_handlers handler at 0x69060aa0 returned 0
6915.843:0034:0072:trace:seh:call_vectored_handlers calling handler at 0x6a434c70 code=c0000005 flags=0
6915.843:0034:0072:trace:seh:call_vectored_handlers handler at 0x6a434c70 returned 0
6915.843:0034:0072:trace:seh:RtlVirtualUnwind type 1 rip 1405c1282 rsp 38befc30
6915.843:0034:0072:trace:seh:dump_unwind_info **** func 5c1230-5c135c
6915.843:0034:0072:trace:seh:dump_unwind_info unwind info at 0x140f5ecb4 flags 0 prolog 0xa bytes function 0x1405c1230-0x1405c135c
6915.843:0034:0072:trace:seh:dump_unwind_info     0xa: movq %rbx,0x30(%rsp)
6915.843:0034:0072:trace:seh:dump_unwind_info     0xa: subq $0x20,%rsp
6915.843:0034:0072:trace:seh:dump_unwind_info     0x6: pushq %rdi
6915.843:0034:0072:trace:seh:RtlVirtualUnwind type 1 rip 140519e0b rsp 38befc60
```

**Comment by sonic2kk** [comment]
@yuiiio ~~I tried to use a patch file for this to build with Proton-tkg but failed, but here's hoping it gets merged soon and works!~~ Installed with Proton-tkg with Wine 5.4 and it works like a charm!

**Comment by sonic2kk** [comment]
This fix is now a part of TkGlitch's Proton-tkg build, which can be found on their [PKGBUILDS](https://github.com/Tk-Glitch/PKGBUILDS) repo. Building Proton-tkg from source should now allow you to play the three games listed here. If you follow the instructions on the repo you'll have it built in no time. You don't need to add a custom patch for the game to work anymore on that build of Proton!

Looking at the code they added, it's part of a hacks patchset and [explicitly mentions these three games](https://github.com/Tk-Glitch/PKGBUILDS/blob/9be1dee586ec552860f64653dddf9aca7ba74e36/wine-tkg-git/wine-tkg-patches/proton/valve_proton_fullscreen_hack-staging.patch#L6420). I can only personally verify NieR:Automata but I trust that it works.

Maybe someone smarter than me can explain why exactly these games broke with later versions of Proton, and why this fix works. But, that's not too terribly important. What matters is that now these games work!

**Comment by aeikum** [comment]
Hello. Thanks for your patience on this issue. This should be fixed now in the Proton 5.13-1 release.

**Comment by yuiiio** [comment]
thanks!
seems work for me.

**Comment by sonic2kk** [comment]
@aeikum Just tested with the latest 5.13-1 downloaded through Steam. NieR:Automata works for me out of the box with that version. Worth the wait!

**Comment by dagolinuxoid** [comment]
Nier:Automata gives me white screen and frezzes OS, however adding 
```py
    # Use OpenGL-based wined3d instead of Vulkan-based DXVK for d3d11, d3d10, and d3d9.
   "PROTON_USE_WINED3D": "1",

```
into `user_settings.py` file makes it work. 
I wonder how to make it work with **DXVK** ??!
btw I've tried to launch the game via wine 6.8 and it launches but crashes upon choosing `Start Game` option (regardless of OpenGL or DXVK renderer)
ps. proton 6.3-4, nvidia GTX 1050, intel i5, elementary os 5.1
