### ISSUE TITLE
Tom Clancy’s Splinter Cell Blacklist (235600)

### ISSUE THREAD

**Issue by yeah-its-gloria** [ValveSoftware/Proton#3074]
## System Information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver/LLVM version: NVIDIA's proprietary driver version `418.88`
- Kernel version: `5.2.11-1-MANJARO`
- [Link to full system information](https://gist.github.com/Apfel/1d6672a0cf921299663c0f5e7e403762)
- Proton version: `4.11-5`

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
The game shows some information about the used stuff like usual for around 3 seconds (if you don't grab focus of the window, the result is then immediate) and then crashes without any sort of error code whatsoever. Unlike usually, the launcher doesn't correctly exit after launching Uplay, which shows debug output. It doesn't seem to introduce the error though, since on Proton 4.2-9, the log output exits normally but the game crashes just like on 4.11.

The most interesting lines consist of
```
[0920/211218.500:ERROR:network_change_notifier_win.cc(157)] WSALookupServiceBegi
n failed with: 8
```
as well as of
```
ERROR: Could Not Get Primary Adapter Handle
```
the latter one being missing from the log output.

I couldn't test DirectX 10 or 9 since neither are supported by Uplay and the game doesn't take advantage of DirectX 10.

## Reproduction
Just launch the game and make sure you're logged into Uplay, since Uplay can't start the game on itself due to Steam being missing.

**Comment by Guy1524** [comment]
@Apfel users on protondb recommend using wined3d and disabling the U-Play overlay, have you tried these suggestions?

**Comment by yeah-its-gloria** [comment]
Yeah, I tried that but to no success, however, on an earlier version of proton 4.11 (4.11-1 to be exact) on a earlier version of ubuntu 19.04, it worked quite fine, with some glitches and weird issues. I appreciate your help nonetheless.

**Comment by yeah-its-gloria** [comment]
To alleviate the stress of testing a little bit, I've done my fair share of testing again on the same machine, just with another OS that I confirmed worked fine before, that being Ubuntu 19.04.

As mentioned before, nothing hardware-related changed, but the OS was swapped:
```
Operating System Version:
    Ubuntu 19.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.0.0-31-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12004000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20190711.3
```

The issues, however, stayed the same, even for the Proton update released a while ago, `4.11-6`.
However, removing the video files that usually play up front the intro screen showed that the game itself seems to try its best and it even plays the intro music, though crashing a second later.
I've tried reinstalling the prefix and other related stuff so far, like Uplay, I even went as far as to delete some registry keys for the display adapter, without any success.
I'm open for any suggestions in regards to trying to get it to run normally.

**Comment by kisak-valve** [comment]
Proton 5.0-7 regression for Splinter Cell Blacklist

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3822.
@HenrikHolst posted on 2020-05-02T21:19:20:

## Game Info
- Name of the game with issues: Tom Clancy's Splinter Cell: Blacklist
- Steam AppID of the game: 235600

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 19.2.8
- Kernel version: 5.0.0
- Proton version: 5.0-7

With 5.0-7 the game freezes and dies after aprox 5-10minutes of play. 5.0-6 worked perfectly so it must be a regression in 5.0-7 that causes this.

Have attached the proton log from such a crash but unsure if proton created a log for the game that crashed or if it just did it for the launcher (I noticed that the game starts 3 wine-processed [it's a Uplay game]).

[steam-235600.zip](https://github.com/ValveSoftware/Proton/files/4568953/steam-235600.zip)

**Comment by Apfel** [comment]
I tried playing again, and this time, after some trial and error, I got it to work.
With the Vulkan wrapper enabled, Vulkan always failed creating an instance:
```
999.915:00b8:00bc:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
```
Why this error occurs is beyond me, considering that my own small attempts at making something with Vulkan never failed to create an instance.

With OpenGL, the game ran obscenely slow. In Full-Screen, tabbing out of the game breaks any control by the mouse, though playing in borderless mode fixed this issue permanently.
I played the Safehouse mission for about half an hour, without any crashes, though, as mentioned before, it was painful to play with such low framerates.

Setup:
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver: NVIDIA, proprietary, 440.82
- Kernel: `5.6.15-zen2-1-zen` (On Arch Linux)
- Proton Version: 5.0-7

A Gist containing more details can be found **[here](https://gist.github.com/Apfel/d80725384882ac1cf9251509aed4a488)**.

I attached 3 logs **[here](https://github.com/ValveSoftware/Proton/files/4708513/Logs.zip)** - one with Vulkan enabled, one with the Uplay Overlay enabled and one with the Uplay Overlay disabled. I may mention that I played the longest with the Overlay disabled, as the Overlay didn't work at all.

**Comment by yeah-its-gloria** [comment]
I've tried dxvk and that doesn't work either - installing `d3d9.dll` and `d3d11.dll` into the directory containing `Blacklist_DX11_game.exe` throws the following text into the little terminal:
```
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: Blacklist_DX11_game.exe
info:  DXVK: v1.7
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to initialize OpenVR
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
terminate called after throwing an instance of 'dxvk::DxvkError'
```
Why this is the case is beyond me.

**Comment by rbernon** [comment]
I've found and fixed a wined3d crash with the overlay, which was the initial issue reported here. It should be available in latest RC (see #3932).

However I still experienced other UPlay related crashes, after exactly 25minutes, as also reported by users on ProtonDB. I have reasons to believe these are DRM related and intentionally caused by UPlay after not being able to validate the Steam serial key, or because Wine is still not able to pass its DRM checks somehow. They happen regardless of whether the overlay is used or not.

**Comment by HenrikHolst** [comment]
> I've found and fixed a wined3d crash with the overlay, which was the initial issue reported here. It should be available in latest RC (see #3932).
> 
> However I still experienced other UPlay related crashes, after exactly 25minutes, as also reported by users on ProtonDB. I have reasons to believe these are DRM related and intentionally caused by UPlay after not being able to validate the Steam serial key, or because Wine is still not able to pass its DRM checks somehow. They happen regardless of whether the overlay is used or not.

Well it has to be mentioned that the crash after 25minutes when UPLay is active and in online mode is something that happens for Windows users as well. Apparently the key that one is given from Steam is not correct and one have to contact Ubisoft support to request a proper key. There are more info in a steam post that I'm for some reason unable to quickly find right now, where the poster had collected a number of Ubisoft support tickets covering the exact same problem and fix.

In any case, to run the game in total offline mode to avoid this constant 30minute crash then just set the launch option to: "%command% -offline -offline_mode".

However as mentioned in a post above, with 5.0-7 I experienced a regression in Blacklist where the game now quits after roughly 5 minutes even when in total offline mode.

**Comment by rbernon** [comment]
Thanks for the information I didn't now that. The latest RC includes a fix for the overlay crash with wined3d, which usually happened after ~15minutes, and only if the overlay is active. I didn't see any other crashes than these two during my debugging session.

**Comment by HenrikHolst** [comment]
Found a post on the Ubisoft forums describing the 20-30 minutes crash on Windows and that it requires a new key: [https://forums.ubisoft.com/showthread.php/820751-Splinter-Cell-Blacklist-Crashes-after-23-or-24-minutes-gameplay?p=11932818&viewfull=1#post11932818](https://forums.ubisoft.com/showthread.php/820751-Splinter-Cell-Blacklist-Crashes-after-23-or-24-minutes-gameplay?p=11932818&viewfull=1#post11932818)

So that one is most likely not wine-related.

**Comment by Apfel** [comment]
I've tested the game with the `5.0-8` Proton update, and the issues with Vulkan weren't resolved, dxvk still fails to create an instance.

But whatever, I played with Wine's ~~terrible~~ OpenGL layer, and this time, I had logs enabled.
I got the crash captured in this [log file](https://github.com/ValveSoftware/Proton/files/4739372/steam-235600.zip) - from what I can tell, it searches for a symbol that doesn't exist. Whatever the symbol might be or do.

I'm somewhat certain this doesn't have anything to do with the game key, but I'll need more `evidence` to prove that.

**Comment by HenrikHolst** [comment]
Tested 5.0-8 and my previous regression in where the game crashed after aprox 5 minutes is gone. Either the regression got fixed, the regression was just a random fluke on my system or the fix was done in uplay (uplay updated at the same time that I tested 5.0-8). In any case for me now the game works for hours on end again as long as it's in offline mode.

edit: went back in and noticed that I for some reason had the overlay enabled so perhaps that was why 5.0-7 crashed for me, don't remember if I enabled that just to see if that would make any change or not since that should have crashed it in the previous 5.0 versions anyway...

**Comment by Apfel** [comment]
Tested again, this time with the new update (`5.0-9`).
None of the issues were resolved, but I've noticed that nothing related to Online gameplay works.
I've noticed that setting `WINEDEBUG` to `-all` gives a slight performance boost with OpenGL, and dxvk still continues to refuse to work for me.

**Comment by Apfel** [comment]
Tested yet again with Proton `5.1-13`, this time, with sorta good news.
DXVK actually... worked. Well, sort of; lighting/shadows/whatever-it-might-be made it look very weird.

### Screenshots
This time I've taken some screenshots - these ones were taken while the game was running with dxvk.

This screenshot shows the first area in the Benghazi level - as you can see, the thing-for-which-I-lack-a-good-name makes it look bad; from what I can tell, it zooms into areas close by itself.
![DXVK-1](https://user-images.githubusercontent.com/32610623/106963847-7a75ae80-6741-11eb-8c64-0e7c17846825.png)
Another one just that I turned around.
![DXVK-2](https://user-images.githubusercontent.com/32610623/106963923-9b3e0400-6741-11eb-91f6-fe0c826e14ed.png)
Now, this is odd - it doesn't seem to affect rooms that you haven't walked into, assuming you can open and close the door by yourself. I didn't take a screenshot of how it looks once you enter it, but it looks exactly the same as the previous two, so uuh, go figure.
![DXVK-3](https://user-images.githubusercontent.com/32610623/106963962-aa24b680-6741-11eb-8bf1-859d1c116047.png)
Even though the weird shading issues affects models, it doesn't affect their cool in-world text rendering thing, which is, you know, odd, since it's (very probably) just a texture on a plane without collision.
![DXVK-4](https://user-images.githubusercontent.com/32610623/106963994-b6a90f00-6741-11eb-815c-ce201322f8e2.png)

The following screenshots were taken while the game was running in WineD3D.

Not only did WineD3D send any hopes for good performance into the 15th dimension, it made models look weird at a distance in darker areas (look close at the two dudes across the room), but at least the shading issue is now, uuh, well, replaced with another.
![WineD3D-1](https://user-images.githubusercontent.com/32610623/106964435-62eaf580-6742-11eb-859d-8779f393c0fb.png)
Getting closer to other models makes the issue go away.
![WineD3D-2](https://user-images.githubusercontent.com/32610623/106964462-6da58a80-6742-11eb-817e-4102f5c19fce.png)  

That sums up my screenshots.

### Settings and other junk
These were my default Proton settings:
```py
user_settings = {
    "WINEDEBUG": "+timestamp,+pid,+tid,+seh,+debugstr,+loaddll,+mscoree",
    "DXVK_LOG_LEVEL": "info",
    "VKD3D_DEBUG": "warn",
# ...
}
```

...and my DXVK-less settings (apologies DXVK):
```py
user_settings = {
    "WINEDEBUG": "+timestamp,+pid,+tid,+seh,+debugstr,+loaddll,+mscoree",
# ...
    "PROTON_USE_WINED3D": "1",
# ...
}
```

...and my (In-Game) Graphics settings:
```
Texture Detail              - Ultra
Shadow Quality              - Ultra
Parallax                    - On
Tessellation                - On
Texture Filtering           - Anisotropic 16x
V-Sync                      - Off
Dynamic Abient Occlussion   - Field AO + HBAO+
Anti-Aliasing               - MSAA 4x
DirectX                     - DX11
```

Here's my updated [system info](https://github.com/ValveSoftware/Proton/files/5928949/System.Info.txt).
Here's a GZip-compressed version of Proton's [log](https://github.com/ValveSoftware/Proton/files/5928954/DXVK.log.gz).
This [one](https://github.com/ValveSoftware/Proton/files/5928956/WineD3D.log.gz) is the compressed version of the log Proton made while I was using WineD3D.

Now, this could very much boil down to just being an issue with DXVK and/or WineD3D, but my expertise is limited on that field, and having a ton of issues on different repositories just sounds counterproductive. Oh well.

**Comment by thaewrapt** [comment]
Unredeemable (as it cannot be linked to an Ubisoft account automatically on a game's first ever start) under Proton 5.0-10, 5.13-6 and Experimental-5.13-20210217 at least, after Ubisoft's transition from UPlay Launcher to Ubisoft Connect Launcher. Symptoms are as following.

On the first start of the downloaded game, UPlay Launcher (packaged with a game) starts and tries to update itself, resulting in it being substituted with a newer Ubisoft Connect one. It will fail in the end with an error about `libcef` (the same happens on Windows, so that's not a Proton/Wine issue).

On the second try, the Ubisoft Connect Launcher starts normally, asks for login credentials (as opposed to Windows, where it would know about linked Ubisoft and Steam accounts and logs you in automatically). After that, it will ask to enter an activation key manually (as opposed to Windows, where it will ask if it's ok to redeem the game on the specific Ubisoft account, the same which is linked to your Steam one, and will add an activation key to your Steam account and run the game, upon completion), which wouldn't be helpful as there is no activation key provided with a purchase of the game (thanks to Steam Support on clarifying this, btw), it's being added only upon your actual activation on Ubisoft Connect Launcher.

Some other symptoms (happen with or without activation of the game): 
- Ubisoft Connect Launcher runs in the terminal (Windows `cmd` one, if I'm not mistaken),
- Ubisoft Connect Launcher ignores "remember me" checkbox and forgets your credentials on every run.

Sadly, I don't have Proton logs for the "activation fail" process as I tried and successfully activated the game using Windows VM using Windows-native Steam client. Thus, this is a current workaround for an issue.

**Comment by Haxk20** [comment]
I had the same issue. I could not redeem the game. contacted uplay support but after 3 hours of trying to make it work i had to activate it on freaking Windows VM and even after that the game crashes right after the beggining text.

The one thing i see in logs is: ERROR: Could Not Get Primary Adapter Handle which strikes me as not very great.

**Comment by apoorv569** [comment]
I had this problem too, and I could not find a fix for it, until today when I tried to play with the `video` settings. It looks like anything above `SSAA 2x2 ROTATED GRID` for `Anti-Aliasing` causes this issue. I'm not sure how/why this happens, but it is what fixed it for me and I hope this might help some people here as well.

EDIT: Now I'm noticing a crash that occurs randomly, after 10-15 mins in the game. Also every time I launch the game from steam Uplay does not remember my last login, I have to login every time again to connect to it,

**Comment by Haxk20** [comment]
> I had this problem too, and I could not find a fix for it, until today when I tried to play with the `video` settings. It looks like anything above `SSAA 2x2 ROTATED GRID` for `Anti-Aliasing` causes this issue. I'm not sure how/why this happens, but it is what fixed it for me and I hope this might help some people here as well.
> 
> EDIT: Now I'm noticing a crash that occurs randomly, after 10-15 mins in the game. Also every time I launch the game from steam Uplay does not remember my last login, I have to login every time again to connect to it,

Could you please send here your config for the game ? Whatever i try it still crashes shortly after opening it.

**Comment by Haxk20** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3074#issuecomment-636533524

Could you explain what exactly did you do to make it work ? I tried everything mentioned here. Deleted all the videos that play on the start and for some reason i still cant launch it. But when deleting the videos i seem to get to what could be main menu loading and sound. After that it crashes again.

**Comment by yeah-its-gloria** [comment]
> Replying to [#3074 (comment)](https://github.com/ValveSoftware/Proton/issues/3074#issuecomment-810472753)

I remember just turning off dxvk, and that was it, but as you might be able to tell, I outlined more stuff in a more recent [comment](https://github.com/ValveSoftware/Proton/issues/3074#issuecomment-773653715) when I tried Blacklist on a newer version of Proton.
I redeemed the game on a Windows machine when I bought it, so I couldn't test that.
The `ERROR: Could Not Get Primary Adapter Handle` message seems to just "exist" and not actually have anything to do with the game's functionality in Proton, iirc it prints that regardless of whether it actually runs or not.

**Comment by Haxk20** [comment]
> > Replying to [#3074 (comment)](https://github.com/ValveSoftware/Proton/issues/3074#issuecomment-810472753)
> 
> I remember just turning off dxvk, and that was it, but as you might be able to tell, I outlined more stuff in a more recent [comment](https://github.com/ValveSoftware/Proton/issues/3074#issuecomment-773653715) when I tried Blacklist on a newer version of Proton.
> I redeemed the game on a Windows machine when I bought it, so I couldn't test that.
> The `ERROR: Could Not Get Primary Adapter Handle` message seems to just "exist" and not actually have anything to do with the game's functionality in Proton, iirc it prints that regardless of whether it actually runs or not.

Rather interesting as i did the same. Use windows VM to redeem the game. The game launches and without the videos at start it shows 2 seconds of main menu animation and crashes right after that.

Ofc i disabled esync and dxvk as some people said it works when disabling it. It basically changes nothing for me. The game still crashes few seconds after start.

**Comment by springwurm** [comment]
Hello

If you still suffer from this 20-30min Crash, try this: https://www.pcgamingwiki.com/wiki/Tom_Clancy%27s_Splinter_Cell:_Blacklist#Game_crashes_without_message_after_20-30min

If the game doesn't start, force DX9 (PROTON_NO_D3D11=1), or `protontricks 235600 d3dcompiler_42` for DX11.

## System Information
- GPU: AMD Radeon RX 580
- Driver/LLVM version: Mesa 21.1.5
- Kernel version: 5.13.6
- Link to full system information report as [Gist](https://gist.github.com/springwurm/10b9ae03c39ad871ce714f01ea4bc384):
- Proton version: 6.3-5

## Additional Symptoms
- Extra Console Output Window.
![steam-235600_console_window](https://user-images.githubusercontent.com/65482005/127808862-89ab5eeb-9d7c-42fd-87d8-2a6b216ecd78.png)
- With Tessellation ON, parts of the npc/player models are missing.
  - https://mega.nz/file/zV9xTS5R#KiL9htLjC2zr0-5RZ-NF6cicc04hlM2OFzLZG8K70WM
  - https://mega.nz/file/PI9nQSYB#nrg95ChtNqUIoe2CYsUrdF74KuLS9ExbKpyX8Pxzn7w
- The Game doesn't close probably after clicking the 'Quit to Desktop' Button. I need to click Stop in the Steam Client.

## Reproduction
- Click Play. (You may have to perform the workarounds first).

## Logs:
- [steam-235600_dx9.log.zip](https://github.com/ValveSoftware/Proton/files/6914558/steam-235600_dx9.log.zip)
- [steam-235600_dx11_with_tessellation.log.zip](https://github.com/ValveSoftware/Proton/files/6914550/steam-235600_dx11_with_tessellation.log.zip)
- [steam-235600_dx11_without_tessellation.log.zip](https://github.com/ValveSoftware/Proton/files/6914551/steam-235600_dx11_without_tessellation.log.zip)

## Screenshot
- Tessellation OFF:
![steam-235600_dx11_without_tessellation](https://user-images.githubusercontent.com/65482005/127809667-b771ce93-bfe7-4b64-b446-97470fbc2e31.png)

**Comment by springwurm** [comment]
Found out. On Windows 10, DX11 Mode starts only with the DXVK´s dxgi.dll.

## Logs Windows 10:
[Blacklist_DX11_windows_10_game_d3d11_with_dxgi.dll.log](https://github.com/ValveSoftware/Proton/files/6915249/Blacklist_DX11_windows_10_game_d3d11_with_dxgi.dll.log)
[Blacklist_DX11_windows_10_game_d3d11_without_dxgi.dll.log](https://github.com/ValveSoftware/Proton/files/6915250/Blacklist_DX11_windows_10_game_d3d11_without_dxgi.dll.log)
[Blacklist_DX11_windows_10_game_dxgi.log](https://github.com/ValveSoftware/Proton/files/6915251/Blacklist_DX11_windows_10_game_dxgi.log)

**Comment by yeah-its-gloria** [comment]
Been a while since anything has been said here, I played the game on a Deck with Proton 8.whatevs and it works just fine. Online is borked on Windows too anyway so no worth talking about that, but the game works just fine
