### ISSUE TITLE
The cursor does not work in games using Proton on Steam OS

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#3142]
# Compatibility Report
- Name of the game with compatibility issues: All games using Proton

## System Information
- GPU:  NVIDIA GeForce GTX 1060
- Driver/LLVM version:  4.6.0 NVIDIA 415.27
- Proton version: 4.11-7

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

## Symptoms 
The cursor does not work in games on Steam OS. The cursor becomes inactive or disappears after the first click in games running through Proton. It is not possible to play games using the keyboard and mouse. This error is only seen on Steam OS.

**Comment by kisak-valve** [comment]
Hello @vladislavyuzbekov, please stop trying to get additional attention through silly manipulation of the issue tracker. If you have something to add to the issue report, add a comment instead of repeatedly opening new issue reports. This is abuse of the issue trackers and you're going to force me to take action to stop you.

This is the fifth issue report for the exact same issue. Closing in favor of #2849.
