### ISSUE TITLE
Thief 2 (211740)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3253]
# Compatibility Report
- Name of the game with compatibility issues: Thief Gold
- Steam AppID of the game: https://steamdb.info/app/211740/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.36
- Kernel version: 5.3.13
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-8

## Symptoms
Game has only low resolutions and bit depth, cursor flickers, and compatibility issues because of its age and vanilla engine limitations.

Installing T2Fix 1.27 fixes the issue for me (https://www.ttlg.com/forums/showthread.php?t=149669). Using 60Hz and VSync and/or framerate limiter to 60fps is necessary for proper movement speeds and game timing. Enabled ```PROTON_USE_D9VK=1``` for Vulkan D3D9 wrapper.

**Comment by kisak-valve** [comment]
Hello @shoober420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/804#issuecomment-557947747.

As a side note, searching this issue tracker by appid should reliably find existing compatibility reports, that's why we have them in the title.
