### ISSUE TITLE
Tekken 7 (389730) triggers Denuvo 5 install per day limit

### ISSUE THREAD

**Issue by Saladin1812** [ValveSoftware/Proton#3267]
I tested Tekken 7 on multiple proton versions to see which proton version has the best performance and Capcom developers of tekken think that I installed the game on more than 5 systems which is not true. I was just testing different versions of proton and now i cant open tekken 7 it just gives me link that it wont revalidate my account. :(

**Comment by kisak-valve** [comment]
Hello @jatin-cbs, please retest after 24 hours (from https://www.reddit.com/r/Tekken/comments/8w3qhw/does_tekken_7_on_steam_have_an_activation_limit/e1t9cz6/).

**Comment by Saladin1812** [comment]
We cant open tekken 5 more than 5 times in a day because it thinks we installed it on 5 different PC's :( 
It doesnt matter we change proton versions or not. Today I didnt change my proton version but i was able to open game 5 times but not more than that it then again displays the message and we have to wait 24 hours. @kisak-valve

**Comment by Saancreed** [comment]
I'm running into the same daily activation limit with Monster Hunter World, which effectively limits me to launching the game 5 times per day (or perhaps less, because it frequently freezes for me on Capcom splash screen).

According to [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Denuvo#Offline_token_locations) Denuvo is supposed to store the token it received from activation server in `$steam_root/userdata/$steam_user_id/582010/$some_number` and indeed, on my Windows machine there are multiple token files in that location, but on my two Linux machines there are no token files in there.

Either Denuvo fails to store these tokens when a game is launched with Proton or they are for some reason invalidated between each launch and Denuvo simply deletes them every time.

**Comment by Saladin1812** [comment]
Can you search inside the $steam_root/userdata/$steam_user_id/582010/   that the file is present or not while you are in the game that would help us figure out that the file is even getting created or not. @Saancreed

**Comment by Saancreed** [comment]
@jatin-cbs I'm pretty sure those files are never created, I just checked it with a file system watcher. Well, that's assuming I can trust `FileSystemWatcher` in .NET Core 3.1, which afaik uses `inotify` on Linux.

**Comment by Saladin1812** [comment]
@Saancreed also what i think is happening is when we launch it does create the token file otherwise i wont even let us in the game but it immediately gets deleted because of some reason.. Maybe it is present for the short duration when that heihachi poster comes maybe just for a second.

**Comment by Myrddin-Wyllt** [comment]
Be glad Capcom has begun removing Denuvo then; Resident Evil 2 was the first game I'm aware of where it's been removed. Devil May Cry 5 is another which Capcom is supposedly removing the performance-killing DRM that the marketing team though was such a great idea (anyone remember why EA's Spore became the most pirated game?)... No sane technical team would've supported Denuvo online DRM for offline games. My advise would be to unleash hell on Capcom's discussion area, support emails/tickets, etc. That's how prior games have succeeded in striking back at Denuvo. The main argument against is obvious for those in the know. Pirated versions of Capcom games removed/disabled Denuvo & due to this, performance for every Capcom game using Denuvo is better when pirated.

**Disclaimer:** In no way am I advocating piracy; Capcom's done a good enough job of that already.

**Comment by Saancreed** [comment]
> what i think is happening is when we launch it does create the token file otherwise i wont even let us in the game but it immediately gets deleted because of some reason

You are right, I went ahead and `strace`d the game, it actually creates and stores those tokens, but in another location; I found one in `$steam_root/steamapps/compatdata/582010/pfx/dosdevices/c:/users/steamuser/Local Settings/Application Data/Steam/userdata/$steam_user_id/582010/169439589` (5154 bytes long text file).

However, when I blocked access to `srv0{1,2,3}.codefusion.technology` and then launched the game, it actually deleted this file after short inspection (by calling on it `openat`, `lstat`, `openat`, `lstat`, `lstat`, `unlink`) and asked me to retrieve token from the support website (which I cannot do anyway, because the dialog crashes before I can copy request data). That would reinforce the idea that tokens are indeed invalidated between each launch.

@kisak-valve Can we change this issue's title to a more generic one as the issue is not specific to just Tekken 7? Or should we move this discussion to another issue?

**Comment by kisak-valve** [comment]
Hello @Saancreed, the title looks fine as it is for now and you can continue discussing the overlap with unofficially supported game titles.

If/when someone finds a fix for the issue, we'll want to transition this issue report to be a whitelist update request instead of closing it immediately.

**Comment by Saancreed** [comment]
Okay, so I was tinkering around my MHW Wine prefix and somehow caused it to break, which forced me to nuke it completely and then have Proton recreate it from scratch. Afterwards I launched MHW which saved a new token there and that token _stays valid_. So whatever was causing the token to be invalidated each time was probably related to changes/leftovers from some custom Proton version I was testing a while ago. With a new prefix created by Proton 4.11-11 Denuvo no longer causes any issues to me. Or so it seems.

@jatin-cbs Could you try the same (nuke prefix, use only Proton 4.11-11) with Tekken?

**Comment by Saladin1812** [comment]
@Saancreed ok will try changing the proton version to 4.11-11

**Comment by Saladin1812** [comment]
@Saancreed What do you mean by nuke the prefix ? I just gota change the wine version or do something else too. dont get the "nuke" here sorry..

**Comment by Saancreed** [comment]
@jatin-cbs Delete the `$steam_root/steamapps/compatdata/389730` directory. Note that depending on the game it could wipe your settings and/or saves, so you might want to enable Cloud Sync beforehand or at least make a backup.

**Comment by Saladin1812** [comment]
@Saancreed  ok first i will try just changing the wine version from glorious eggroll to 4.11-11 and if didnt work I will delete compat data and try

**Comment by Saladin1812** [comment]
@Saancreed I am closing this i changed my proton to 4.11-11 and it works just a request to @kisak-valve to make this default version for tekken 7 instead of 3.16 as its one of the supported titles.

**Comment by EvgenijM86** [comment]
Any way around this issue? I need to test game mods with different versions of proton, patch the mod and then try again, until it works with at least some version of proton. This severely limits game modding.

**Comment by Saladin1812** [comment]
@EvgenijM86 this issue was fixed a long back tekken runs awesome without any issue.
