### ISSUE TITLE
Borderlands GOTY Enhanced (729040)

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Proton#3354]
# Compatibility Report
- Name of the game with compatibility issues: Borderlands GOTY Enhanced
- Steam AppID of the game: https://steamdb.info/app/729040/

## System Information
- GPU: GTX 760
- Driver/LLVM version: NVIDIA 440.44
- Kernel version: 5.4.6
- https://github.com/shoober420/linux-scripts/blob/main/home/shoober420/sysinfonvidia
- Proton version: 4.11-11

## Symptoms

You have to change two things for this to work good. First, as mentioned on the ProtonDB (https://www.protondb.com/app/729040), you have to rename "BorderlandsGOTY.exe" to "Launcher.exe". Use the ```DO=(%command%); "${DO[@]/%Launcher.exe/BorderlandsGOTY.exe}"``` launch option.

Second, set "Framerock Locking" to "Unlimited" in the video settings, especially if you're using NVIDIA, to fix the framerate stuttering.

**Comment by soredake** [comment]
Game crashes before startup with proton 5.0-3.
[steam-729040.log](https://github.com/ValveSoftware/Proton/files/4239640/steam-729040.log)

**Comment by Ottoman-Von-Bismarck** [comment]
Hey, so I too did change the names of the Launcher and BorderlandsGOTY files and now when I run the game in proton 4.2 a graphic comes up and a collapsed window that is black also appears. These only appear on proton versions that are 4.2 or older otherwise nothing happens. These only appeared after I had changed those file names as before nothing would happen when trying to launch. The graphic and the collapsed window will remain open until closed and don't load anything. Is there anything else I should try doing to get it to actually load the game?

**Comment by gverm** [comment]
It seems that with a recent Proton or game update, the launcher trick is not needed anymore. Game worked OOTB for me with recent Proton-Experimental. I did still have to set "Framerock Locking" to "Unlimited" in the video settings, since I'm on Nvidia.

**Comment by Blisto91** [comment]
I was having issues with this game when i set vsync on or fps limiter below 100 i got horrible fps drops when i moved my mouse around. Even in character selection main menu since it has vsync on i think. When i turn off vsync and set fps limiter to unlimited it goes away ingame. I'm guessing that's to do with the suggestion people say to set it to unlimited
This does not happen on windows.

I then also discovered that the issue seemed to go away completely when i launch the game with gamemode even with vsync on and fps limiter set.

**Comment by kisak-valve** [comment]
Hello @shoober420, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2494#issuecomment-1139966130. This went unnoticed for a long time due to an former bug in Github where an issue report was no longer indexed for searches when the author has turned into a ghost.
