### ISSUE TITLE
Super key does not work

### ISSUE THREAD

**Issue by strlcat** [ValveSoftware/Proton#3528]
Proton version: 4.11-12
Affected game: any (in this case, Elder Scrolls Online)

X11 Super key does not work. I do not have a dedicated Czech keyboard layout, and usually type Czech characters like č or ř via pressing [Alt-Gr]+[c]+[c] or [Alt-Gr]+[c]+[r] to get these characters typed. On vanilla Wine (4.0) it works correctly, but on Proton wine it does not work at all. It does not work even in Wine apps shipped with Proton. It would be great to enable this functionality, so behavior is consistent across all X11 programs.

**Comment by aeikum** [comment]
This might be due to ValveSoftware/wine@557144d3b78b1dbe1b8e9dc14e2e6ccda2a1c11d. @electrorys can you try enabling XIM in the registry? You can use the `PROTON_DUMP_DEBUG_COMMANDS` runtime option to dump some scripts in `/tmp/`, which will let you run regedit with `/tmp/proton_$USER/run regedit`. Then you can add this registry key:

    [HKCU\Software\Wine\X11 Driver]
    UseXIM="y"

And see if that fixes your text input.

**Comment by strlcat** [comment]
Thank you @aeikum, this fixed the problem! Although ESO still does not accept Czech characters, at least behavior in Proton Wine is restored. I will try to solve ESO part myself.

**Comment by KairanD** [comment]
@electrorys What distro are you running? I have the same problem, but the solution is not working for me. Another user said it works in Debian (https://github.com/ValveSoftware/Proton/issues/3791), but it's not working in Ubuntu. At least not for me. I've tried different computers, versions and games. My knowledge about GNU/Linux is very limited, but I'm sure I did it right (exactly like the other user at 3791 did).

**Comment by strlcat** [comment]
> @electrorys What distro are you running? I have the same problem, but the solution is not working for me. Another user said it works in Debian (#3791), but it's not working in Ubuntu. At least not for me. I've tried different computers, versions and games. My knowledge about GNU/Linux is very limited, but I'm sure I did it right (exactly like the other user at 3791 did).

I am running Slackware 14.2, updated to latest SW versions (aka 15.0). Also, I got it working only partially - some characters are typed okay, but chars like č or ř do not work. I suspect this is due to ESO not supporting them (at least when it is launched from Wine/Proton), because in Wine (Proton 4.11) native apps these characters are working fine.
I applied only solution from https://github.com/ValveSoftware/Proton/issues/3528#issuecomment-589828273, not trying anything else.
**Edit**: I also forgot to mention that I run this game with `LC_ALL=cs_CZ.UTF-8 LANG=cs_CZ.UTF-8 %command%`. Maybe setting locale in game command line will help.

**Comment by KairanD** [comment]
@electrorys Thanks for the answer and for the tip! I tried running with `LC_ALL=pt_BR.UTF-8 LANG=pt_BR.UTF-8 %command%`, but it also didn't work. :(

I know it's not a problem with ESO because it worked when I was using Windows 10 Home. And it also happens in other games. I have some apps running with Wine (like MS Office 2013 x86) and working fine. I don't use Windows anymore (since April I think), just Ubuntu. What I can't understand is that I can type the letter "ç" (that I think only exists in Portuguese) normally, but I can't type letters with accents, like "á", "ã", "é", "ó", "õ". 

Being unable to type these letters is a pain in Portuguese, because I'm basically unable to type some words (differentiated only by accents) and I always need to tell my friends that my shameful grammar is a GNU/Linux problem. Same thing when typing in Spanish. It was driving me nuts and I almost installed Windows 10 back. But now I'm training to avoid some words and abbreviate others. Typing like that still makes me feel bad, but I believe in open source software and it's amazing what Proton has done for the community. I love Ubuntu, but it seems it may be a distro or configuration problem.

**Comment by KairanD** [comment]
**GOT IT WORKING!** With a fresh install of Ubuntu 20.10. The problem was my system. Now I can confirm that the solution above works. In my case, it wasn't necessary to run with `LC_ALL=pt_BR.UTF-8 LANG=pt_BR.UTF-8 %command%`.

**Comment by JudgeGregg** [comment]
It works, but make sure to use a string key value for regedit, without quotes: see #3791
