### ISSUE TITLE
Deus Ex: Mankind Divided (337000)

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/Proton#3589]
# Compatibility Report
- Name of the game with compatibility issues: Deus Ex: Mankind Divided
- Steam AppID of the game: 337000

## System Information
- GPU: RX 560 with aco
- Driver/LLVM version: X.Org Radeon RX 560 Series (POLARIS11, DRM 3.36.0, 5.5.6-17-tkg-pds, LLVM 9.0.1)
- Kernel version: 5.5.6-17-tkg-pds
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
- Proton version: 5.0-3

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-337000.log](https://github.com/ValveSoftware/Proton/files/4271917/steam-337000.log)

## Symptoms 
Game infinitely loads save.

## Reproduction
1. Start game.
2. Try to load save.

**Comment by kisak-valve** [comment]
From #3096:
@kajzersoze commented on 2020-03-12T16:37:45:

This was working fine 2 days ago, in the meantime there was mesa update that I remember and I'm not sure but I think Proton as well, anyway it doesn't launch anymore, it crashes and exits after several seconds.

Proton 5.0-4
Mesa  20.0.1
***
@fls2018 commented on 2020-03-12T17:52:07:

Yes can confirm Proton 5.0.4 has broke this, unofficial GE 5.1 Proton (maybe later versions although haven't tested yet) still works.
***
@kajzersoze commented on 2020-03-12T18:13:18:

Indeed it runs with GE 5.2
Thanks for the information!

**Comment by alasky17** [comment]
We have found a fix for this, which will be in the next Proton release. In the meantime, there is a new app branch for the Proton 5.0 app called "proton-5.0-3" which you can use to play the game. You can find it on the BETAS tab in the settings for the Proton 5.0 tool in your Steam client.

**Comment by aeikum** [comment]
Hello. Deus Ex: Mankind Divided should be playable again in Proton 5.0-5. Thanks for reporting the problem!

**Comment by soredake** [comment]
Proton 5.0-5, still infinitely loads save.
[steam-337000.log](https://github.com/ValveSoftware/Proton/files/4363337/steam-337000.log)

**Comment by kopr12** [comment]
Works fine here, loading saved games as well.

**Comment by doitsujin** [comment]
@soredake your logs show some vkd3d messages, indicating that you might be using D3D12, which is known still have issues. Have you tried D3D11?

**Comment by soredake** [comment]
@doitsujin d3d12 is disabled in launcher, then i added `WINEDLLOVERRIDES="d3d12=d" `, same result, only disabling esync/fsync fixed infinitive loading.
[steam-337000.log](https://github.com/ValveSoftware/Proton/files/4364950/steam-337000.log)

**Comment by soredake** [comment]
Tested with 5.6 kernel, nothing changed.

**Comment by soredake** [comment]
Hmm, old save does not load even with NO_{E,F}SYNC, starting new game, saving, and loading new saves working fine with fsync and esync enabled.

**Comment by soredake** [comment]
Is anyone having problems with this game?

**Comment by jqadev** [comment]
I reported an issue regarding D3D12 here https://github.com/HansKristian-Work/vkd3d/issues/122 and @doitsujin explained here https://github.com/HansKristian-Work/vkd3d/issues/122#issuecomment-630757866 that the game doesn't launch because of a missing native d3dcompiler_47 library in Proton.
@soredake or @kisak-valve, please reopen this issue as there are still things to do to run this game using vkd3d.

**Comment by kisak-valve** [comment]
Hello @jqadev, the reporting user has chosen to close this issue report. Since there isn't an open compatibility report for this unofficially supported game, feel free to open a new compatibility report.

**Comment by soredake** [comment]
Proton 5.13-1, game still can't start out of the box in dx12 mode.

**Comment by fconyt** [comment]
Tested on 6.3-4, 5.13-6, 5.0-10 and Experimental. Doesn't work with or without esync or fsync. Attached both proton and game logs, plus steam system info. Both DX11 and 12 do not work.
[steam-337000.log](https://github.com/ValveSoftware/Proton/files/6557093/steam-337000.log)
[Deus Ex -  Mankind Divided.log](https://github.com/ValveSoftware/Proton/files/6557092/Deus.Ex.-.Mankind.Divided.log)
[sysinfo.txt](https://github.com/ValveSoftware/Proton/files/6557106/sysinfo.txt)

**Comment by Weirdo1312** [comment]
I launched this game once with wined3d
I exited the game and removed the wined3d line and now it works fine with dxvk
the problem is the initial first time setup that dxvk cannot process wile wined3d can

**Comment by soredake** [comment]
Can anyone confirm this?

![изображение](https://user-images.githubusercontent.com/5204968/147358262-0f586241-9401-4676-9375-9b0e4f954911.png)

**Comment by ahjolinna** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/3589#issuecomment-1000853318

with my short test with proton-experimental [bleeding-edge] it does seem to run fine on DX12, there is some random stuttering but I think its shader caching

------------

my system spec:

```
             .;ldkO0000Okdl;.                ahjolinna@localhost
         .;d00xl:^''''''^:ok00d;.            OS: openSUSE 20211228
       .d00l'                'o00d.          Kernel: x86_64 Linux 5.15.8-1-default
     .d0K^'  Okxoc;:,.          ^O0d.        Uptime: 4d 7h 29m
    .OVVAK0kOKKKKKKKKKKOxo:,      lKO.       Packages: 2853
   ,0VVAKKKKKKKKKKKKK0P^,,,^dx:    ;00,      Shell: bash 5.1.12
  .OVVAKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.     Resolution: 3840x2160
  :KVAKKKKKKKKKKKKKK: kKx..dd lKd   'OK:     DE: KDE 5.89.0 / Plasma 5.23.80
  lKlKKKKKKKKKOx0KKKd ^0KKKO' kKKc   lKl     WM: KWin
  lKlKKKKKKKKKK;.;oOKx,..^..;kKKK0.  lKl     GTK Theme: Materia-dark [GTK2/3]
  :KAlKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:     Icon Theme: Papirus
   kKAVKKKKKKKKKKKK0x;,,......,;od  lKP      Disk: 17T / 25T (68%)
   '0KAVKKKKKKKKKKKKKKKKKK00KKOo^  c00'      CPU: AMD Ryzen 7 5700G with Radeon Graphics @ 16x 4.3GHz
    'kKAVOxddxkOO00000Okxoc;''   .dKV'       GPU: NVIDIA GeForce RTX 3060 Ti
      l0Ko.                    .c00l'        RAM: 5322MiB / 15771MiB
       'l0Kk:.              .;xK0l'         
          'lkK0xc;:,,,,:;odO0kl'            
              '^:ldxkkkkxdl:^'

```

**Comment by jarrard** [comment]
DX12 is slower then DX11 in this game. And snags/crashes in areas. 

I have a issue atm where it takes forever to load in between MAJOR map changes. (new area of world)

**Comment by Bloodis94** [comment]
Tested with proton 7.0-1, out of the box the game arrive to the builtin launcher, starting the game a black fullscreen window appear and crash after ~1 min.

Tested with dx11 & dx12

System-spec:
![image](https://user-images.githubusercontent.com/57262788/154333504-4f580741-4480-4c2f-93c6-7f6505fc8add.png)

Vm created with Unraid, 16 core assigned (8 real, 8HT), gtx 1080 in passthrough, usb card in passthrough

**Comment by kisak-valve** [comment]
Deus Ex: Mankind divided

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5789.
@stixholder posted on 2022-04-24T01:10:24:

# Compatibility Report
- Name of the game with compatibility issues: Deus Ex: Mankind dividded
- Steam AppID of the game: 337000

## System Information
- GPU: AMD Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-109-generic)
- AMD FX-8350
- Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 21.2.6 / LLVM 12.0.0)
- Kernel version: 5.4.0-109-generic
- Linux Mint 20.3 (64 bit)
- Proton version: Proton Experimental
- X Server Release:  12013000
- X Window Manager:  Mutter (Muffin)
- Steam Runtime Version:  steam-runtime_0.20220119.0

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

## Symptoms 
After playing some prolonged time the game will freeze, with only music playing and mouse still working, while following error popup shows:
"Microsoft Visual C++ Runtime Li...
Runtime Error!
Program: N:\.steam\\debian-installati...
R6025
-pure virtual function call"

## Reproduction
Intermittent / after prolonged playing (0.5 to 2h), while the game will freeze - probably always, during using, combining, or moving items around a lot inside the inventory

Using starting parameters "env LD_PRELOAD='' DISABLE_VK_LAYER_VALVE_steam_overlay_1=1 %command%", to prevent the notorious stuttering issues otherwise kicking in after some time (see https://github.com/ValveSoftware/Proton/issues/47). But the freeze would seem to occur also without those params.

**Comment by jarrard** [comment]
> * Driver/LLVM version:  4.6 (Compatibility Profile) Mesa 21.2.6 / LLVM 12.0.0)
> 
> * Kernel version: 5.4.0-109-generic

There a reason your using a outdated kernel and driver? Also make sure your xserver is up to date.  
You may need to look at a community updated repo. I don't use Debian based distros anymore so can't remember the process.

**Comment by stixholder** [comment]
@jarrard : Well, I'm using Mint 20.3, which is based on Ubuntu 20.4, which is based on Debian testing, to my knowledge.

Not that I'd favour Ubuntu, but before that, I tried Manjaro (to avoid outdated deps like in Ubuntu), which was way too flaky and breaky, to be of much practical use, as I spent more time hunting down issues with the OS, than I do now writing bug reports. 

Plus, game distributors (namely Steam) and game vendors (Feral Interactive, Firaxis) kind of insisted on me using Ubuntu, before providing any 'support' for their software (which they really don't either way).

I've had my share of fixing messed-up deps due to using different repos and I'd like to avoid that kind of issues on my 'plain and simple gaming box', if possible, where I intended to enjoy a little more convenience. I was tempted to try LMDE first, but a few weeks ago, it was still at version 4, and it's based on Debian stable, so it might be even more 'outdated' than the Ubuntu-based branch.

What OS do you use, anyway?

EDIT:
Besides, the error looks more of a native Microsoft C++ DLL or Wine issue to me (which may or may not be solved by a newer kernel).

**Comment by jarrard** [comment]
> What OS do you use, anyway?

I use EndeavourOS and haven't had really any issues with reporting bugs and what not. Also typically these days Feral and Firaxis will not fix linux bugs for the most part anyway because the games last released are very old. They even removed several of them off the Linux supported steam page.

**Comment by soredake** [comment]
I don't use linux or care about linux gaming anymore.
