### ISSUE TITLE
Sorcery! Part 1 & 2

### ISSUE THREAD

**Issue by zelmor** [ValveSoftware/Proton#3649]
# Compatibility Report
- Name of the game with compatibility issues: Sorcery! Parts 1 and 2
- Steam AppID of the game: 411000

## System Information
- GPU: Intel HD 5500
- Driver/LLVM version: 18.3.6-2+deb10u1
- Kernel version: 5.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/zelmor/fd96674e05aa3e82367d5c88ecd338b6
- Proton version: 5.0.4

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-411000.log](https://github.com/ValveSoftware/Proton/files/4351870/steam-411000.log)

## Symptoms 
crashes without game window appearing

**Comment by kisak-valve** [comment]
Hello @zelmor, I'm not seeing any hints as to how this game is failing in the log, however, I did notice that you have no vulkan drivers installed. Please install the 32 bit and 64 bit vulkan drivers for your gpu with something like `sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386` and retest.

**Comment by speakn2pabst** [comment]
"Sorcery! Part 1 & 2" used to run without issues from my personal experience and also as testamented by a number of platinum ratings on ProtonDB.com https://www.protondb.com/app/411000

But returning to it recently it now runs with terrible performance such as needing many moments to process a mouse left-click and has visual artifacts, especially on the UI buttons but also in the background.  It's an older game that shouldn't required high resources and it runs over OpenGL.  The issue was persistant across all current available Proton prefixes (3.x,4.x,5.x) and including Proton Experimental.  The visual artifacting was least noticeable in Proton 3.7-8 but was still present (for instance the 'Quit' button) and also still awful performance. 

GPU :  AMD Vega 56
Driver:  AMD Radeon RX Vega (VEGA10, DRM 3.40.0, 5.11.10-xanmod1-1, LLVM 11.1.0)
Driver Version:  4.6 (Compatibility Profile) Mesa 20.3.4
Kernel :   5.11.10-xanmod1-1
Gist of Sys info  https://gist.github.com/speakn2pabst/0621688db8d651f98a04ea9e240397a4
Proton version :  3.7-8, 5.13-6

Proton Log for 3.7-8   (minor artifacting and bad performance)
(Had issue with drag and drop so provided via Gist)
https://gist.github.com/speakn2pabst/2859019e325fbf56599ee11b699f6398

Proton Log for 5.13-6 (bad artifacting and bad performance)
https://gist.github.com/speakn2pabst/aa272b9917892ea10ca58629e54820a6

Symptoms - Awful performance and some visual artifacting.

Workaround  -  It is easy to see how the game should perform without issues, just start it in a fresh WINE prefix.  It doesn't appear to have DRM, Steam doesn't even need to be running.  I started it with my distros WINE (non staging) (6.4-1) and all the performance was back and no artifacts to be seen.  It was a 64 bit prefix defaulting to Win 7 compatibility.  So the issue relates only to Proton.

**Comment by zelmor** [comment]
Issue is resolved in latest proton experimental.
