### ISSUE TITLE
FileNotFoundError for /dist/bin/wine

### ISSUE THREAD

**Issue by n-jay** [ValveSoftware/Proton#3702]
Proton version: 4.11

I've been testing out different (non-steam) game executables using the following proton terminal command.
`STEAM_COMPAT_DATA_PATH=~/.proton/ ~/.steam/steam/steamapps/common/Proton\ 4.11/proton run ./game-file.exe`

At first, I tested in my PC (running Ubuntu 18.04) which I had _pre-installed Steam on_. The command worked as intended and Proton handled most games I threw at it.

Then I thought of running a VM instance on Azure (Ubuntu 18.04) and seeing if I can replicate the functionality.
Based on the previously mentioned command above I assumed that the directories **.proton** and **Proton 4.11** are all that's needed to run Proton standalone. So I extracted those 2 folders separately, put them in a single directory and re-ran my command via a bash script (accounting for the changes in location). It worked fine in my local machine.

That script is as follows:
```
export STEAM_COMPAT_DATA_PATH=$PWD/.proton
PROTON_USE_WINED3D11=1 
PROTON_NO_ESYNC=1 
$PWD/Proton-4.11/proton run ./demos/demo1/game-file.exe
```

But as soon as I run it on the Azure VM, I get the following error:

```
Traceback (most recent call last):
  File "/home/proton/Documents/folders/Proton-4.11/proton", line 738, in <module>
    g_session.run()
  File "/home/proton/Documents/folders/Proton-4.11/proton", line 706, in run
    self.run_proc([g_proton.wine_bin, "steam"] + sys.argv[2:])
  File "/home/proton/Documents/folders/Proton-4.11/proton", line 697, in run_proc
    subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/proton/Documents/folders/Proton-4.11/dist/bin/wine': '/home/proton/Documents/folders/Proton-4.11/dist/bin/wine'
```
This is not possible since the **wine** executable _does exist_ in the /dist/bin/ location.
![image](https://user-images.githubusercontent.com/24616975/77859236-ca344100-7225-11ea-8316-2d0aab3bc0db.png)

Assuming it was something to do with Azure's VM, I thought of recreating an exact environment in my local machine via VirtualBox (using an Ubuntu 18.04 iso) and retrying.
Alas, the results were the same.

I'm assuming this means there are other directories or files that I haven't accounted for which are being utilized by the command, although not explicitly mentioned.
My questions are;

1. Is my assumption correct?
2. If so, what are those directories?
3. If otherwise; what is the exact cause of this issue and how can I address it?

**Please note that this version of Proton I've used was not built from source, rather it was the one extracted from `~/.steam/steam/steamapps/common`

**Comment by aeikum** [comment]
That's a pretty wacky setup. I think you're largely on your own here. If you're running outside the Steam runtime, then possibly it can't find the loader executable, but that's just a guess.

**Comment by n-jay** [comment]
> If you're running outside the Steam runtime, then possibly it can't find the loader executable, 

Noted @aeikum. Where exactly can I find the loader executable? I'm still very new to this and its taking some time to know the ropes.

Also, just to clarify...

> I assumed that the directories .proton and Proton 4.11 are all that's needed to run Proton standalone.

I mentioned the above in my original post. 
Is this assumption correct?

**Comment by ghost** [comment]
I looked a tiny little bit into this.

"This is not possible since the wine executable does exist in the /dist/bin/ location."

The file not found error could be a bit misleading (errors can at times be very misleading). eg "Raised when a file **_or directory_** is requested but doesn’t exist."

https://docs.python.org/3/library/exceptions.html#FileNotFoundError

There are possibly other situations with that depending on what the code is doing. One way or another, it cannot find the file from what or where it is.

For example, in this situation

https://teamtreehouse.com/community/filenotfounderror-errno-2-no-such-file-or-directory-workdirmessymessy

the person recommends "OR, Python doesn't have the permissions to access the files at that path…". That is not to say the file's perm _could be_ correct but Python (not you) must be able to access the full path as well. If it can't then can you say that the file is not found? Yes.

There are other weird things that can happen though such as if the code knows the full path but uses relative path eg "../someFolder/someFile".

I'm not sure of all the values its holding or if its using full vs relative paths etc. Didn't really look at it that way. Just pointing out some things.

**Comment by badly-drawn-wizards** [comment]
Seconding this.
I am running on NixOS. Both the steam distributed 4.11 and 5.0 give this error.
