### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by es20490446e** [ValveSoftware/Proton#3737]
What works under Wine doesn't seem to work at all with Proton.

Tried with both steam-manjaro and steam-native, also deleting the steam folders. I also tried listing missing libs following the instructions in the Arch wiki, but no missing dependency was listed.

Here's the [log](https://bin.privacytools.io/?1db1d6fc2a38eb06#caS2MQxNwtLSv2Ybkvp1trDGRWaGn+aV1Gil/etOeU4=) and, just in case you want to see further detail, a [screencast](https://youtu.be/hwD842bj9Kg).

My system specs are:
- Manjaro Deepin stable branch
- Radeon HD5870
- linux 5.5
- mesa 19.3.5

**Comment by kisak-valve** [comment]
Hello @es20490446e, the ATi Radeon HD5870 does not support Vulkan, which is required for DXVK to work inside of Proton. You may have luck adding `PROTON_USE_WINED3D=1 %command%` to the games launch options in order to use Wine's DirectX to OpenGL render path, but this comes with a significant performance penalty and is not considered supported.

**Comment by es20490446e** [comment]
@kisan-valve https://github.com/ValveSoftware/Proton/issues/3738
