### ISSUE TITLE
Homeworld Remastered Collection (244160)

### ISSUE THREAD

**Issue by Theogore** [ValveSoftware/Proton#3774]
# Compatibility Report
- Name of the game with compatibility issues: Homeworld Remastered
- Steam AppID of the game: 244160

## System Information
- GPU: NVIDIA GeForce RTX 2080 Ti
- Driver/LLVM version: 440.44
- Kernel version: 5.3.0-7642-generic
- Link to full system information report as [Gist](https://gist.github.com/): 
**https://gist.github.com/virtusgaming/d313fafeb09be61f9511bf48dae6f681**
- Proton version: 5.06

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-244160.log](https://github.com/ValveSoftware/Proton/files/4484286/steam-244160.log)

## Symptoms 
Clicking Play, the Steam interface acts like it's going to do something but then nothing happens and the button changes from "Cancel" to "Play"

## Reproduction
1. Install Homeworld Remastered.
2. Click Play.
3. Nothing happens.

**Comment by Konfuz** [comment]
The game itself runs fine, it is the launcher that wont start. 
Fix should be a low hanging fruit, someone wrote an external launcher that works with proton: https://git.sr.ht/~_dev_fra/hwrc-proton-launcher

**Comment by madewokherd** [comment]
Should this and #99 both be open?

**Comment by kisak-valve** [comment]
@madewokherd, nice find, looks like there's a search index bug in Github which makes #99 not appear in searches. I'm guessing it's related to the user turning into a ghost.

Because we're using one issue report per unofficially supported game title, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/99#issuecomment-626318519.
