### ISSUE TITLE
youtube-dl.exe support

### ISSUE THREAD

**Issue by XLPhere** [ValveSoftware/Proton#3798]
Hey,
`youtube-dl.exe` still seems to have issues, has anyone found an workaround to it on getting it working? The thing is VRChat runs pretty well at the time of writing this (SteamPlay: Proton 5.0-6). The only issue is that you have to delete or rename/move `youtube-dl.exe` (at least thats the only way that works *for me* right now, which obviously consequently disables every youtube-dl powered function in VRC though). 

In the thread dedicated to VRChat i also heard something that the (missing?) `Microsoft Visual C++ 2010 Redistributable Package (x86)` (https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-468045658) is the issue, even though i didn't felt confident enough to tinker with it yet, since i have rather limited knowledge about wine and proton myself. 
Anyone has an idea how to fix this? (or maybe even get a global patch on proton for this?)

Why is this a separate issue and not inside the VRChat-thread?
- Having a separate issue for this problem is probably more organized then having this issue together with several other issues in the VRC's main issue-thread 
- Even though my point of view right now is only related to VRC, this might also be effecting other apps/games that use youtube-dl.exe

Thanks for helping!

**Comment by kisak-valve** [comment]
Hello @XLPhere, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-619371252.

I have to disagree that this should be tracked separately because VRChat is the only game on Steam being run through Proton and uses youtube-dl that we currently know about.
