### ISSUE TITLE
Euro Truck Simulator 2 (227300)

### ISSUE THREAD

**Issue by Patola** [ValveSoftware/Proton#3827]
# Compatibility Report
- Euro Truck Simulator 2
- 227300

## System Information
- GPU: RTX 2070 SUPER
- Driver/LLVM version: 440.82
- Kernel version: 5.0.0-20-mfutex #21+1valve1+mfutex1-Ubuntu
- Link to full system information report as Gist: https://gist.github.com/Patola/6341ab77bb48691b3d762515f5a9f3f1
- Proton version: 5.0-7
[steam-227300.log](https://github.com/ValveSoftware/Proton/files/4572611/steam-227300.log)
- Ubuntu 20.04
- 32 GiB RAM

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 

Euro Truck Simulator 2 VR Mode does not seem to work on Proton. Other proton games like Half-Life: Alyx and Borderlands 2 VR work perfectly with the same setup.

## Reproduction
- Change Euro Truck Simulator 2 to force proton 5.0-7
- Change Euro Truck Simulator 2 branch (on BETAS tab from properties) to oculus - Oculus/Vive - 1.36 - (SDK 1.4.0)
- Change launch parameters to: PROTON_LOG=1 %command% -openvr (or simply -openvr if you don't want the debug info)
- On properties -> General disable "Use Desktop Game Theatre while SteamVR is active"
- Just for additional assurance, disable SteamVR Home on the SteamVR settings
- Launch SteamVR, wait for it to settle
- Launch Euro Truck Simulator 2, it will ask which version, run 64-bit DirectX11 (which works perfectly under non-VR)

**Comment by Patola** [comment]
Note, the Linux version does not support VR mode, nor does it have an executable in the oculus 1.36 depot.

**Comment by Patola** [comment]
Euro Truck Simulator 2 works beautifully in VR right now under Proton 5.0-8. I don't know what changed. Should I close this ticket?

**Comment by mimattr** [comment]
> Euro Truck Simulator 2 works beautifully in VR right now under Proton 5.0-8. I don't know what changed. Should I close this ticket?

@Patola Can also confirm VR is now working with **Proton 5.13-2** and **SteamVR 1.15.9**, as well as the standard non-VR version.

This issue is resolved and can be closed/whitelisted.

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 455.38**
- Distro version: **Ubuntu 20.04 LTS**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **5.13-2**
- SteamVR version: **1.15.9**

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.

**Comment by Patola** [comment]
Maybe this ticket can be closed now? Should I be the one doing it?

**Comment by mimattr** [comment]
> Maybe this ticket can be closed now? Should I be the one doing it?

@Patola "Yes" and "Yes", thanks!
