### ISSUE TITLE
[Whitelist] Command & Conquer: Red Alert 3 - Uprising (17480)

### ISSUE THREAD

**Issue by tr37ion** [ValveSoftware/Proton#402]
Arch Linux
Kernel 4.18.3
Proton 3.7
Nvidia GTX 1070 - nvidia-beta 396.54
KDE Plasma 5.13.4
KDE Framework 5.49.0
Qt 5.11.1
GFX max

Command & Conquer: Red Alert 3 - Uprising works without problems, except that sometimes some of the EFX are looking strange. I'm not sure if that's it used to be or there is a minor issue. IN general I would say it works.

**Comment by kisak-valve** [comment]
With Proton 5.0-3 and the game set to 1920x1080 and the graphic preset set to High, I observed the game having major rendering issues with Intel graphics, and crashing with nVidia graphics on the same system. Adding `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 %command%` to the game's launch options resolved both these issues. (Quick test with the first tutorial.)

**Comment by Wedge009** [comment]
Isn't 17480 the Steam ID for Red Alert 3, not Uprising?

At any rate, Red Alert 3 (not Uprising) seems to work just as I remember it on Windows, running on Proton 8.0-2. The big problem is start-up - it takes a disproportionately long time (~2 minutes) before RA3.exe calls ra3_1.12.game, at first I thought Proton had failed to run the game.

**Comment by kisak-valve** [comment]
Hello @Wedge009, looking around a bit, that is correct. It looks like that detail got missed.

The whitelist system doesn't really exist in the wild anymore, having been replaced by Steam Deck Verification. Also, `PROTON_FORCE_LARGE_ADDRESS_AWARE` is now enabled by default.

I think our best option here is to close this issue report, continue tracking feedback on Command and Conquer: Red Alert 3 - Uprising on #6459, and since there isn't another compatibilty report tracking 17480, you can open a new compatibility report with your findings.
