### ISSUE TITLE
How to check proton version that game is run with?

### ISSUE THREAD

**Issue by furai** [ValveSoftware/Proton#4073]
Hello,

How can I check in Steam client/filesystem which version of proton the game is using? 
It seems that some games bypass the default global setting and use proton version that has been reported working for that game? 
Am I wrong with that assumption? (At least it seemed to be the case with Doom 2016 for me. I had to manually force it to 5.0.9).

I've searched around multiple times and I couldn't find any answer to my question.

I hope that someone can help me with that.

And I'm sorry if this has been answered somewhere but I can't seem to find it.

Cheers,
Furai

**Comment by kisak-valve** [comment]
Hello @furai, In the Steam client, go to the game in your Library, and click the ⓘ icon on the right side. In the additional details, if a compatibility tool is in use, it is noted there and why it was selected.

**Comment by furai** [comment]
Thanks a ton, I've literally looked everywhere I could to find this information. And it was so obvious. Thanks again! :)

**Comment by darkbasic** [comment]
@kisak-valve it says "Proton Experimental selected by you for this title" but if I go to Properties -> Compatibility the "Force the use  of a specific Steam Play compatibility tool" options is not checked. Is it because I've opted into Steam Beta? Or just because the title (Age of Empires 2 Definitive Edition) defaults to Proton Experimental?

**Comment by kisak-valve** [comment]
Hello @darkbasic, that reads like the Proton version you chose in Steam's global settings is being used. (`Steam` -> `Settings` -> `Compatibility` section.)
