### ISSUE TITLE
World of tanks

### ISSUE THREAD

**Issue by jaspi72** [ValveSoftware/Proton#4105]
# Compatibility Report
- Name of the game with compatibility issues: world of tanks by lutris

## System Information
- GPU: gtx1050
- Driver/LLVM version: nvidia-450
- Kernel version: 5.4.0-42-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jaspi72/64ffb1951ccd4569b681aa065050eb90
- Proton version:Proton-5.9-GE-5-ST

## I confirm: 
Launcher starts but when push play nothing happends. 
Lutris own win it works but missing win10 and need something to get mod tundra working..

**Comment by kisak-valve** [comment]
Hello @jaspi72, this feedback is a bit odd because you're giving feedback about a non-Steam game, being run outside of Steam, using a third party Proton build. There's pretty much nothing here for a Proton dev to use to improve the mainline Proton build. However, in general, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1369#issuecomment-665651296 and you can continue discussing your issue over there.
