### ISSUE TITLE
Silent Hunter Wolves of the Pacific (15200)

### ISSUE THREAD

**Issue by cudla100** [ValveSoftware/Proton#4196]
# Compatibility Report
- Name of the game with compatibility issues: Silent Hunter Wolves of the Pacific
- Steam AppID of the game: 15200

https://store.steampowered.com/app/15200/Silent_Hunter_Wolves_of_the_Pacific/
https://store.steampowered.com/app/15240/Silent_Hunter_Wolves_of_the_Pacific_UBoat_Missions/

## System Information
- GPU: NVIDIA Corporation GeForce GT 635M/PCIe/SSE
- Driver/LLVM version: 4.6.0 NVIDIA 390.138
- Kernel version: 5.4.0-47-generic
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/cudla100/99e13d51c10787718d17b750919742ee
- Proton version:5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available. Both flatpak and Ubuntu are up to date.

[steam-15200.log](https://github.com/ValveSoftware/Proton/files/5217575/steam-15200.log)

## Symptoms 
1)The game opens with black screen and small message box that says "cannot initialize 3D engine". I click "ok" and game shuts itself down. Problem can be solved by switching to older proton version.

2)Should I create new issue next time? I am new to this. Game is missing some sounds. For example sound of diving below the thermal layer or sound of putting all crew to battle stations. I tried to change settings, but nothing seems to work.

## Reproduction
1)I start the game.

2)These sounds never work during playing.

**Comment by kisak-valve** [comment]
Hello @cudla100, looking at your system information, the nVidia's 390 series driver is older than the support cutoff for Proton and it doesn't provide Vulkan support for your Fermi generation video chipset anyway. It'd be a bad idea to try a newer nVidia driver series because support for Fermi was dropped after the 390 series. Also, the video drivers for the Intel Ivybridge in your system provides an incomplete implementation that might partially work, but quirky graphics are expected.

With Proton 5.0, the included build of DXVK grew support for D3D9, which is what changed compared to older Proton versions, exposing the incomplete nature of Vulkan on Ivybridge to you.

You may have luck trying `PROTON_USE_WINED3D=1 %command%` in the game's launch options to tell Proton to use wine's DirectX to OpenGL render path, but this comes with a significant performance penalty and is not considered supported.

--

We're using one issue report per unofficially supported game title. Since this game is not whitelisted, we'd like to hear all feedback about it here in one compatibility report.

**Comment by cudla100** [comment]
The command fixed both problems. Thank you.
