### ISSUE TITLE
All proton games fail with the same error about DXVK

### ISSUE THREAD

**Issue by rebelC0der** [ValveSoftware/Proton#4198]
Hello.

Issue: All games that I run via `Proton` (any version) or `Steam Linux Runtime` fail with the same error:
```
Xlib:  extension "NV-GLX" missing on display ":0".
terminate called after throwing an instance of 'dxvk::DxvkError'
```
The latest example: Bioshock Remastered. Logo on the desktop is displayed (game starts to load) and then stops and the error above is displayed.

I am on a laptop with a dual-graphics (Nvidia optimus) and I run all other applications/native games like just fine with `primusrun APP`. Proton stuff fails on NVidia and on Intel GPUs

NVidia driver:
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 765M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 390.132
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 390.132
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
```

System:
```
Manjaro Linux x86_64 
CPU: Intel i7-4710MQ (8) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 765M 
GPU: Intel 4th Gen Core Processor 
Kernel: 5.8.6-1-MANJARO
```

Anyone else had this issue?

**Comment by kisak-valve** [comment]
Hello @RebelCoderRU, primusrun is not compatible with Vulkan. This is not a proton issue.

Looks like your nVidia 765M is a Kepler generation chipset which is supported by the current nVidia driver series (450.xx as of this writing) and you'll most likely have a better experience with setting up PRIME render offloading instead of using bumblebee (https://wiki.archlinux.org/index.php/PRIME#PRIME_render_offload). Alternatively, look into using primus_vk.
