### ISSUE TITLE
Among us dont work

### ISSUE THREAD

**Issue by tanqkq** [ValveSoftware/Proton#4202]
among us.
issue: Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed
Linux Mint x64, nvidia gt210

**Comment by kisak-valve** [comment]
Hello @tanqkq, in general, we're using one issue report per unofficially supported game title, and usually I'd transfer this to #4190, but in your case it's clearly a lack of hardware capability.

Proton uses DXVK to efficiently translate DirectX 9/10/11 to Vulkan. Your nVidia Tesla generation video card does not support Vulkan, so it doesn't meet the minimum requirements for Proton.

You might have luck trying `PROTON_USE_WINED3D=1 %command%` in the game's launch options to tell Proton to use wine's DirectX to OpenGL render path, but that comes with a significant performance penalty and is not considered supported. Additionally, your hardware does not support DirectX 11 on Windows, so there's only a small chance that this game will run at all. And to pile more grim news on top of that, support for the nVidia 340 driver series, which is the newest driver that supports your card, has ended entirely.

It's just not going to happen unless you get really lucky.

**Comment by DestyNova** [comment]
I must say it is a bit surprising that a 2D game would require a rather modern graphics card...

**Comment by DestyNova** [comment]
**Update:** I tried swapping out the proprietary NVidia driver for the open-source nouveau driver (which often causes system hangs, otherwise I'd stick with it more often), and the game launches just fine directly with `wine64`. However, then I wasn't able to access my DLC pets, and I'm guessing online play won't work.

According to lspci, my laptop's graphics card is:
```
02:00.0 VGA compatible controller: NVIDIA Corporation GT218M [GeForce 310M] (rev a2) 
```

If it works with Wine, surely Proton should support it? How do we debug this? Can you reopen the issue @kisak-valve?

**Comment by kisak-valve** [comment]
Hello @DestyNova, no, please use #4190 to discuss this game.
