### ISSUE TITLE
Among us on Debian 10

### ISSUE THREAD

**Issue by jumpy72red** [ValveSoftware/Proton#4250]
# Compatibility Report
- Name of the game with compatibility issues:
Among Us
- Steam AppID of the game:
945360 (I think that's it, it is the number from the URL)

## System Information
- GPU: Intel Open Source Technology Center Mesa DRI Mobile Intel® GM45 Express Chipset
- Driver/LLVM version: 00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07) (From `lspci | grep VGA`)
- Kernel version: 4.19.0-10-amd64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/jumpy72red/ef9e5e89e494029692d28a9f651afa32
- Proton version: 5.0-9

## I confirm:
- [Confirm ] that I haven't found an existing compatibility report for this game.
- [Confirm ] that I have checked whether there are updates for my system available.

[steam-945360.log](https://github.com/ValveSoftware/Proton/files/5359856/steam-945360.log)

## Symptoms 
I click play and it says `Launching...` for about 30 seconds then just turns into `Play` again. The game doesn't launch.

## Reproduction
Click play and wait for crash.

**Comment by kisak-valve** [comment]
Hello @jumpy72red, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #4190, but in your case, your fourth generation Intel gpu chipset is not supported by Proton because it does not have Vulkan support.

You might get lucky by adding `PROTON_USE_WINED3D=1 %command%` to the game's launch options to tell Proton to use wine's DirectX to OpenGL render path, but that comes with a significant performance and is not considered supported.
