### ISSUE TITLE
Proton 5.13 forces installation of "Steam Linux Runtime - Soldier" when STEAM_RUNTIME=0

### ISSUE THREAD

**Issue by StarterX4** [ValveSoftware/Proton#4277]
When the STEAM_RUNTIME=0 environment variable is set, running any game with Proton 5.13 forces installation of "Steam Linux Runtime - Soldier". Uninstalling it and trying to run the game keeps installing it again.
I don't want a bunch of deprecated useless libraries taking up 500MB of my disk space.

**Comment by misyltoad** [comment]
Proton 5.13 requires Steam Linux Runtime - Soldier.

Its a different Steam Runtime to the one referred to in STEAM_RUNTIME=0 so this is not an issue.

**Comment by kisak-valve** [comment]
Hello @StarterX4, this is intentional and expected. Steam Linux Runtime - Soldier is a container environment in addition to being a separate and updated set of runtime libraries. Proton 5.13 is built on top of the Soldier runtime instead of the older Scout runtime, and LD_* style runtime setup which STEAM_RUNTIME=0 influences.
