### ISSUE TITLE
Beyond Two Souls (960990)

### ISSUE THREAD

**Issue by minionprocyk** [ValveSoftware/Proton#4372]
# Compatibility Report
- Name of the game with compatibility issues: Beyond Two Souls
- Steam AppID of the game: 960990

## System Information
- GPU: 5700XT
- Driver/LLVM version: Mesa 20.2
- Kernel version: 5.8
- Link to full system information report as [Gist](https://gist.githubusercontent.com/minionprocyk/c216ba4ed2a939f28a849f8c91e77c13/raw/588483cde16293e30f0e74ea50ad8684b46e0efa/system%2520info):
- Proton version: 5.13-2

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-960990.log](https://github.com/ValveSoftware/Proton/files/5540351/steam-960990.log)

## Symptoms 
- Game audio crackles when using eiden or any low frequency sound is played. 
- Game hangs on exit and requires a force quit from steam to exit completely

## Reproduction
1. Start beyond two souls
2. Enter play area and switch to eiden
3. Run around aimlessly / click buttons and you may trigger the sound crackling
4. Exit to main menu
5. Exit Game (game will now hang)

**Comment by SimpliFly03** [comment]
To fix audio problem you can add `WINEDLLOVERRIDES="xaudio2_7=n,b" %command%` as launch options.

**Comment by FanderWasTaken** [comment]
> * Game hangs on exit and requires a force quit from steam to exit completely

Seems to have been fixed by Proton 6.3-7. But my save file corrupted after 3 hours of play... (was also an issue on PS3 apparently, so I assume that's game's fault not Proton's)

> * Game audio crackles when using eiden or any low frequency sound is played.

Also isn't an issue with Proton 6.3-7.

**Comment by Jhackler** [comment]
Gpu: vega 56 Driver mesa 21.1.5 llvm13.0.0 Frame rate drops super hard right at beginning but gpu load is less than 1% and the clock speed steams bellow 300mhz
Proton experimental and 6.3-7 This is the second game I have had this issue with all other games work correctly.

**Comment by DanMan** [comment]
Proton Experimental 7856446: For me there's sometimes an endless saving bug (constant save icon - usually it takes only a second) . I can either I quit the game or wait until it crashes itself. In any case my savegame will be corrupted on next launch, meaning I have to start over.

Other than that I can't complain much. Sometimes the framerate drops pretty low. I guess that's how a crash announces itself early, because it happens in areas you've already visited while performance was fine. Best to quit and restart the game when that happens. Performance is usually good again then, too. Memory leak maybe?

**Comment by minionprocyk** [comment]
Using latest proton stable, 7.0-4
Game no longer hangs on exit, I played around for about an hour and could not reproduce the same sound crackling i remember originally. This appears to be fixed.
