### ISSUE TITLE
Non-working VkBasalt in Proton 4.xx.x

### ISSUE THREAD

**Issue by guglovich** [ValveSoftware/Proton#4394]
## System Information
- GPU: AMD RX460
- Driver/LLVM version: Mesa 20.2.2-2, LLVM 11.0.0-1
- Kernel version: 5.9.8
- System information : https://gist.github.com/guglovich/40a7f0d65d21600c864dbe8c25581566
- Proton version: 4.11.13

## I confirm:
- [+] that I haven't found an existing compatibility report for this game.
- [+] that I have checked whether there are updates for my system available.

## Symptoms 
VkBasalt does not work with Proton 4 in the branch. I test it after updates, but apparently it did not work initially.

## Reproduction

100% repetition. Tested on game Remember Me

**Comment by kisak-valve** [comment]
Hello @guglovich, in general, support for vkBasalt is out-of-scope for the Proton issue tracker. It's an independent project. Also, it may be worthwhile to mention this to the vkBasalt dev(s).

I'm going to close this because it's not a Proton dev's problem to solve, but someone might have some ideas to try.
