### ISSUE TITLE
GTX 770 2GB, very low performance on DX11 titles running in DXVK (even in lowest quality)

### ISSUE THREAD

**Issue by Deus-nsf** [ValveSoftware/Proton#4414]
The PC is actually very powerful, Ryzen 5900X with the latest Manjaro build, latest Nvidia drivers and latest proton version as today.
DX9 games runs fine but for some reason DX11 games runs super slowly at 1080p (Resident Evil 2 and FF15 were tested) we're talking like 10-20 FPS in lowest preset for both games.
I was wondering if the GPU would be too old since Vulkan is a modern tech but I remember being able to play DotA 2 at max settigns on Windows and also DOOM 2016 not at max settings though, using the Vulkan renderer, and they were running quite good.

Any idea ? Maybe the translation layer from DX11 to Vulkan requires a lot of VRAM ?

**Comment by lucifertdark** [comment]
It's time for you to upgrade that GTX770 to something with a bit more oomph. Even my GTX1650 is struggling with some of the newer games.

**Comment by Deus-nsf** [comment]
It is planned, when Nvidia restocks though :D however, it is not a very good answer sorry, I don't care about that don't worry but imagine you say something like that to someone who can't afford a 3070 or 3060 (when it launches), the 770 on windows works very well at 1080p as long as you are willing to sacrifice VRAM heavy settings like textures and shadow resolutions, it's certainely not a 15 FPS card, also RE2 remake is extremely well optimized, and FF15 is well optimized on the GPU too as long as the CPU is good.

**Comment by CygnusTerminal** [comment]
Is your Manjaro a fresh installation? Have you tried another distro (like EndeavourOS, more close to pure Arch than Manjaro)? So we can rule out the problem being with Manjaro. If you have, and problems persist, your GPU is at fault. Sorry, but there is no other thing you can do, unless you are into overclocking, but i think that would not help too much.

**Comment by Deus-nsf** [comment]
Oh damn, I thought I precised it but I forgot, yep this is a fresh install. Everything is properly up to date, I think the GPU is at fault because we tried with my 1080 Ti previously and everything was fine, but since it's my main GPU I took it back and gave my friend (which has the linux based PC) my secondary GPU (the 770), but I was surprised by the lackluster performance. Maybe the Kepler architecture just doesn't play very nicely with Vulkan. But also maybe there is something wrong with how Proton translates DX11 to Vulkan for that architecture, since on Windows the card was doing fine, it's actually not a bad GPU, it just lacks VRAM.

**Comment by kisak-valve** [comment]
Hello @RSF-Deus, this issue would need to be evaluated on [DXVK's issue tracker](https://github.com/doitsujin/dxvk/issues) for any real assessment, however, looking at the minimum requirements for these games, you are right up against the resource limits of your video card.

From Resident Evil 2's minimum requirements:
`Graphics: NVIDIA® GeForce® GTX 760 or AMD Radeon™ R7 260x with 2GB Video RAM`
`Additional Notes: This game is expected to run at 1080p/30 FPS. If you have don't have enough graphics memory to run the game at your selected texture quality, you must go to Options > Graphics and lower the texture quality or shadow quality, or decrease the resolution.`
and Final Fantasy 15's minimum requirements:
`Graphics: NVIDIA® GeForce® GTX 760 / NVIDIA® GeForce® GTX 1050 / AMD Radeon™ R9 280`
`Additional Notes: 720p 30fps`

We do know that DXVK does need a bit more vram than Windows and nVidia's driver doesn't get to manage it as well. Similar issue reports: https://github.com/doitsujin/dxvk/search?q=more+vram+label%3Aperformance&type=issues

Once the game asks for more vram than is available, it can get pushed to system ram and you can detect this scenario by keeping an eye on PCIe Bandwidth utilization in nVidia's X server settings utility. Normal PCIe utilization is fairly low, but if the system needs to render with some stuff in system ram, then it quickly becomes a high percentage and typically stays there because the game doesn't know it has been put on a slow path.
