### ISSUE TITLE
Forcing a specific Steam Play version causes games to be downloaded again

### ISSUE THREAD

**Issue by Popkornium18** [ValveSoftware/Proton#4418]
Whenever I try to change the Steam Play version for some title, Steam downloads the entire game again.
I'm using the stable Steam Client on Arch Linux.

I'll gladly provide further information, however I'm not sure what information would be useful.

**Comment by kisak-valve** [comment]
Hello @Popkornium18, downloading and managing game content is handled by the Steam client instead of Proton itself, and it looks like a similar issue is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7388. Feel free to add your experience to that issue report if you have any additional insight.

Closing in favor of the older issue report.

**Comment by Popkornium18** [comment]
Alright, thanks!
