### ISSUE TITLE
proton 5.13-2

### ISSUE THREAD

**Issue by tails2021** [ValveSoftware/Proton#4424]
Computer Information:
Manufacturer: Unknown
Model: Unknown
Form Factor: Desktop
No Touch Input Detected

Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz
CPU Family: 0x6
CPU Model: 0x17
CPU Stepping: 0xa
CPU Type: 0x0
Speed: 2933 Mhz
2 logical processors
2 physical processors
HyperThreading: Unsupported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Unsupported
AES: Unsupported
AVX: Unsupported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

Operating System Version:
Ubuntu 20.04.1 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 5.4.0-54-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12008000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20201005.0

Video Card:
Driver: Intel Open Source Technology Center Mesa DRI Intel(R) Q45/Q43 (ELK)
Driver Version: 2.1 Mesa 20.0.8
OpenGL Version: 2.1
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x8086
DeviceID: 0x2e12
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1280 x 1024
Desktop Resolution: 1280 x 1024
Primary Display Size: 13.39" x 10.63" (17.09" diag)
34.0cm x 27.0cm (43.4cm diag)
Primary VRAM Not Detected

Sound card:
Audio device: Realtek ALC662 rev1

Memory:
RAM: 3831 Mb

VR Hardware:
VR Headset: None detected

Miscellaneous:
UI Language: English
LANG: fi_FI.UTF-8
Total Hard Disk Space Available: 233200 Mb
Largest Free Hard Disk Block: 115914 Mb 

deus ex human revolution director cut and deus ex the fall working proton 5.13-2 
OpenGL Version: 2.1

**Comment by kisak-valve** [comment]
Hello @tails2021, Proton uses DXVK to translate DirectX 9/10/11 to Vulkan, and your video chipset does not support Vulkan.

It looks like both of these games use DirectX 9, so it would take this render path. You might have some luck setting `PROTON_USE_WINED3D=1 %command%` in the game's launch options to tell Proton to use wine's DirectX to OpenGL render path, however, this is expected to come with a significant performance penalty and is also not considered supported. You might get lucky with some games using this environment variable, but in general your hardware isn't going to work very well with Proton due to a lack of hardware features.
