### ISSUE TITLE
Cannot start any game with Proton

### ISSUE THREAD

**Issue by Idealismus87** [ValveSoftware/Proton#4587]
# Compatibility Report
- Name of the game with compatibility issues: e.g. Fallout Shelter
- Steam AppID of the game: 588430

## System Information
- GPU: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07)
- Driver/LLVM version: Mesa 20.2.6
- Kernel version: 5.4.0-65-generic
- Link to full system information report as [Gist](https://gist.github.com/): 
https://gist.github.com/Idealismus87/aced543e83a6d6de26694a75fb50c221
- Proton version: 5.13-5

## I confirm:
- [y] that I haven't found an existing compatibility report for this game.
- [y] that I have checked whether there are updates for my system available.

(steamlog in homefolder is empty)

## Symptoms
Program does not start. The starting process runs for about a second and then stops.

**Comment by Leopard1907** [comment]
I think this is simply related to your gpu not having Vulkan support. By default DXVK is being used for d3d9/10/11 titles which makes good chunk of the games and probably apps you tested are using those api's.

You can try `PROTON_USE_WINED3D=1 %command%` as a launch option for any of the games that fails.

Right click to game on library-Properties-Launch options

https://github.com/ValveSoftware/Proton#runtime-config-options

**Comment by Idealismus87** [comment]
Thanks for the idea but the problem persists as before. Any other ideas?

**Comment by kisak-valve** [comment]
Hello @Idealismus87, as noted by @Leopard1907, there is a major lack of hardware support in the fourth generation of Intel graphics. It's unfortunate, but hardware from that era doesn't have feature parity between DirectX and OpenGL and most games will have trouble with wine/Proton regardless of any workaround you attempt. Your hardware is unsupported by Proton.

Using `PROTON_USE_WINED3D=1 %command%` in the game's launch options tells Proton to try to use wine's DirectX to OpenGL render path, and it was your best chance at getting something to work, but it comes with a significant performance penalty and is not considered supported.

**Comment by Idealismus87** [comment]
Thanks for putting it straight @kisak-valve . Seems like I need new graphic card. 
I'm still wondering though as fallout shelter is playable on my 5 year old smartphone.

**Comment by Leopard1907** [comment]
@Idealismus87 While we're going a bit off topic , 

1-) Your pc hw is older than 5 years.
2-) Comparing an Android port of a game against a PC game is wrong. Because that game you mentioned needs GLES 2.1 on Android which means even Android 4.4 era phones are capable to run it, while on PC port it requires D3D11 which your PC hw doesn't expose/advertise D3D11 support on Windows either.
3-) For DX9 titles at least you have a better chance due to wined3d at least a bit better on dx9 compared to what wined3d offers for dx11. But still perf hit would be so much.
4-) https://gitlab.freedesktop.org/airlied/mesa/-/blob/crocus/src/gallium/drivers/crocus/crocus_todo.txt

If this becomes a reality at a further date very old hw like yours might have a better chance at running D3D9 titles in a more performant way assuming when this happens Proton will also expose Gallium9 support.
