### ISSUE TITLE
[Nier: Automata] Denuvo cannot reach the servers

### ISSUE THREAD

**Issue by flying-train** [ValveSoftware/Proton#461]
After several hours of downloading, the game won't launch, with Denuvo error message:
"The server is not reachable, check your Internet connection and click 'Retry'.
In case the problem persists, click 'Next' to open the support website in the default browser"

Clicking retry achieves nothing, so does clicking next. That's weird considering it is a whitelisted game by Valve. My internet connection is fine, the game is legally obtained via Steam (obviously), my PC has all the specs to launch the game.

System info:
OS: Antergos Linux x86_64
Driver: nvidia  396.54-1

**Comment by flying-train** [comment]
For some reason running Steam from the terminal once fixed the issue, and from then on the game can be launched without steam running from the teminal.

**Comment by Matoking** [comment]
I encountered this problem myself as well on Arch Linux. In the end it turned out to be Steam running using native libraries instead of Steam Runtime; I had forgotten a `export STEAM_RUNTIME=0` line in my ~/.bashrc file which meant Steam Runtime was always skipped regardless if I ran Steam with `steam` or `steam-native`. Running Steam with `STEAM_RUNTIME=1 steam` on the other hand worked.

**Comment by hexchain** [comment]
Got the same problem today on Arch Linux, with `steam-native` (i.e. without bundled runtime). Switching to Proton 4.2-3 worked for me.
