### ISSUE TITLE
Fonts are buggy on all source engine games running with proton

### ISSUE THREAD

**Issue by kleinermob** [ValveSoftware/Proton#4616]
they look like this https://imgur.com/f7IvshZ
please fix

**Comment by Neoony** [comment]
by the way, did you solve this somehow or find some workaround?
Since its closed

Same thing for Empires Mod
Affects Deck experience on proton, but also anyone not on deck

**Comment by JerryDELUXE** [comment]
Why was this closed? This is still an issue. Playing any HL2 mod through proton makes the menus and subtitles really hard to read. Not to mention subtitles which use italics (which are very frequent in HL2) are nearly impossible to read. This seems to be because the game doesn't use it's own font, but rather, a generic one.
![20240513151049_1](https://github.com/ValveSoftware/Proton/assets/146459906/a73b5fc0-db64-4859-a96d-b573c9dd4fe2)
![20240513151108_1](https://github.com/ValveSoftware/Proton/assets/146459906/2ba86203-af2d-4371-84c1-c0e1b4a87901)

**Comment by Neoony** [comment]
at least for the game I had issue with (empires mod), it seems some proton version has fixed it and changed the font some time ago (but its not the same font as in Windows, its some other font which has no symbols, so some signs are squares, but thats much less issue)
