### ISSUE TITLE
Thief Simulator fails to start

### ISSUE THREAD

**Issue by hlangli** [ValveSoftware/Proton#4655]
# Compatibility Report
- Name of the game with compatibility issues: Thief Simulator
- Steam AppID of the game:704850

## System Information
- GPU: Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 2000 (SNB GT1)
- Driver/LLVM version: 3.0 Mesa 20.2.6
- Kernel version: 5.8.0-44-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hlangli/60a395a637f14d512de629788ea76009
- Proton version:5.13-6, 5.0-10, 4.11-13, 4.2-9, 3.16-9, 3.7-8, Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-704850.log](https://github.com/ValveSoftware/Proton/files/6056374/steam-704850.log)

## Symptoms Game doesn't start
The game fails to start and shows an error dialog with the following exception:
`kernelbase.dll caused an Unknown exception type (0x20474343)
  in module kernelbase.dll at 0033:7b01193e.

Error occurred at 2021-02-27_104132.
Z:\home\adam\.local\share\Steam\steamapps\common\Thief Simulator\thief.exe, run by steamuser.
35% memory in use.
4096 MB physical memory [4096 MB free].
4096 MB paging file [-2048 MB free].
4096 MB user address space [4096 MB free].

Context:
RDI:    0x0021e888  RSI: 0x0021e958  RAX:   0x0021e880
RBX:    0x045a5680  RCX: 0x0021e860  RDX:   0x00000000
RIP:    0x7b01193e  RBP: 0x0021ec90  SegCs: 0x00000033
EFlags: 0x00000202  RSP: 0x0021e840  SegSs: 0x0000002b
R8:    0x00000001  R9: 0x0021e950  R10:   0x00000000
R11:    0x0021e628  R12: 0x045a5640  R13:   0x0021ea70
R14:    0x0021eaa0  R15: 0x0021e9d0

Bytes at CS:EIP:
90 48 81 c4 c8 00 00 00 5e 5f c3 0f 1f 80 00 00 
`
If I put PROTON_USE_WINED3D11=1 in the Launch Options, the game starts, but is painstakingly slow.  So much so that it is unusable.  I have also tried with PROTON_NO_ESYNC and PROTON_NO_D3D11 and any combination of the 3 options, but it doesn't change anything.  I have also tried each of the available Proton versions in the Steam compatibility section for the game.  I've also tried installing wine separately with winetricks and dxvk.

## Reproduction
Try to run the game

**Comment by kisak-valve** [comment]
Hello @hlangli, Proton uses DXVK to translate DirectX 9/10/11 to Vulkan and your video chipset does not support Vulkan. Since `PROTON_USE_WINED3D11=1` gets the game running, that tells use the game is otherwise usable besides the lack of hardware features in your system.

The `PROTON_USE_WINED3D` (and older `PROTON_USE_WINED3D11`) runtime option tells Proton to use wine's DirectX to OpenGL render path, but this comes with a significant performance penalty and is not considered supported. No amount of tinkering would get around that.

Looking at the game's minimum requirements, you would need to add a modern mid-range add-on video card in order to have a chance at running this game properly, but as it stands now, your system is not supported by Proton in general (for any games using DirectX 9 to 12).
