### ISSUE TITLE
Stutter when loading new areas with AMD 6800XT

### ISSUE THREAD

**Issue by Gip-Gip** [ValveSoftware/Proton#4688]
When entering areas I haven't been in before there is really bad stuttering for any proton game, from Halo: CE to Dark Souls 3. The stuttering is temporary and goes away after a few seconds, but comes back when loading in a new area/asset/something. The stuttering does not reset when I reload the game, and it only sometimes resets when steam rebuilds the shader cache(I think)

I do not have this problem with linux native games like minecraft or borderlands 2

Any clue what the issue could be from per chance?

Hardware includes:
- AsRock TaiChi 6800XT graphics card
- Ryzen 9 3900X cpu
- 16GB 3200mhz DDR4 ram
- 970 evo ssd

Software includes:
- Arch Linux
- Ly display manager
- XFCE4 desktop environment thing(compositor disabled)
- EXT4 file system
- Proton experimental(tested on all version still the same issue)

willing to provide more info if need be

**Comment by kisak-valve** [comment]
Hello @Gip-Gip, you've described what happens when the video driver's on-disk shader cache has not been warmed up. The stuttering would be the game waiting on shaders to compile as it encounters them for the first time in-game. The point of Steam's shader pre-caching is to exercise the video driver's compiler with shaders it thinks the game will be using ahead of time. Every time you update your video driver, the existing on-disk shader cache gets invalidated and the video driver has to start over, re-caching the shaders for each game.

In general, native Linux games are aware of this behavior and some use various techniques to hide shader compilation in the background, while games run with Proton and DXVK are not and have to deal with the driver overhead as it is encountered.

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, I'd like to check if you're using a point release of mesa or a bleeding edge build.

**Comment by Gip-Gip** [comment]
Thank you for the quick response, I had a feeling that's what the issue was but I wasn't 100% certain. I should add I've tested this on both mesa and mesa-git, I may retry mesa-git again soon but last time I checked it didn't solve the issue

Otherwise everything *should* be bone-stock

[https://gist.github.com/Gip-Gip/28fe5c57195fa92bd61296bd30119e84](https://gist.github.com/Gip-Gip/28fe5c57195fa92bd61296bd30119e84)

**Comment by kisak-valve** [comment]
Your system information tells us that you are using AMDVLK for Vulkan, and not mesa/radv, so for the most part it doesn't matter what version of mesa you're using when it comes to caching Vulkan shaders.

**Comment by Gip-Gip** [comment]
That pisses me off.. out of all the forum/reddit posts and all the hunting it's an AMDVLK issue. I switched over to RADV and games run smooth as butter. Glad someone finally found the culprit, I appreciate it
