### ISSUE TITLE
Borderlands GOTY Enhanced Stuck on Splash Screen

### ISSUE THREAD

**Issue by Ottoman-Von-Bismarck** [ValveSoftware/Proton#4728]
# Compatibility Report
- Name of the game with compatibility issues: Borderlands GOTY Enhanced
- Steam AppID of the game: 729040

## System Information
- GPU: 2nd Gen Intel Integrated Core Processor
- Driver/LLVM version: 3.0 Mesa 20.3.4
- Kernel version: 5.10
- Link to full system information report as [[Gist]](https://gist.github.com/Ottoman-Von-Bismarck/04a9a4990b2eb6ce407f6110b1c6dc89)
- Proton version: 4.2-9

## I confirm:
- [yes] that I haven't found an existing compatibility report for this game.
- [yes] that I have checked whether there are updates for my system available.

(Proton logs compress well if needed.)--> 
[steam-729040.log](https://github.com/ValveSoftware/Proton/files/6250104/steam-729040.log)

## Symptoms
Stuck on the splash screen when launching. When launched the splash screen appears along with a collapsed black window that will use 100% CPU although nothing else happens (I have run it for ~20 min with no change). I have already renamed the Launcher.exe and BorderlandsGOTYEnhanced.exe files which allowed for the splash screen to appear in the first place (prior the game would crash on launch). When I run the unenhanced copy of the game the same splash screen and black window will appear but then in a few seconds the game itself appears. I've seen a few other posts on this and other forums where folks had the same issue but I didn't see any responses to them. Any help would be much appreciated. Thank you.

![problem](https://user-images.githubusercontent.com/39245558/113428182-3098f580-938b-11eb-9ba2-e7e51b3f4d90.png)

**Comment by kisak-valve** [comment]
Hello @Ottoman-Von-Bismarck, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #3354, however, the cause is obvious in your case.

Proton uses DXVK to translate DirectX 9 / 10 / 11 to Vulkan, but your Intel Sandybridge chipset does not support Vulkan, which will make most games run with Proton fail when trying to initialize the graphics component of the game. You could try setting the game's launch options to `PROTON_USE_WINED3D=1 %command%`, which tells Proton to use wine's DirectX to OpenGL render path, but this runtime option is not considered supported. Unfortunately, your system in general is not supported by Proton.

**Comment by Ottoman-Von-Bismarck** [comment]
Ok, thanks. I had a feeling it was because the computer couldn't handle it but figured that I should check first. Thank you for bearing with me. Have a nice day.
