### ISSUE TITLE
Grand Theft Auto V does not launch

### ISSUE THREAD

**Issue by movedtocodeberg** [ValveSoftware/Proton#4737]
# Compatibility Report
- Name of the game with compatibility issues: Grand Theft Auto V
- Steam AppID of the game: 271590

## System Information
- GPU: GTX 1660
- Driver/LLVM version: nvidia 460.67
- Kernel version: 5.11.11
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/gksudolol/c54bfa91c6d2aeeeb76d959ce35ece87
- Proton version: Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-271590.log](https://gist.github.com/gksudolol/3117be68422868b86ac5ce84e9a99667)

## Symptoms
Upon launching GTA V via Steam, an error dialog pops up showing "Unable to launch game, please verify your game data"

## Reproduction
Install Steam from the Arch Linux official repository, opt-in to Steam Beta Update and enable Steam Play in the Steam Settings, select "Proton Experimental" under Run other titles with. Download GTA V and launch the game with no added launch options.

**Comment by kisak-valve** [comment]
Hello @gksudolol, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-813040493.

**Comment by linuxmintg** [comment]
I've had the same problem! I am using Linux Mint 19.3, Kernel is lower than gksudolol : 5.0.0-32-generic

Do we get our money back if there is no solution? I only had the game for roughly 6 months. I am so glad I finished it on time!

**Comment by movedtocodeberg** [comment]
@linuxmintg Looks like we're stuck with an unplayable game, unless we use Windows _*shudders*_

**Comment by linuxmintg** [comment]
@gksudolol -- I don't think it's acceptable. We should get our money back if we don't get the game again. Why should I even use Steam at all? People were raving on about it on Youtube. I followed their instructions on how to use Windows games. You do it. And you get updates whether you like it or not. We're all stuffed. You can't even turn off updates! 

I've looked in the Steam comments/replies. On first glance it looks like all my comments have been deleted! I think anyone who can't play games should complain and take it to a higher level! Take it to the Better Business Bureau!

I will never buy any games again, if this problem is not fixed! I don't give out money on the street.... it's like as if I've thrown money on the street! It's a service and they should look after their customers!

**Comment by linuxmintg** [comment]
@gksudolol -- We're on GNU/Linux because we wanted to escape the Windows/Mac cult! But cursed if we do!

**Comment by linuxmintg** [comment]
My version of Proton was high 4's early 5's from memory.....
