### ISSUE TITLE
How does one install software like Source Filmmaker (1840)? 

### ISSUE THREAD

**Issue by akirapink** [ValveSoftware/Proton#4755]

**Comment by maximstewart** [comment]
@TPO100Cofficial 

Example:
/home/abaddon/.steam/steam/steamapps/common/Proton 6.3/dist/bin/(wine or wine64)  <path_to_your_install.exe>

Though, to be fare there might be better ways such as through Lutris or PlayOnLinux and specifying the Steam Wine paths in there and using their UIs to do the magic.

**Comment by akirapink** [comment]
I mean installing, not running it, because SFM isn't, IIRC, in the user's library. (that, or i made horrible mistakes,) making it so I'm not able to set it to install with Steam Play tools.

**Comment by kisak-valve** [comment]
Source Filmmaker should be in your Steam Library as something that's available to everybody, however, it's categorically Software instead of Games. In the Steam library view, you may need to select Software in the dropdown list under the Home button in the upper left corner, or search for Source Filmmaker. After that the options to tell Steam to use Proton should be the same as any other game.
