### ISSUE TITLE
How I fixed a game that didn't start with proton and why does we have to carry 2 drive_c ?

### ISSUE THREAD

**Issue by bananasmoothii** [ValveSoftware/Proton#4764]
This issue is both a guide and a question

So I had installed Among Us with Steam and could run it without problem. Then I installed Wine and tweaked some files, and a little time after Among Us didn't want to start anymore. So I uninstalled everything: Steam, Among Us, Proton and Wine and reinstalled everything but Wine. It worked again.  I noticed while having Wine that I had 3 drive_c folders (one in `~/.wine`, one in `~/.steam/debian-installation/steamapps/common/Proton - Experimental/files/share/default_pfx/` and one in `~/.steam/debian-installation/steamapps/compatdata/{AMONG US STEAM ID}/pfx/`, and each 3 were taking a lot of disk-space. So I tried to do a symlink that points the other 2 with only one, and that was the cause of Among Us no launching. Using the command line i found that proton deletes the file in .../drive_c/openxr/wineopenxr64.json and then complains that it doesn't exists. Maybe the issue was juste that symlink, but maybe it was caused by wine manually installed

### So here comes my feature request
Could you make it so we can use only 1 drive_c folder so it will limit huge amounts of duplicated files ?

### Risks
users asking proton to use an usable drive_c folder

### version:
proton experimental freshly installed the 18/04/2021

**Comment by kisak-valve** [comment]
Hello @bananasmoothii, in terms of a feature request, this issue is already being tracked in #2691 / #4093 / #604. In particular, https://github.com/ValveSoftware/Proton/issues/4093#issuecomment-665690586 empathizes that the per-game wineprefix should be using symlinks to the default prefix for files that have not changed from the base install. The wine prefix in `~/.wine` is the default location for upstream wine and is unrelated to Proton.

From a functional perspective, some games may have dependencies that can interfere with other games and wineprefixes can not be summary merged without considerable thought on interactions between them and unintended consequences related to that. Also, manipulating wineprefixes with an upstream wine build is not supportable and might cause odd behavior.

Closing in favor of the older feature requests.
