### ISSUE TITLE
World of Tanks (1407200)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#4785]
# Compatibility Report
- Name of the game with compatibility issues: World of Tanks
- Steam AppID of the game: 1407200

## System Information
- GPU: AMD Radeon 6900XT
- Driver/LLVM version: Mesa 21.1.99/12.0.0
- Kernel version: 5.13-rc0
- Link to full system information report as [Gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: 6.3-20210427b

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1407200.log](https://github.com/ValveSoftware/Proton/files/6401065/steam-1407200.log)

## Symptoms 
The game crashed after clicking "Launch" button in the launcher.
Safemode didn't helps.

![Screenshot from 2021-04-30 00-21-33](https://user-images.githubusercontent.com/200750/116606369-12062a00-a94a-11eb-9368-bd62e79756c2.png)

![Screenshot from 2021-04-30 00-26-32](https://user-images.githubusercontent.com/200750/116606871-c7d17880-a94a-11eb-9c5e-f7a4c06b817d.png)

## Reproduction
Always.

**Comment by kisak-valve** [comment]
Hello @NTMan, this game is a bit of an oddball because we've gotten feedback on it years before it was added to Steam. We're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1369#issuecomment-829527024.
