### ISSUE TITLE
Being able to set a theme that gets used for all proton games

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#4915]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I want that you are able to set a custom msstyle theme that gets used for all proton games.
## Justification [optional] 
The default wine doesn't look that good and it would take long to change the theme for every game seperately.

**Comment by kisak-valve** [comment]
Hello @Toadfield, this is close enough to your feature request at #4902 to consider it a duplicate.

**Comment by ghost** [comment]
But it is different,when you set that proton uses your gtk theme,then it doesn't look as good as some msstyles.

**Comment by kisak-valve** [comment]
They're both requests to include theming support, and fragmenting that discussion over multiple feature requests is less than ideal. You can adjust your previous feature request to cover the topic.

Regardless, this topic may be better suited for upstream wine since I don't think that Proton does anything special here.

**Comment by ghost** [comment]
> Regardless, this topic may be better suited for upstream wine since I don't think that Proton does anything special here.

Wine already supports that,you just need a wine manager.
