### ISSUE TITLE
Ori and the Will of the Wisps achievements not granted in Steam Library

### ISSUE THREAD

**Issue by Pixdigit** [ValveSoftware/Proton#5009]
# Compatibility Report
- Name of the game with compatibility issues: Ori and the Will of the Wisps; as well as Hades
- Steam AppID of the game: 1057090 and 1145360

## System Information
- GPU: GeForce GTX 1060 6GB
- Driver/LLVM version: Nvidia 460
- Kernel version: 5.4.0-80-generic
- Link to full system information report as [pastebin](https://pastebin.com/QjyvVGyY): https://pastebin.com/QjyvVGyY
- Proton version: <=6.3 or experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game, that lists this particular issue.
- [x] that I have checked whether there are updates for my system available.

This log is from Ori and the Will of the Wisps in which I was granted about 20 achievements. If you need I can list them also.
[steam-1057090.log](https://github.com/ValveSoftware/Proton/files/6874064/steam-1057090.log)

## Symptoms 
Both games show achievements in-game but do not in the Steam library. I have tried starting the games with other proton versions. In Ori and the Will of the Wisps I still get in-game notifications about achievements, that I previously achieved, when I load a save.

## Reproduction
Play the games on a system similar to the one above and play either game, until an in-game notification about an achievement appears.

**Comment by Pixdigit** [comment]
The issues with Hades has seemingly resolved itself. I got eleven Achievements when I started up Hades for further testing :sweat_smile:

**Comment by kisak-valve** [comment]
Hello @Pixdigit, this needs to be evaluated on a per-game basis and we're using one issue per unofficially supported game title, and usually I'd transfer this issue report to #4528, then ask you to add a note to #3312 for your experience with Hades, but, your Proton log tells us the game is running with Proton 4.2-9 instead of the version you expected, and `err:steamclient:create_win_interface Don't recognize interface name: SteamClient019` is the line of interest from your log. That interface was added with 7aa1b840d945b823034281e03df4bb32cd185ad4 and is in Proton 4.11-3 and newer. Please retest with a newer Proton version and add a note to #4528 with a new Proton log if you can reproduce the issue.

**Comment by Pixdigit** [comment]
Also since I saw that others tend to make the same mistake, it may be worth to clarify that new issues for games which already have a bug report for a different problem, should still go to the pre-existing issue.
