### ISSUE TITLE
Uplay / Ubisoft Connect process stuck open after exiting game

### ISSUE THREAD

**Issue by Mattiams** [ValveSoftware/Proton#5212]
This is for a game purchased on the Steam storefront. In this case, it was Assassin’s Creed Origins. I’ve not been able to install another game requiring Uplay just yet.

Happens regardless of Proton version I am using, switched between Experimental and latest version offered through Steam.

Process shows in the Wine/Proton window on the upper left side of the screen. Can be forced to close by using the Force Quit option for the game on Steam.

Uplay overlay is disabled. Application set to close instead of minimise to taskbar.

**Comment by kisak-valve** [comment]
Hello @Mattiams, from Proton's perspective, it's behaving correctly because Ubisoft Connect is actively running and part of the game. The behavior of Ubisoft Connect sticking around after game exit should be consistent with what happens on Windows, with the exception that Steam for Windows doesn't need to care about what Ubisoft Connect is doing after the game exits.

It might be interesting for someone on Windows to check if Ubisoft Connect has an option to exit along with the game that isn't working properly with Proton.

The Ubisoft tray icon you're referring to can be used to restore their user interface and quit Ubisoft Connect in a controlled manner, instead of forcefully killing it.

**Comment by Mattiams** [comment]
I can certainly try this out after my night shifts end in the next few days. I have a Windows machine I could at the very least install Ubisoft Connect on.

And I was unaware I could restore the user interface. I’m using this on my 4K TV, so have to set the zoom of the desktop to 300%. I will re-launch Assassin’s Creed Origins, quit it, and attempt to do access Ubisoft Connect again. And report back.

**Comment by Mattiams** [comment]
I will be closing this off. I can confirm your previous comment that Proton is working as intended. Ubisoft Connect does not have an option to automatically close when a game closes.

**Comment by fritz-fritz** [comment]
I'd like to reopen this issue. While from Proton's perspective, it is behaving as intended... It would be ideal for the launcher to be closed when the game is quit. This should be completely possible by monitoring for the `UbisoftGameLauncher.exe` process to die and then quitting. The Ubisoft Connect process runs separately as `upc.exe`. I can currently script to watch for the process to terminate and then send the correct kill to gracefully exit the Ubisoft Connect process which allows proton to exit and Steam to end the process. Ideally, this would be handled by proton directly?

**Comment by apo-egix** [comment]
As already mentioned, yes it is working as intended, but not from a linux users perspective, since closing the game should allow me to open another one afterwards. Steam is stuck because upc.exe keeps running and it registers as a game.

@fritz-fritz This is in my eyes the perfect solution for that problem
