### ISSUE TITLE
Silent hunter 3, V

### ISSUE THREAD

**Issue by Stormfinger** [ValveSoftware/Proton#5302]
Hi

i have Debian 11 and xfce on my machine. 
 
1) i have bought silent hunter pack on steam unfortunately when i try to start silent hunter V i receive error that ubisoft service is unavailable and after clicking ok nothing happens.. can you help and advise?

2) in silent hunter 3 the sound is falling behind and its not fluid and periscope is not working. i have previously run it ok in dos box without problem on ubuntu prior ver. 18 .. now i installed it via steam.

![SilentHunter_V](https://user-images.githubusercontent.com/84122683/141186444-538fc1e5-7506-4ae2-84f0-8627860e308c.png)

thank you for your time and assistance.
regards

**Comment by kisak-valve** [comment]
Hello @Stormfinger, in general, we're using one issue report per unofficially supported game title, and you've given what appears to be dissimilar feedback on two different games. In terms of troubleshooting this is a low quality issue report.

For Silent Hunter 5, we already have some feedback on #4650, feel free to add your experience to that issue report.

For Silent Hunter III, please copy the [compatibility report template](https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md) to this issue report, fill it out, and let me know when you're done so I can reopen this issue report. (Edited link because it was improperly formatted)
