### ISSUE TITLE
Grim Dawn Class Selection Broken

### ISSUE THREAD

**Issue by Twinsonian** [ValveSoftware/Proton#535]
i5-4460 / RX 460
Proton 3.7 - Proton 3.7.4
Ubuntu 18.04 / Mesa 18.3.0-devel - padoka PPA

- Missing Shaman class from list of class choices. Also, unable to select any classes on new characters. Have not tested on established characters with only one class selected.
- Grim Dawn does not allow accessing skills menu a second time after leveling a new character.

_This affects Grim Dawn with or without ashes expansion._

**Comment by kungtotte** [comment]
CPU Brand: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
Kernel Version: 4.14.65-1-MANJARO
Driver Version:  4.6.0 NVIDIA 396.51, Proton 3.7

I'm having the same issue. I mounted my Windows games partition and compared the files between the Windows install and this one, and everything matches up. Going to investigate some more.

**Comment by kisak-valve** [comment]
Hello @twinsonian, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue over to https://github.com/ValveSoftware/Proton/issues/466#issuecomment-415994810.

**Comment by dbzlotrfan** [comment]
Actually once you hit a new level (i.e 1->2, 2-> . . . ) you have a very short Windows to click the player level (between the health and mana bars) when it glows. Since I have AOM, once I do get the character selection screen to show (if at all) I don't see the Necromancer class either . . . . Trying to press (or re-assign) the skill window button (normally S) doesn't do anything.
