### ISSUE TITLE
Cuphead Compatability

### ISSUE THREAD

**Issue by HatcherMine** [ValveSoftware/Proton#5381]
# Compatibility Report
- Name of the game with compatibility issues: Cuphead
- Steam AppID of the game: 268910

## System Information
OS: Arch Linux
KERNEL: 5.15.5-arch1-g14-1
CPU: AMD Ryzen 9 5900HS with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU
GPU DRIVER: 495.176.0
RAM: 15 GB
- Proton version: 6.3-8
Game requires the NVidia 32bit utilities when it previously didnt (lib32-nvidia-utils in arch).

**Comment by kisak-valve** [comment]
Hello @HatcherMine, there's not enough actionable detail here to do anything with your feedback. In general, most games used with Proton need a sane, working Vulkan driver stack because it uses DXVK to translate DirectX to Vulkan. If the game is 32 bit, and you didn't previously have nVidia's 32 bit userspace libraries, then the only guess I could make is that the game was previously running on the AMD GPU side of your CPU, and you're hinting that some system issue has happened to break the 32 bit Vulkan render path there.
