### ISSUE TITLE
[Whitelist] Spelunky (239350)

### ISSUE THREAD

**Issue by SakanaKogane** [ValveSoftware/Proton#539]
![Screen capture with game running, neofetch and Valve Proton version](https://user-images.githubusercontent.com/36506430/44618665-8ecbd680-a87a-11e8-8dd4-beabe1f8cd51.png)
[Steam System Information](https://gist.github.com/SakanaKogane/0cc73db28bf03b0781a05d56f91471df)
Spelunky seems to run perfectly. I played it for 4-5 hours and did not see any slowdown, any bug, any glitch or any other problem.

The only thing I would like to mention is that it did not recognize my Xbox One Controller, I don't know however if it's caused by the game or my system and/or my Steam configuration.

**Comment by bruno-fs** [comment]
I played for 30 minutes without issues 

[Steam System Information](https://gist.github.com/varnion/73786ff3a9b41ca2c524bdfcf61cffb7)

I played with a Logitech F310 on Xinput mode

**Comment by jvschiavo** [comment]
It works for me as well. How can I contribute?

**Comment by SakanaKogane** [comment]
@jvschiavo Copy your system information from steam (`Steam -> Help -> System Information`) and put it in a gist, then include a link to the [gist](https://gist.github.com/) in your reply.

_I just copied @kisak-valve's answer to posts where the OP doesn't do this._

You can also give any remarks, if a controller you use works, etc.

**Comment by ghost** [comment]
Works great for me. Xbox One controller works too.
https://gist.github.com/QuirkyTechie/26be9007c0dbe0f932424980e19b4b9f

**Comment by glubsy** [comment]
Spelunky seems to run fine, but losing focus from the window (ie. alt+tab or changing workspace in i3 window manager) results in the window going black and not drawing properly anymore. Have to kill the game in order to fix it. 
This only happens when fullscreen is activated in the game, if windowed mode is active, no problem.

Xbox360 wired controller works very well for me.

**Comment by sachalau** [comment]
Spelunky runs fine with me but only with an X360 like controller. I have three controllers, logitechF710, logitech rumblepad 2 and Steam controller and the only one recognized is the F710. My F710 is emulated as an XboX controller in Steam Big Pic and given the experiences on this threds this fits with only xbox controllers workings. Did somebody managed with something else ? Maybe this could be fixed before switching it to white list ? Otherwise awesome.

**Comment by jvschiavo** [comment]
@SakanaKogane thanks.

I can confirm it works on both of my machines.

System info:
[Desktop](https://gist.github.com/jvschiavo/dd12016a82e27bf43ee3591ba44286a6)
[Laptop](https://gist.github.com/jvschiavo/c04f2cb0ff7ee7aecbc91856a0fed247)

On my laptop I have some stuttering audio issues. Also some gameplays stuttering sometimes as well. But that is probably because the machine is weak.

**Comment by jvschiavo** [comment]
Ok, now I've got a BIG problem. I've finally completed the game (Olmec run, not Yama) and I alt+tabbed to tell my friends and when I alt+tabbed back I got a fatal error and it closed.
I've alt+tabbed right on this part of the ending scene (image for reference only):
![captura de tela de 2018-09-18 09-47-07](https://user-images.githubusercontent.com/20977075/45688567-175f2f00-bb28-11e8-819e-aaa40e322f64.png)

PS: I could alt+tab anywhere else on the game without problems.
Edit: At least I guess the game still thinks I've completed it.

**Comment by kisak-valve** [comment]
Found in the 2018-09-05 white list update.

**Comment by jakemagee** [comment]
Can the default Proton version be updated?  The game runs MUCH better for me on 3.16-8 ... 3.16.-4 might also run fine, but I haven't tried it.  Before with 3.7-8, I was getting small graphical shuddering (hard to describe) that while playable, was visually annoying.  Should I open a new issue to suggest updating the default version?

**Comment by kisak-valve** [comment]
Hello @jakemagee, yes, please do.
