### ISSUE TITLE
No Proton Games Work - Intel Xe - Wayland KDE 

### ISSUE THREAD

**Issue by meechgalhuquot** [ValveSoftware/Proton#5411]
Games that previously have worked on my laptop no longer launching. When I try Hades, it tells me that it does not detect a GPU. Just last week this game ran fine on the same device. Tried Proton 6.3, Experimental, and even GE and none of them will launch any games anymore. Mesa drivers are up to date running Arch

**Comment by Leopard1907** [comment]
At least attach a Proton log so people can look at it for info.

`PROTON_LOG=1 %command%`

**Comment by meechgalhuquot** [comment]
[steam-1145360.log](https://github.com/ValveSoftware/Proton/files/7728108/steam-1145360.log)

**Comment by kisak-valve** [comment]
Hello @meechgalhuquot, the `Command:` line in the log's header is strange, what launch options are you using with the game? There should only be up to one use of `%command%` in the per-game settings if you want to slip environment variables before the command Steam calls to start the game.

Setting that aside, `err:vulkan:__wine_create_vk_instance_with_callback Failed to create instance, res=-1` and `err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance` are the lines you should care about in your log. It tells us that Vulkan is failing to initialize on your system. Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`), wait for Steam to gather the extended diagnostics information, and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by meechgalhuquot** [comment]
[Gist](https://gist.github.com/meechgalhuquot/95e60346bf97549680be0216db97dfe9)
here are all the lauch options as default with the exception of adding the proton log being what I added 
`PROTON_LOG=1 %command% PROTON_FORCE_LARGE_ADDRESS_AWARE=1 PROTON_NO_ESYNC=1 %command%`
I have not adjusted any settings in any of the proton games, Hades is just the one that gave me an error instead of just crashing

**Comment by kisak-valve** [comment]
https://gist.github.com/meechgalhuquot/95e60346bf97549680be0216db97dfe9#file-steamsystem-txt-L153-L166 and https://gist.github.com/meechgalhuquot/95e60346bf97549680be0216db97dfe9#file-steamsystem-txt-L294-L307 are the parts that matter here.

Looking at the installed Vulkan driver icds https://gist.github.com/meechgalhuquot/95e60346bf97549680be0216db97dfe9#file-steamsystem-txt-L468-L491, it seems odd that you have AMDVLK installed on an Intel-only system. I would try removing the `amdvlk` and `lib32-amdvlk` system packages and also install `lib32-vulkan-intel` so that you have a 32 bit Vulkan driver installed for your GPU as well.

`PROTON_FORCE_LARGE_ADDRESS_AWARE` is enabled by default. Because `PROTON_NO_ESYNC=1` is after the first `%command%`, it's getting handed to the game as an argument instead of setting an environment variable. You can shorten that to `PROTON_LOG=1 PROTON_NO_ESYNC=1 %command%` for a more predictable effect.

**Comment by meechgalhuquot** [comment]
removing those AMD drivers seems to have done the trick, they somehow must have got tangled up with steam though because when I tried uninstalling them in Pamac (GUI package manager) it wanted to uninstall Steam and various other packages. Removing with pacman in the terminal worked fine. Interesting how that happened
