### ISSUE TITLE
THE KING OF FIGHTERS XV (1498570)

### ISSUE THREAD

**Issue by krispr1ngle** [ValveSoftware/Proton#5611]
# Compatibility Report
- Name of the game with compatibility issues: THE KING OF FIGHTERS XV
- Steam AppID of the game: 1498570

## System Information
- GPU: AMD/ATI Radeon RX 560
- Driver/LLVM version: Mesa 21.2.6
- Kernel version: 5.13.0-30-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/the-j-master/6555d35c2cced988b36a57df102b25d3
- Proton version: 7.0-1

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Upon selecting a team in the game's Story mode, the game stops on a black screen. Using MangoHUD I was able to confirm that the game wasn't simply freezing up, and inspecting the log reveals a complaint about being unable to find an H.264 decoder in the directory of Proton itself.

## Reproduction
1. Open the game
2. Select "Story" as the game mode
3. Select a team
4. Cutscenes will not play

**Comment by krispr1ngle** [comment]
[steam-1498570.log](https://github.com/ValveSoftware/Proton/files/8133646/steam-1498570.log)
Forgot the log, that's my bad.

**Comment by krispr1ngle** [comment]
Issue fixed in latest patch by SNK.

**Comment by legacychimera247** [comment]
I know this was closed already, but bought the game 2 days ago and having the same exact problem

anyone found a real solution yet?

**Comment by Lucario24** [comment]
I bought the game like a month ago and I am also experiencing the same problem, no videos either on story mode or gallery. 

I've tried many proton versions (official ones, including experimental, and no official ones) since many people in protonDB claim the game works fine (the same way, some people played it using proton official versions while other used non official), but I had no luck in both cases. Game runs fine except for this detail that is preventing me to play story mode. Depending on proton version, when a video plays, it stays in a black screen forever or the game crashes instantly.

I've attached a log from the game running with PROTON_LOG=1 parameter and a file with the output of Help > System Information
[system specs.txt](https://github.com/ValveSoftware/Proton/files/11022651/system.specs.txt)
[steam-1498570.log](https://github.com/ValveSoftware/Proton/files/11022232/steam-1498570.log)

On some of the lines from the log it says "are 64-bit GStreamer "base" plugins installed?",  I make sure to have them installed, still no luck
![imagen](https://user-images.githubusercontent.com/63479471/226455858-81ee1098-6e34-4814-94bc-77ce4120587e.png)

**Comment by legacychimera247** [comment]
well my pc is just a little higher than yours, i hope someone will look at it, since snk removed survival mode so story mode is almost the only thing in the game apart from doing some vs cpu casual matches...

**Comment by Jammmmm** [comment]
I'd like to also add that it does the same for me in Story mode. Versus works fine.

Story -> select your characters -> indefinite black screen requiring a force quit.
You can also check using Gallery -> Movies without the game freezing (you can press ESC to get out of the black screen).

I have tried Proton and GE-Proton, and command line parameters such as -dx11, with no success.
