### ISSUE TITLE
Escape Simulator (1435790)

### ISSUE THREAD

**Issue by dylanmtaylor** [ValveSoftware/Proton#5642]
# Whitelist Request
- Name of the game to be whitelisted: Escape Simulator
- Steam AppID of the game: 1435790

## System Information
Valve Steam Deck
- GPU:  Custom AMD GPU
- Driver/LLVM version:  Latest
- Distro version:  Steam OS 3
- Proton version: 7

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.

This game works flawlessly on the Steam Deck using the out of the box proton configuration without any tweaks needed. Feels native.

**Comment by kisak-valve** [comment]
Hello @dylanmtaylor, this game has a native Linux variant which should be used by default. I'm going to close this whitelist request for now because there doesn't appear to be any action to be taken by a Proton dev.

To ponder this further, I'd like to know if you're sure that you were testing the game with Proton. Also, please explain how this game is substantially better than the native variant.
