### ISSUE TITLE
Sea of Thieves won't allow me to join an Open Crew

### ISSUE THREAD

**Issue by joe1inux** [ValveSoftware/Proton#5761]
# Compatibility Report
Name of the game with compatibility issues: Sea Of Thieves
Steam AppID of the game: 1172620

## System Information
- GPU: i9-12900
- Driver/LLVM version: Nvidia 510.60.02
- Kernel version: 5.15.26-gentoo-x86_64
- Link to full system information report as [Gist](https://gist.github.com/joe1inux/0ff904dbcbe4461f5f4c4b04cdbd9bcb):
- Proton version: Proton Experimental

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

Proton Log:
[steam-1172620.log](https://github.com/ValveSoftware/Proton/files/8457603/steam-1172620.log)

## Symptoms 
I can no longer join open crews.  I suspect there is something interfering with my ability to communicate with Microsoft/Xbox Social gaming servers.

**Comment by kisak-valve** [comment]
Hello @joe1inux, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3931#issuecomment-1094111945.

**Comment by joe1inux** [comment]
Sorry...first time using github...does this mean that all the issues
surrounding Sea of Thieves are on this one page?

Or that my issues is somehow linked to the issue at the top of the page?

**Comment by kisak-valve** [comment]
Using one issue report per game title on the Proton Issue tracker is an exception, rather than a general rule due to the large number of games the Proton devs get feedback on, and there are several bug trackers that the developers need to use on a regular basis. The first half of your question is correct for this issue tracker, #3931 is the right place for all feedback related to running Sea of Thieves with Proton, combined.
