### ISSUE TITLE
Ember Knights (1135230)

### ISSUE THREAD

**Issue by rabidcopy** [ValveSoftware/Proton#5799]
# Compatibility Report
- Name of the game with compatibility issues: Ember Knights
- Steam AppID of the game:1135230

## System Information
- GPU: RX 570
- Driver/LLVM version: Mesa 22.0.2-1/LLVM 13.0.1
- Kernel version: 5.17
- Link to full system information report: [Gist](https://gist.github.com/rabidcopy/74b0a1d6ef368973dc79637ad6e39e96)
- Proton version: Proton Experimental

## I confirm:
- [✅] that I haven't found an existing compatibility report for this game.
- [✅] that I have checked whether there are updates for my system available.

[steam-1135230.log](https://github.com/ValveSoftware/Proton/files/8566197/steam-1135230.log)

## Symptoms 
Playback of intro video file is corrupted.
![unknown](https://user-images.githubusercontent.com/8052832/165374419-c7e2c548-619a-48f1-9ad7-b1e5e19f9cda.png)

## Reproduction
Launch the game and start a new save file. Issue remains with Fullscreen/Vsync options checked/unchecked.

## Notes
Game seems to run completely fine outside of this issue. Multiplayer works as expected.

**Comment by kisak-valve** [comment]
Hello @rabidcopy, can you test if setting the game's launch options to ` WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1 %command%` has an effect?

**Comment by rabidcopy** [comment]
> Hello @rabidcopy, can you test if setting the game's launch options to ` WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1 %command%` has an effect?

This resolved the issue and the video plays without issue now. Thanks. Will keep this launch option mind in the future if I run into a similar problem with video playback.

**Comment by alasky17** [comment]
@rabidcopy If you find more games where video playback is fixed by this launch option, I would appreciate it if you would also tag me or @kisak-valve on this issue tracker to let us know :)  We have a hack in proton right now with all the games that folks have reported need this variable so that other users don't have to go through the same troubleshooting.  I'm adding Ember Knights today, and I can add more in the future if you find more :)
