### ISSUE TITLE
Proton 7.0-2 : Any game don't launch

### ISSUE THREAD

**Issue by Martinc4321** [ValveSoftware/Proton#5835]
# Compatibility Report
- Name of the game with compatibility issues:
ALL

## System Information
- GPU: 
SAPPHIRE RADEON PULSE RX 5700 8G OC / 8GB GDDR6 /
PCI-E / 1x HDMI / 3x DP 11294-01-20G
- Driver/LLVM version: 
[glxinfo.txt](https://github.com/ValveSoftware/Proton/files/8680893/glxinfo.txt)
- Kernel version:
5.15.0-27-generic
- Link to full system information report as [Gist](https://gist.github.com/):
(If u want some gist format, then tell me how ...)
[system.txt](https://github.com/ValveSoftware/Proton/files/8680931/system.txt)
- Proton version: 7.0-2
-Run updates - upgrades.

Proton 7.0-2 ERROR
[ERROR-steam-1484720.log](https://github.com/ValveSoftware/Proton/files/8680851/ERROR-steam-1484720.log)
Proton 6.3-8 WORKING
[WORKING-steam-1484720.log](https://github.com/ValveSoftware/Proton/files/8680849/WORKING-steam-1484720.log)

Start anything and nothing happens.

Steps to reproduce:
1.Click play.
2.Nothing happens.

Running Ubuntu 22.04 .

**Comment by kisak-valve** [comment]
Hello @Martinc4321, `C:\windows\system32\explorer.exe: symbol lookup error: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/vulkan/4/libvulkan_radeon.so: undefined symbol: amdgpu_device_get_fd` looks like the line of interest in your Proton 7.0-2 log. This is telling us that there's a broken video driver issue due to an outdated dependency getting picked up. I'm not aware of any fundamental changes between Proton 6.3 and 7.0 which would make one work but not the other like this.

Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Martinc4321** [comment]
Here u go:
[Gist](https://gist.github.com/Martinc4321/c3d36125d03c859896b8c229a45a7b6f)

**Comment by Martinc4321** [comment]
I have tried different game and not even 6.3-8 is working ...
I updated to 22.04 from the 20.04, however games worked fine for week.
Then it randomly stooped yesterday 
I think.

**Comment by kisak-valve** [comment]
These look like relevant lines in your system information:
```
        "overrides/lib/x86_64-linux-gnu/libdrm.so.2 -> /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0",
        "overrides/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1 -> /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0",`
```

You have leftovers from an amdgpu-pro install (or maybe rocm?) which is interfering and breaking the 64 bit Vulkan render path on your system. Please check if any system package owns files in `/opt/amdgpu` and clean it up.

**Comment by Martinc4321** [comment]
Many thanks,
Where can i send u donate for coffee ?

This command did the trick:
`amdgpu-install --uninstall`

**Comment by Martinc4321** [comment]
Most "amusing" was that the Dead Estate was able to run ... If it wasn't able to run I wouldn't write issue here ...
