### ISSUE TITLE
Horizon Zero Dawn (1151640) won't start w/ latest Proton Experimental

### ISSUE THREAD

**Issue by mackatozis** [ValveSoftware/Proton#5836]
# Bug Report
- Name of the game with issues: Horizon Zero Dawn
- Steam AppID of the game: 1151640

## System Information
- GPU: MSI GeForce RTX 2060 6GB Gaming Z
- Driver/LLVM version: nvidia 470.103.01
- Kernel version: 5.4.0-110-generic
- Link to full system information report as [Gist](https://gist.github.com/mackatozis/51452c5de84f5eab5f5a78513f1949d5):
- Proton version: 1652278199 experimental-7.0-20220511

`PROTON_LOG=1 %command%` Output : [Gist](https://gist.github.com/mackatozis/a1120a4d8ff5590a0e1190ca5528cbc9)

## Symptoms 
Today, on the 13th of May, 2022, my steam client updated to the latest Proton Experimental `1652278199 experimental-7.0-20220511`. By doing so, Horizon Zero Dawn will not start. The game was playable before the update.

## Reproduction
Force the use of a specific Steam Play compatibility tool -> Proton Experimental

## Temp Solution
I changed the Proton version to `7.0-2` and the game boots normally.

**Comment by kisak-valve** [comment]
Hello @mackatozis, we're using one issue per unofficially supported game title, and usually I'd transfer this issue report to #4125, however, this specific issue is that your video driver is too old for VKD3D-Proton in Proton Experimental (`012c:err:vkd3d_init_device_caps: KHR_dynamic_rendering is not supported by this implementation. This is required for correct operation.`) which is intentional and not a bug in Proton.

Please update your video driver to 510.47 or newer.
