### ISSUE TITLE
Merge Protonfixes into Proton

### ISSUE THREAD

**Issue by rokam** [ValveSoftware/Proton#5956]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Due to the variaty of solutions, it would be nice to have protonfixes merged inside proton, similar to protonge.

## Justification [optional] 
There are some games, like Squad and Fall Guys that need some file changes to run over proton. I think protonfixes is a great way to add out of the box support for those games.

## Risks [optional]
Some of the protonfixes and tweaks that make the game "better", but in some cases it might break the support. So I think that it needs a deep analysis of what should be merged and what can be defined user based through environment.

## References [optional] 
https://github.com/GloriousEggroll/protonfixes/pull/76
https://github.com/GloriousEggroll/protonfixes/pull/75
https://github.com/GloriousEggroll/protonfixes/pull/72

**Comment by kisak-valve** [comment]
Hello @rokam, this is a legally grey area that's not worth the risk.

**Comment by orowith2os** [comment]
Could this be considered again, but instead of including the full winetricks list, it uses the tricks that have been verified to be okay? This would remove the legality issues, I imagine, since it wouldn't include things like dotnet workarounds if those are found to be an issue (or aren't okayed).


This would also allow for some games to have their own specific fixes such as environment variables, not just for winetricks, I think.
