### ISSUE TITLE
Pathfinder: Kingmaker (640820)

### ISSUE THREAD

**Issue by alexpattyn** [ValveSoftware/Proton#5983]
#### Your system information

* Steam client version (build number or date): June 7, 2022
* Distribution (e.g. Ubuntu): Tested on Fedora 36 and Holoiso
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Steam crashes due to a core dump. This is reproducible on a NUC8i7HVK (Hades Canyon) and seems related to the RX Vega M. I expect a core dump doesn't take place. So far I have only seen this using steam. E.g. running [GtkStressTesting](https://flathub.org/apps/details/com.leinardi.gst) for 30mins with http://webglsamples.org/aquarium/aquarium.html doesn't lead to any crashes. 

#### Steps for reproducing this issue:

1. Install fedora 36 or Holoiso on a NUC8i7HVK
2. Install latest build of steam. 
3. Launch Pathfinder: Kingmaker (the game that I've been able to quickly reproduce this with).
4. See crash. 

#### Additional Info

[flatpak-output.txt](https://github.com/ValveSoftware/steam-for-linux/files/9080085/flatpak-output.txt)
[systemd-coredump.txt](https://github.com/ValveSoftware/steam-for-linux/files/9080086/systemd-coredump.txt)

See https://github.com/flathub/com.valvesoftware.Steam/issues/926

**Comment by kisak-valve** [comment]
Hello @alexpattyn, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

To me, this reads like either an Xwayland bug, or a video driver issue. That said, it wouldn't hurt to ponder this from Proton's side as well. Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Were you able to reproduce this issue with Flatpak out of the picture so that their maintainer can rule it out as a factor?

**Comment by alexpattyn** [comment]
Hi @kisak-valve I can supply those logs for you. I've been reproducing it across a couple of different configs. I can confirm that this occurs with the native package as well. Additionally it doesn't appear to be exclusive to Pathfinder: Kingmaker. For example I saw this on vampire survivors and valheim. Pathfinder is just the easiest to reproduce this crash with. 

I'll send this bug to Xwayland as well and see what they have to say.

**Comment by kisak-valve** [comment]
If you tested with the native Linux version of Valheim, then that removes Proton from the riddle and makes it more likely that your issue is somewhere in the render stack.

**Comment by alexpattyn** [comment]
So I am attaching the my steam info, but I wasn't able to get the game to produce a log using `PROTON_LOG=1 %command%`. Perhaps it crashes the entire system before the log can be made?

[steam-info.txt](https://github.com/ValveSoftware/Proton/files/9093268/steam-info.txt)

**Comment by alexpattyn** [comment]
Issue was resolved. It was a problem with a bad memory module and not the GPU. This was discovered via windows memory tool.
