### ISSUE TITLE
NTFS Compatibility

### ISSUE THREAD

**Issue by Alejandro9509** [ValveSoftware/Proton#6012]
Hi guys, a question

Does Proton currently support NTFS? Is there no identified problem with this file system?

As of version 5.15 of the Linux Kernel, there is supposed to be "full" NTFS support, but I'd like to make sure.

**Comment by kisak-valve** [comment]
Hello @Alejandro9509, Proton interacting with NTFS is known to be finicky, to the point the general recommendation is to use a linux native filesystem instead of it. There are several open issue reports already tracking this: https://github.com/ValveSoftware/Proton/search?q=ntfs+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues

Closing in favor of the older issue reports.
