### ISSUE TITLE
How to start games on ntfs3 partition

### ISSUE THREAD

**Issue by amekiri13** [ValveSoftware/Proton#6024]
I have add uid and gid when mounting NTFS partition, but I use ntfs3 (Linux Core) instead ntfs-3g
I found that Windows games cannot start on NTFS partition , but it can start when installed on Linux partition.

There are logs
````
(pressure-vessel-adverb:5201): pressure-vessel-WARNING **: Recovering by keeping our previous LD_LIBRARY_PATH
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: could not load kernel32.dll, status c000012f
pid 5239 != 5238, skipping destruction (fork without exec?)
Game process removed: AppID 783120 "/home/amekiri/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=783120 -- '/mnt/Ex-Data/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/mnt/Ex-Data/SteamLibrary/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/mnt/Ex-Data/SteamLibrary/steamapps/common/hello_lady/hello.exe'", ProcID 5130 
ThreadGetProcessExitCode: no such process 5238
ThreadGetProcessExitCode: no such process 5237
ThreadGetProcessExitCode: no such process 5236
ThreadGetProcessExitCode: no such process 5235
ThreadGetProcessExitCode: no such process 5234
ThreadGetProcessExitCode: no such process 5233
ThreadGetProcessExitCode: no such process 5133
ThreadGetProcessExitCode: no such process 5131
Uploaded AppInterfaceStats to Steam
````

There are my partition condition
![Partition Condition](https://user-images.githubusercontent.com/74164430/180455772-6e170597-d86c-4b57-8631-c425f5efe08a.png)

**Comment by kisak-valve** [comment]
Hello @amekiri13, Proton interacting with NTFS formatted partitions is known to be finicky, to the point that the general recommendation is to use a native linux filesystem instead of using NTFS. There's some community written workarounds suggested at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows#preventing-ntfs-read-errors which you might have luck trying.

For bug tracking purposes, there already is several open issue reports already tracking NTFS issues: https://github.com/ValveSoftware/Proton/search?q=ntfs+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues

Closing in favor of the older issue reports.
