### ISSUE TITLE
wine any command not working

### ISSUE THREAD

**Issue by suraj2315** [ValveSoftware/Proton#6097]
i on not able to run any wine command ;-;
i tried wineboot too but its says "wine: could not load kernel32.dll, status c0000135
"

please help me ;-; , i have to do some tasks that i got from my boss ;-;

btw , i am using kali linux latest version

**Comment by kisak-valve** [comment]
Hello @suraj2315, you've come across the Proton issue tracker, which is a downstream fork of wine which is used with Steam for Linux to run games intended for Windows.

Using Steam for Linux with Kali Linux is not supported here because it's contradictory to the fundamental goals of the distribution, which focuses on security testing and is not intended to be used as a general purpose desktop environment, and by extension, Proton is also not supported.

If you're using upstream wine, then report this issue to the upstream wine issue tracker at https://bugs.winehq.org/.

**Comment by suraj2315** [comment]
Thanks! I will sure report my issue on bugs. Winehq. Org/
