### ISSUE TITLE
The First Descendant (2074920)

### ISSUE THREAD

**Issue by NTMan** [ValveSoftware/Proton#6249]
# Compatibility Report
- Name of the game with compatibility issues: The First Descendant
- Steam AppID of the game: 2074920

## System Information
- GPU: AMD Radeon 6900XT
- Driver/LLVM version: [Mesa 22.3-git](https://gitlab.freedesktop.org/mesa/mesa/-/commit/1252d63cc2ecc398dd2d36b4a77a1af212cc6cb2)/15.0.0
- Kernel version: 6.1-rc1
- Link to full system information report as [gist](https://gist.github.com/NTMan/33cca4906328793206218192820779ec)
- Proton version: experimental-7.0-20221012

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-2074930.log](https://github.com/ValveSoftware/Proton/files/9827025/steam-2074930.log)

## Symptoms 
The game crashes with message "An Error has ocurred while loading imports. Wrong DLL present."
![Screenshot from 2022-10-20 11-28-33](https://user-images.githubusercontent.com/200750/196874863-986263cf-6af7-4958-ba63-f2e6acf27e19.png)

## Reproduction
Always.

**Comment by Pheoxy** [comment]
Can confirm.

![image](https://user-images.githubusercontent.com/6779172/196911036-b06d9eca-71ea-4456-9d46-5fc55a7d1450.png)

Same issue, https://github.com/ValveSoftware/Proton/issues/6245

**Comment by kisak-valve** [comment]
Hello @NTMan, your Proton log confirms that you're testing the Steam Beta variant of this game (appid ending in 30 instead of 20) instead of the main game release, and we already have a compatibility report tracking that variant of the game at #6245. I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/6245#issuecomment-1285497855.
