### ISSUE TITLE
Remote play will be stuck on Custom PC

### ISSUE THREAD

**Issue by yxding95** [ValveSoftware/Proton#6293]
# Compatibility Report
- Name of the game with compatibility issues: Battlefield™ 1
- Steam AppID of the game: 1238840

## System Information
- GPU:  GTX 1070
- Driver/LLVM version: nvidia 515.76
- Kernel version: 5.15.0-52-generic
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DDbang/e3fbefbf5af7d56d572abeaf24ab43b1
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

The log is still too big after compress...

## Symptoms 
The game is able to start on the Host PC (Ubuntu 22.04 System). But when I start remote play on my laptop (Win10 System), the video display will be stuck before the game start, but there are game sounds and the cursor, also a slow network warning icon on the page. It is ok for SteamLink on a mobile phone. So it seems the problem is about the streaming on PC.

**Comment by kisak-valve** [comment]
Hello @DDbang, since Linux host + Proton to Steam Link Android client works, that makes your issue an issue with the client side of Remote Play with Steam for Windows instead of an issue with Proton. Report this issue to [Steam Support](https://help.steampowered.com/en/) for the main Steam team to take a look.

Closing as out of scope for the Proton project.
