### ISSUE TITLE
Fallout 2 (38410)

### ISSUE THREAD

**Issue by K1ngst0m** [ValveSoftware/Proton#6296]
# Compatibility Report
- Name of the game with compatibility issues: Fallout 1 and 2
- Steam AppID of the game: 38400, 38410

## System Information
- GPU: amd ryzen 5700g apu
- Driver/LLVM version: Mesa 22.2.2 renoir, LLVM 15.0.3, DRM 3.48
- Kernel version: 6.0.5
- Link to full system information report as [Gist](https://gist.github.com/):
https://gist.github.com/K1ngst0m/a7128b27193e3da548ec9a199171cc0c
- Proton version: 7.0-4

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## system info and proton run log:

https://gist.github.com/K1ngst0m/a7128b27193e3da548ec9a199171cc0c

## Reproduction

1. open the steam client
2. run fallout or fallout 2
3. game execution failed and popup an error window:

![image](https://user-images.githubusercontent.com/34272057/200154347-51a9d315-725c-4b9a-9a16-152d6393913f.png)

**Comment by kisak-valve** [comment]
Hello @K1ngst0m, let's use this compatibility report to focus on Fallout 2.

Looking at your system information, you have AMDVLK and AMDGPU-Pro installed, which might be irrelevant since it appears this is a DirectX 7 game rendering through wined3d to OpenGL, but I'm also seeing d3d9.dll getting loaded in the Proton log with no hints that DXVK is starting up.

Setting that aside, `err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.` might be a line of interest in the Proton log as a weak hint.

It's unclear if this is a regression from the older feedback for this game or AMD APU specific behavior. Can you check how the game behaves with a couple older releases of Proton? Also, there's a chance this might be bspwm specific behavior. It would be nice to know if the same issue happens with a more common desktop environment.

**Comment by Blisto91** [comment]
Fallout 2 is originally not a d3d9 game but the gog and steam version includes some extra fixes and modifications to make it run better on modern system, d3d9 support being one of them https://www.pcgamingwiki.com/wiki/Fallout_2#sfall

I will try to check it out.

**Comment by kisak-valve** [comment]
If the game is taking a D3D9 render path, then it would be interesting for @K1ngst0m to see if running the game with mesa/RADV instead of AMDVLK or AMDGPU-Pro helps.

**Comment by K1ngst0m** [comment]
> If the game is taking a D3D9 render path, then it would be interesting for @K1ngst0m to see if running the game with mesa/RADV instead of AMDVLK or AMDGPU-Pro helps.

I tried the following version of the proton: exp, 7.0-4, 6.3-8, 5.13-6.

they all show the same output.

**Comment by Blisto91** [comment]
I have played the DirectX 9 mode with both proton 7.0-4 and experimental and haven't encountered any issues getting the game to run. This is with a AMD R9 380 and mesa (radv) newish git version.

**Comment by kasha695** [comment]
I've seen this error before when the game can't detect a valid screen resolution.

I was testing on the Deck and I think this error would show up in both Desktop mode and in Gaming mode if I had toggled on the Scaling x2 option in the config executable. You could try changing to Window mode, or disable scaling x2 and see if that makes any difference?

**Comment by K1ngst0m** [comment]
This is solved by changing my WM from bspwm to qtile. I guess that the previous WM's window control logic has some issues with this game.
