### ISSUE TITLE
Rogue Heroes: Ruins of Tasos does not run

### ISSUE THREAD

**Issue by junefish** [ValveSoftware/Proton#6363]
# Compatibility Report
- Name of the game with compatibility issues: Rogue Heroes: Ruins of Tasos
- Steam AppID of the game: 787810

## System Information
- GPU:  Quadro P1000
- Driver/LLVM version:  nvidia 510.85.02
- Kernel version:  5.18.16-testing-amd64
- [Link to full system information report as Gist](https://gist.github.com/junefish/289ec4b118ec78af7adeda0ed97a3129)
- Proton version: Experimental / 7.0-5 / 7.0-4 / 6.3-8

## I confirm:
- [ X] that I haven't found an existing compatibility report for this game.
- [ X] that I have checked whether there are updates for my system available.

 Have added to the launch options but no log file is being generated
![Screenshot](https://user-images.githubusercontent.com/19216250/205713219-79e1911c-d33d-4ca0-b679-0b746353beaf.png)

## Symptoms 

Game does not launch (button switches to "Stop" for about a second and then back to "Play" with no window opening)

## Reproduction
- open game properties
- set Compatibility > Proton Version to [Experimental / 7.0-5 / 7.0-4 / 6.3-8)
- close properties
- click "play"

**Comment by kisak-valve** [comment]
Hello @junefish, your issue is with the Steam Linux Runtime - Soldier container environment and Pressure Vessel which sets up that container. It comes down to your home folder being a subdirectory of /usr/local, and there's a note at https://github.com/ValveSoftware/steam-runtime/blob/60f438709eff5ccb7a6fc5c609ae832d58edbe42/doc/steamlinuxruntime-known-issues.md#usrlocal that this is a known incompatible folder location.

This is not a game-specific issue, or a Proton issue. It is not something that can be sanely solved besides relocating your home folder, but there is a workaround suggested in https://github.com/ValveSoftware/steam-runtime/issues/288.

**Comment by junefish** [comment]
That's weird, because other games run fine with Proton (e.g. Among Us, Wingspan), but I will take your word for it!

Following [this comment](https://github.com/ValveSoftware/steam-runtime/issues/288#issuecomment-717207328_), I ran `mount --bind /usr/local/home/junefish/.local/share/Steam /data/games`.  Now if I `ls /data/games` I see the contents of my steam folder.

I then tried running Rogue Heroes again and it downloaded some updates before once again not opening.  Should I try fully relocating my Steam library?  Or is it the Steam installation that's the problem?

Thanks!
