### ISSUE TITLE
Proton Experimental stopped working after today's update of it

### ISSUE THREAD

**Issue by Git-Forked** [ValveSoftware/Proton#6416]
# Compatibility Report
- Name of the game with compatibility issues:  Asphalt 9
- Steam AppID of the game: 1815780
https://store.steampowered.com/app/1815780/Asphalt_9_Legends/

## System Information

```
OS: Manjaro Linux x86_64 
Host: HP EliteDesk 800 G1 SFF 
Kernel: 6.1.1-1-MANJARO 
DE: Plasma 5.26.4 
WM: KWin 
CPU: Intel i5-4590 (4) @ 3.700GHz 
GPU: Intel HD Graphics 
Memory: 3751MiB / 15912MiB 

Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
    driver: i915 v: kernel
  Display: x11 server: X.Org v: 21.1.6 with: Xwayland v: 22.1.7 driver: X:
    loaded: modesetting dri: crocus gpu: i915 resolution: 1: 1920x1080~60Hz
    2: 1280x1024~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.1 renderer: Mesa Intel HD Graphics 4600 (HSW
    GT2)
```
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Using Proton Experimental, it was updated today, 12/27/22.
Since this update Asphalt 9 will no longer launch. 
The screen goes black like it tries to load, but then nothing loads, and the [stop] button becomes [play] again.
I have been playing the game for almost a year with this same setup and it has always worked until today.
I don't play any other games that require Proton, so I can't test other games. 
I run Manjaro Linux.  Manjaro is a rolling release with all updates current.

[steam-1815780.log](https://github.com/ValveSoftware/Proton/files/10311058/steam-1815780.log)

**Comment by kisak-valve** [comment]
Hello @Git-Forked, please copy the compatibility report template from https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md to here, and fill out the requested details.

**Comment by ClumsyDerp** [comment]
Have you found a solution yet?

I'm affected by a similiar problem that seems to have come out nowhere and may be closely related.

I've checked your logs and one particular line resembles the problems I am having.

> err:   D3D11CreateDevice: No default adapter available

In your case it seems your system thinks it has no default GPU?

In my case all proton games fail to launch (Lutris do though and natives through steam as well) with something aching to

> err:   D3D11CoreCreateDevice: Failed to create D3D11 device

My Steam/Proton will not recognize my GPU at all it seems. Games that do not outright crash tell me that I have no compatible direct x  GPU device. The system recognizes the GPU and Steam as well, though, using Help -> System Info.

All titles that now crash on me (literally any proton game) worked just splendidly at some point in time. Affected titles: Hitman 3, Forza 5, Elex II, Elden Ring, Songs of Conquest, Civ 6. 

As I've been on my Deck for past few weeks/months I can't tell when exactly things started turning bad.

I am on a fully up-to-date EndeavourOS, tied various older proton versions and am a bit lost, too.

6900XT with RadV json override active and everything up to date.

**Comment by kisak-valve** [comment]
Hello @Git-Forked, it looks like your edits fell trough the cracks, sorry for the delay. There's a couple significant details here:

First and most significant, your system uses Haswell generation Intel graphics. The Vulkan drivers for this generation are not spec compliant. Unfortunately, that means that Proton can not support your system in general.

Second, what Vulkan support is available in the mesa/ANV video driver got split from newer Intel chips and you're now using mesa/hasvk. Along with this split, the video driver went from claiming support for Vulkan 1.3 to 1.2 (https://gitlab.freedesktop.org/mesa/mesa/-/issues/7827#note_1672395). The builds of DXVK and VKD3D-Proton in Proton Experimental requires Vulkan 1.3 support.

This leads to the Vulkan driver to not meet the requirements DXVK needs to run. From your Proton log:
```
warn:  Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 4600 (HSW GT2)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
err:   D3D11CreateDevice: No default adapter available
```

You should be able to use Proton 7.0, which has a DXVK version that requires less features from the video driver.

Hello @ClumsyDerp, your issue is unrelated.
