### ISSUE TITLE
Stuck In Time (1814010)

### ISSUE THREAD

**Issue by pinekiller** [ValveSoftware/Proton#6419]
# Compatibility Report
- Name of the game with compatibility issues: Stuck In Time
- Steam AppID of the game: 1814010

## System Information
- GPU: AMD Radeon r9 290
- Driver/LLVM version: Mesa 22.0.5 /  LLVM 13.0.1
- Kernel version: 5.15.0-56-generic
- Link to full system information report as [Gist](https://gist.github.com/): [System Info](https://gist.github.com/pinekiller/cc80309181fd23988b3c60b6c8b06bcb)
- Proton version: 1671481081 experimental-7.0-20221219

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When the game is lunched it generates this error message:

> Win32 function failed: HRESULT: 0x887a0002 
>
> Call:  at line 232 in file \Graphics_DisplayM.cpp

The game works fine when using proton 7.0-5

## Reproduction
Launch the game 

[steam-1814010.log](https://github.com/ValveSoftware/Proton/files/10322167/steam-1814010.log)

**Comment by kisak-valve** [comment]
Hello @pinekiller, `warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.` `err:   D3D11CreateDevice: No default adapter available` from your Proton log and https://gist.github.com/pinekiller/cc80309181fd23988b3c60b6c8b06bcb#file-system-report-L172-L195 from your system log are the key details here.

By default, the linux kernel uses the `radeon` kernel module with your Sea Islands (CIK) generation video card, but the `radeon` kernel module is not compatible with Vulkan. Please give https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games a read.

I suspect that the game was running with lavapipe to render on your CPU instead of using your video card with Proton 7.0-5.

**Comment by pinekiller** [comment]
following the instructions in [https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games ]( https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games ) solved the issue.

thanks for the help.
