### ISSUE TITLE
[Question] Origin of the name

### ISSUE THREAD

**Issue by ArekPiekarz** [ValveSoftware/Proton#642]
I am curious if you could tell us where the name Steam Proton came from?

It's unusual in the scheme of other Valve products, which were either named as plays on words, like Steam Cloud, Steam Machine, or more direct references to their underlying functionality - i.e. Steam Play, Steam Audio. However I don't know how to fit Steam Proton to either of these categories or find a reference to Wine.

The only explanation I can come up with is you wanted to make a positive change in Linux ecosystem, just like a proton is a particle with a positive charge. Did I guess correctly? :-)

Edit: I realized it's actually called Proton, not Steam Proton.

**Comment by aeikum** [comment]
We've been working on this for a long time. We needed an internal codename we could use that wouldn't tip our hand if it leaked (so Wine puns are out), and that we wouldn't be embarrassed to continue using after release (sorry, BadgerBadgerBadger). A bunch of ideas were tossed around the CodeWeavers office one afternoon, and I ended up picking Proton because it's short, easy to remember, sounds cool, and is hard to Google for.

Although, I like your explanation too :)

**Comment by NoXPhasma** [comment]
And I thought it was a pun in direction of Electron framework, since that makes web applications cross platform available on the desktop ;)

**Comment by KayKay91** [comment]
I've always had a though that the idea for that name came from one of Iron Man's super moves in Marvel vs Capcom called Proton Cannon (Which somewhat became a meme).
