### ISSUE TITLE
Proton update 7.0

### ISSUE THREAD

**Issue by DashCourageous** [ValveSoftware/Proton#6511]
Proton update caused all my steam games to crash and not load. To remedy the issue I had to uninstall the update. This needs to be looked at to address this issue.

**Comment by Blisto91** [comment]
Hello.

For a game that crashes please add [PROTON_LOG=1 %command%](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file.  Also, please copy your system information from Steam (Steam -> Help -> System Information) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by fabrijustiniano19** [comment]
@Blisto91 I think the issue I'm having with Sims 4 might be related to this. I'm not sure if it is because of the last proton update or the last game update, but it doesn't happen with other games even ones who use the EA app launcher like FIFA 22 work just fine. The sims 4 just crashes before launch for me now.

Gist: https://gist.github.com/maplehobo/aae4f6e33e389d4348b18733cc54b858

Proton Log: [steam-1222670.log](https://github.com/ValveSoftware/Proton/files/10711281/steam-1222670.log)

**Comment by kisak-valve** [comment]
Hello @maplehobo, please post that feedback on the game-specific compatibility report (#4174).

**Comment by robotman40** [comment]
> @Blisto91 I think the issue I'm having with Sims 4 might be related to this. I'm not sure if it is because of the last proton update or the last game update, but it doesn't happen with other games even ones who use the EA app launcher like FIFA 22 work just fine. The sims 4 just crashes before launch for me now.
> 
> Gist: https://gist.github.com/maplehobo/aae4f6e33e389d4348b18733cc54b858
> 
> Proton Log: [steam-1222670.log](https://github.com/ValveSoftware/Proton/files/10711281/steam-1222670.log)

I am getting the exact same issue at this time of speaking

**Comment by kisak-valve** [comment]
Closing do to a lack of actionable information.
