### ISSUE TITLE
EA APP doesn't start after last proton experimental update

### ISSUE THREAD

**Issue by thegabriele97** [ValveSoftware/Proton#6617]
# Compatibility Report
- Name of the game with compatibility issues: EA APP
- Steam AppID of the game:

## System Information
- GPU: RTX 3060 TI
- Driver/LLVM version: nvidia 525
- Kernel version: 6.11
- Proton version: Experimental

## Symptoms 

After the most recent Proton Experimental Update, the EA App doesn't start anymore, presenting a black screen.

## Reproduction
- Open EA App via Steam with Proton Experimental
- Login
- After the login, a black rectangle draws on top of the login window and it is impossibile to do anything

![image](https://user-images.githubusercontent.com/35406071/225096775-906197e0-1514-4243-8c01-f05926a6e7ce.png)

**Comment by stixholder** [comment]
EA APP starts and seems to work with Proton 8.0-2 at first. But after downloading a game from the library, it's not possible to run it. As I remember, I required Experimental to install EA APP as external program at first and needed to switch to 8.0-2 afterwards.

When switching to Proton 7.0-6 (which seems to be the only working stable version for Ubisoft games), the APP window UI will render as black (with invisible buttons clickable), which is useless, as is 8.0-2 ultimately, since EA games like Crysis 3 won't start with it. 

After switching back to 8.0-2, the downloaded and "installed" EA game is then vanished from EA APP, and stays so, even after switching back to 8.0-2. 

In addition, the Steam client will grey out and block the Proton version drop down box, once EA APP (or any externally installed game/program for that matter) was launched, until Steam was completely closed and restarted.
