### ISSUE TITLE
Mesa 23 crashes (Unity) games for Radeon

### ISSUE THREAD

**Issue by Jens14L** [ValveSoftware/Proton#6654]
# Compatibility Report
- Names of the games with compatibility issues: _Yu-Gi-Oh! Duel Links_ and _Yu-Gi-Oh! Master Duel_ (Unity-based games)
- Steam App-IDs of the games: 601510 and 1449850

## System Information
- GPU: AMD/ATI Mobility Radeon HD 3670
- Driver/LLVM version: Mesa AMD RV635 (DRM 2.50.0 / 6.2.8-arch1-1, LLVM 15.0.7), 3.0 Mesa 23.0.0
- Kernel version: 6.2.8-arch1-1
- [Link to full system information report](https://gist.github.com/Jens14L/fed3e161834fbd1b48617bc856fa4dc6)
- Proton versions: Experimental, 7.0-6 or 6.3-8

## I confirm:
- [x] that I haven’t found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms
Both games crash after the start and the Unity crash handler is executed.

## Reproduction
1. Update from Mesa und Vulkan-Radeon from 22.x (22.3.6) to 23.x (23.0.0 or 23.0.1). (Downgrading back to 22.3.6 fixed all issues.)
2. Open Steam, use the start option `PROTON_USE_WINED3D=1 %command%` and force the use of Proton.
3. Start the games.

## Logs
[steam-601510.log](https://github.com/ValveSoftware/Proton/files/11094639/steam-601510.log)
[steam-1449850.log](https://github.com/ValveSoftware/Proton/files/11094640/steam-1449850.log)

**Comment by kisak-valve** [comment]
Hello @Jens14L, sorry, but all Terascale hardware does not support Vulkan, and the `PROTON_USE_WINED3D` runtime option is also not considered supported which makes your system unsupportable in general. For this issue to be evaluated on the game side, then you need to reproduce the issue with vanilla wine and report it to the upstream wine project.

That said, you've identified that your issue is a video driver regression and you should report that issue to your video driver vendor first.
