### ISSUE TITLE
Extremely low fps in Cyberpunk 2077 and Elden Ring

### ISSUE THREAD

**Issue by SashaCanfield03** [ValveSoftware/Proton#6683]
I am using Ubuntu with an rx7900xtx (unique setup), a core i7 10700, and the 6.2.10-x64v4-xanmod1 kernel, using KDE as my desktop environment.

In Elden Ring, and also Cyberpunk 2077, I get what feels like less than 5 fps even on the lowest graphics settings. I don't care as much about getting Cyberpunk 2077 fixed because I got it on sale to test out the new graphics, and I can boot into Windows the few times I want to play it. However, I actually wanted to play Elden Ring.

When I run it, eldenring.exe takes a little over 50% of my cpu, and checking the cores, I see that several of them are at almost 100% utilization. It was only using 4.2 gigs of my ram though (lowest settings). However, it runs fine in the menus. In Cyberpunk it lags through the entire opening sequence while launching the game, and through all the menus too.

Let me know what I should do to get more information to solve the problem! I bet there's a lot of commands to figure out what drivers I'm using, maybe run Cyberpunk in the command line, stuff like that. I won't be able to test it in Elden Ring though, since I am getting a refund.

**Comment by kisak-valve** [comment]
Hello @pjc5712, in general, performance issues need to be evaluated on a per game basis, and we're using one issue report per unofficially supported game title. Since you've removed Elden Ring as a test case, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-1508788342.
