### ISSUE TITLE
vkd3d crashes Deep Rock Galactic and Katana Zero

### ISSUE THREAD

**Issue by ardishko** [ValveSoftware/Proton#6836]
# Compatibility Report
- Name of the game with compatibility issues:
Deep Rock Galactic & Katana Zero
- Steam AppID of the game:
DRG: 548430
Katana Zero: 460950
## System Information
- GPU AMD Radeon 6900 XT
- Driver/LLVM version: Mesa 23.1.1-1
- Kernel version: Linux Arch 6.3.6
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ardishco-the-great/ee53981803700f28a433d969a24c1d2f
- Proton version:(8.0-2)

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptoms 

Deep Rock Galactic, Katana Zero and some other games crash and/or hang (when looking at the logs when the game hangs, nothing seems wrong, so it might be a WM issue) on Proton 8.0-2 and higher. I am not able to attach a Katana Zero log because after running it for 10 seconds I generated a 700mb file which is way too big for me to distribute but If it would be helpful, then I would be happy to provide it one way or the other.

**Keep in mind that the reason I am not submitting 2 separate bug reports is because it is related to the same thing on both games (vkd3d-proton)**

The error seems related to the new vkd3d implementation, as you can see in the log.

## Reproduction

For DRG:

1 - Launch Deep Rock Galactic
2 - Get past info screen
3 - Wait
4 - After a few seconds, the game will crash

For Katana Zero
1 - Launch game
2 - See start card for a second
3 - The game will crash right after that.
(For some reason, this generates a huge log file)

Proton logfile for DRG: https://n0paste.tk/Jea1qoK/

**Comment by kisak-valve** [comment]
Hello @ardishco-the-great, you've indicated that there's a common error, but also that you couldn't find a common hint to ponder. This makes it difficult to evaluate if there's a single issue or multiple issues with coincidental symptoms. If you're confident that the issue is scoped to VKD3D-Proton, then that should be reported upstream (https://github.com/HansKristian-Work/vkd3d-proton).

Setting that aside, please copy the output of `Steam Runtime Diagnostics` from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, if this a regression, please clearly indicate the newest Proton version you know is unaffected with the games.

**Comment by mbriar** [comment]
I don't see anything in the log that indicates that it's a problem with vkd3d-proton. Certainly for Katana Zero it won't be, because this game doesn't use d3d12 at all.

**Comment by kisak-valve** [comment]
Thanks for the note @mbriar. Since that scopes the usable feedback here to Deep Rock Galactic, and we're using one issue report per unofficially supported game title, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/284#issuecomment-1584614097.

It looks like there currently isn't an open compatibility report for Katana Zero, so please open a new compatibility report with your findings for that game.
