### ISSUE TITLE
Proton Refuses to see my new GPU

### ISSUE THREAD

**Issue by Alecr87** [ValveSoftware/Proton#6846]
I upgraded my GPU. Changed an old GT710 Nvidia card with Fermi to a new brand Radeon RX 6600.

Happy I have AMD to use MESA, Steam refuses to launch any windows game with version of proton beyond 5.0.1 version.

It seems proton is stuck believing Im still with the old card. I can launch DX9 games with Proton 4.13 and 5.0.1.

I purge any nvidia drivers on my system. I installed Kisak repository and updated to the latest MESA driver there. I deleted the cache of Steam. I can launch native games.
Steam info reports my card properly. Launching the games from Steams reports nothing back. No proton log too at all.
DX9 games refuses to work with newer versions of Proton.

I dont want to reinstall Steam again and do the painful process of reinstalling all the games. 

Please help!!
This is the Steam System Info Report.
https://gist.github.com/Alecr87/123a741a6c9c4314405a7e501e823645

**Comment by kisak-valve** [comment]
Hello @Alecr87, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. If you're using the Steam client beta, then please also include `Steam Runtime Diagnostics`.

It should be noted that Proton does not generate logs by default because there can be a performance and disk usage concerns related to them. Please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to a couple game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)

**Comment by kisak-valve** [comment]
Thanks, looking through your system information, https://gist.github.com/Alecr87/123a741a6c9c4314405a7e501e823645#file-gistfile1-txt-L1505 is the key detail. The leftovers of the 390 series NVIDIA driver install has caused you to encounter https://github.com/ValveSoftware/steam-runtime/issues/420.

The 390 series NVIDIA driver is older than the support cutoff for Proton in general, and your best option is to purge that driver version since you're no longer using the hardware anyway.

Closing in favor of https://github.com/ValveSoftware/steam-runtime/issues/420.

**Comment by Alecr87** [comment]
Added the data generated by the Steam System Info to the original message.
Then It seems the purge command didnt work as expected.
