### ISSUE TITLE
Proton 8.0 doesn't work with nvidia 470 driver

### ISSUE THREAD

**Issue by hmyzna** [ValveSoftware/Proton#6865]
I tried playing Scrap Mechanic, Blockade3D, The Hunter: Call of the Wild using proton 8.0 and experimental from Valve (i also tried ProtonGE, didn't work). Proton 7.0 works fine
My GPU is GTX 650 and I am running void linux and fedora (happens on both) with nvidia proprietary driver 470.182.03
![image](https://github.com/ValveSoftware/Proton/assets/55652142/a1554d4d-2780-4179-99c8-9a76e469d40f)

[steam-1049800.log](https://github.com/ValveSoftware/Proton/files/11834089/steam-1049800.log)

**Comment by awesqm** [comment]
If that helps, ProtonGE 7-26 is the latest ProtonGE version that works. (I know it's not affiliated with Valve's proton, but I thought it may be helpful?)

**Comment by hmyzna** [comment]
oops closed by accident

**Comment by hmyzna** [comment]
Also, ProtonGE 7-26 is the latest ProtonGE that works (I know it's not affiliated with Valve's Proton, but I thought it may be helpful)

**Comment by kisak-valve** [comment]
Hello @awesqm, noted in Proton 8.0's [release notes](https://github.com/ValveSoftware/Proton/releases/tag/proton-8.0-1c), the builds of DXVK and VKD3D-Proton in Proton 8.0 and newer requires Vulkan 1.3. The NVIDIA 470 series video driver provides support for Vulkan 1.2.

Sorry, but this is the expected outcome because the video driver doesn't provide enough features to continue support.
