### ISSUE TITLE
[Manjaro Linux] After update any games cant launch. Only invisible window with game sound

### ISSUE THREAD

**Issue by antonTroyan** [ValveSoftware/Proton#6919]
I posted this issue [old issue](https://github.com/ValveSoftware/Proton/issues/6830 )
It was marked as duplicate [same bug, but on arch](https://github.com/ValveSoftware/Proton/issues/6760) that is solved because arch linux was updated to Mutter 44.2. But manjaro linux isnt.
That`s why any game that is not native for linux havent work second month already. Can it be fixed?

**Comment by kisak-valve** [comment]
Hello @antonTroyan, if Manjaro is shipping a known quirky version of mutter, that has to be resolved by Manjaro's package maintainers, not Proton. Report this issue to your distro's package maintainer(s) for GNOME.

Closing because this issue has already been evaluated as not-a-Proton issue on #6760.
