### ISSUE TITLE
[Request] Valorant anticheat's (Vanguard's) kernel driver (`vgk.sys`) and later the anticheat as a whole

### ISSUE THREAD

**Issue by m1karii** [ValveSoftware/Proton#6966]
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
I'd like - if it 'd be possible - for you to make Valorant anticheat's kernel driver (`vgk.sys`) and later the anticheat as a whole runnable through proton

## Justification [optional] 
This would enable running of Valorant, the game itself

**Comment by kisak-valve** [comment]
Hello @m1karii, in general, no game on Steam should require superuser access to run on Linux, and that's exactly what you're requesting in this feature request.

It looks like this game isn't distributed on Steam, so that makes this request something that would make more sense for the upstream wine devs to ponder instead of Proton devs.

**Comment by m1karii** [comment]
Hi @kisak-valve, could you please explain why would Vanguard AC require superuser access to run on Linux?
As far as I understand - and my understanding is quite limited - other ACs (for e.g. Easy AC) also have kernel acces. In what does Vanguard differ from these other ACs?
