### ISSUE TITLE
Issues launching many Windows games through Proton

### ISSUE THREAD

**Issue by xxkfqz** [ValveSoftware/Proton#6982]
# Compatibility Report

## System Information
- GPU: AMD Radeon RX 5500XT
- Video driver version: Mesa 23.1.4
- Kernel version: 6.4.7-gentoo
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/xxkfqz/296e8bc5c3b02db04140758b874e38da
- Proton version: Experimental, 8.0-3, 7.0-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Proton Experimental (also 8.0-3 and 7.0-6) stopped launching many Windows games like BattleBit, SuperPower 2, Wings of Vi but runs Quake.

`PROTON_LOG=1 %command%` outputs:
- [BattleBit Remastered](https://gist.github.com/xxkfqz/32f0970901131bf12427d64d1d77af43)
- [SuperPower 2 log](https://gist.github.com/xxkfqz/c4e584105bd2004bfb9ef834cef155c9)
- [Wings of Vi log](https://gist.github.com/xxkfqz/8bbc563722bb790bb9bee31f6bc7e5b4)

[vulkaninfo](https://gist.github.com/xxkfqz/e99ddc10a9dcf6ebbf4b1b73ccd4eeea)

## Reproduction

1. Enable Steam Play
2. Select "Proton Experimental"
3. Launch Windows game

**Comment by kisak-valve** [comment]
Hello @xxkfqz, it looks like your system is configured to use AMDGPU-Pro. Can you test how these games behave with mesa/RADV? Also, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by xxkfqz** [comment]
@kisak-valve [Steam Runtime Diagnostics](https://gist.github.com/xxkfqz/d0d5bf178a81ac14ab0b18b640c974ea)

**Comment by ipr** [comment]
Steam client seems to have a random issue. Closing the client and starting it again (without rebooting) seems to solve it sometimes.

For me this appears after computer has been rebooted (which doesn't happen often). Restarting Steam seems to fix whatever it is.

**Comment by xxkfqz** [comment]
@kisak-valve Yep, removing AMDGPU-Pro drivers makes all games run again

**Comment by kisak-valve** [comment]
Looking over the diagnostics information, looks like VK_ICD_FILENAMES was forcing the Vulkan loader to only try a single option, and since that didn't exist it broke all Vulkan render paths.
Set variable: https://gist.github.com/xxkfqz/d0d5bf178a81ac14ab0b18b640c974ea#file-runtime-diag-L62
Driver ICD does not exist: https://gist.github.com/xxkfqz/d0d5bf178a81ac14ab0b18b640c974ea#file-runtime-diag-L328-L337
Broken 32 bit Vulkan: https://gist.github.com/xxkfqz/d0d5bf178a81ac14ab0b18b640c974ea#file-runtime-diag-L77-L90
Broken 64 bit Vulkan: https://gist.github.com/xxkfqz/d0d5bf178a81ac14ab0b18b640c974ea#file-runtime-diag-L189-L202
