### ISSUE TITLE
dear god almighty, there needs to be UX for fossilize_replay eating my CPU

### ISSUE THREAD

**Issue by colemickens** [ValveSoftware/Proton#7000]
Sorry if this is the wrong place for this but I don't know **what on Earth** fozzilize-replay is, but if Valve/Steam/Proton folks had any sense, there would be some sort of an explanation for this process that seems to eat 17-20% of my CPU when I just happen to have Steam open. Even for a full on hour.

**Comment by colemickens** [comment]
Baffling too, I sat here and listening to it ramp my laptop fans, eat my CPU, and the second I restart Steam it disappears and hasn't come back.

Not great. not great.

**Comment by colemickens** [comment]
This isn't okay.
![screenshot-1691578396](https://github.com/ValveSoftware/Proton/assets/327028/40851360-e13c-4519-8c4d-0a9a45a7e92e)

**Comment by kisak-valve** [comment]
Hello @colemickens, fossilize_replay (https://github.com/ValveSoftware/Fossilize) takes a collection of hardware independent shaders and runs it through your video driver so that the video driver's on-disk shader cache has been warmed up from seeing those shaders in advance. The general purpose is to reduce stutter from compiling shaders on demand in the middle of gameplay.

This is managed by Steam, not Proton, and you have control over this behavior of Steam at `Steam` -> `Settings` -> `Downloads` -> `Allow background processing of Vulkan shaders`. That tells Steam if it's allowed to work ahead when there isn't a game running.

Closing as not a Proton issue.

Related: https://github.com/ValveSoftware/steam-for-linux/issues/9405

**Comment by colemickens** [comment]
That's a very detailed, kind, helpful answer. Thank you so much @kisak-valve :).
