### ISSUE TITLE
Proton crashes on games installed on ntfs

### ISSUE THREAD

**Issue by PlayerXYT** [ValveSoftware/Proton#7143]
# Compatibility Report
- Name of the game with compatibility issues: Cult of the lamb is used as an example, this affects all proton games
- Steam AppID of the game: 1313140

## System Information
- GPU: RTX 3080Ti
- Video driver version: nvidia 535.113.01-2
- Kernel version: 6.5.5.arch1-1
- Link to full system information report as [Gist](https://gist.github.com/PlayerXYT/7a90882aec599408d6a51400e7eb3003)
- Proton version: 8, experimental, and hotfix

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms
Proton games crash on startup due to "not having ownership"

## Reproduction

Attach a drive or partition your existing drive
Format the drive to ntfs
Mount the drive
Download and install a steam game to that drive
Enable proton compatibility via the steam settings
Play the game, it will crash
Running steam from the command line will throw this error:
`wine: '/run/media/playerxyt/DATA/SteamLibrary/steamapps/compatdata/1313140/pfx' is not owned by you`
The pfx file has 777 permission but is owned by root (due to fstab)
`drwxrwxrwx 1 root root   4096 Mar  9  2023 pfx`
`chown` Will not work because it is not supported in ntfs
Reinstall the game to a linux file system (ext4 in root in my case)
The game will run perfectly

**Comment by kisak-valve** [comment]
Hello @PlayerXYT, there's several issues with Proton interacting with NTFS already (https://github.com/search?q=repo%3AValveSoftware%2FProton+NTFS+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues&state=open), which makes it quirky enough that the general recommendation is to use a Linux native filesystem with Proton instead of NTFS.

Wine requires that the wineprefix folder must be owned by the current user that is running it to prevent an entire category of hard to diagnose issues. Proton inherits this behavior. This specific issue is already being tracked at https://github.com/ValveSoftware/Proton/issues/4820.

Closing in favor of the older issue reports.

**Comment by aquib-sh** [comment]
Hello, I recently go into this issue as well on my NTFS drive while I was sharing a game between Windows and Linux

I was able to fix the issue by remounting the drive with appropriate permissions. 

Please follow this article: https://aquib.sh/2025/05/fix-for-pfx-not-owned-by-you.html
