### ISSUE TITLE
more than 8 axis breaks proton

### ISSUE THREAD

**Issue by MNS26** [ValveSoftware/Proton#7252]
proton version: tested with 6.3 and newer 
wine version: 

testing RP2040 with 8 axis
![image](https://github.com/ValveSoftware/Proton/assets/53867268/e4c5d7aa-3694-4b07-bb2d-aa0516b2f31b)

RP2040 with 9 axis
![image](https://github.com/ValveSoftware/Proton/assets/53867268/31d7e7de-1795-428a-8601-f657172fd053)

i have had this issue with my X52 pro as well but didnt know how to debug it

`bekopharm` made the folowing issue 
[Thumbstick on HOTAS X52 (Pro) does trigger all kinds of buttons pressed](https://github.com/ValveSoftware/Proton/issues/6537)

also made a report on wineHQ about this
https://bugs.winehq.org/show_bug.cgi?id=55660

**Comment by MNS26** [comment]
i just got a patch from `Rémi Bernon` over on wineHQ [bus_sdl.c patch](https://bugs.winehq.org/attachment.cgi?id=75417&action=diff&context=patch&collapsed=&headers=1&format=raw) (cant send file directly since its not supported)

**Comment by kisak-valve** [comment]
Hello @MNS26, fragmenting the discussion of an issue across multiple issue reports is counterproductive. Since this issue report added a little more detail, I have transferred it to https://github.com/ValveSoftware/Proton/issues/6537#issuecomment-1806885326.

Closing in favor of the older issue report.
