### ISSUE TITLE
Apex Legends I get into the game and try to log-in it wont work

### ISSUE THREAD

**Issue by GentBinaku** [ValveSoftware/Proton#7257]
# Compatibility Report
- Apex Legends
- 1172470
--

<br class="Apple-interchange-newline">

## System Information
- GPU: GTX 3060
- Video driver version: Mesa llvmpipe (LLVM 15.0.7, 256 bits)
- Kernel version: 6.2.0-36-generic
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Experimental

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[steam-1172470.log](https://github.com/ValveSoftware/Proton/files/13342315/steam-1172470.log)

## Symptoms 
I can't get by the first screen.

**Comment by kisak-valve** [comment]
Hello @GentBinaku, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #4350, but as you've noted and in your Proton log `info:  llvmpipe (LLVM 15.0.7, 256 bits):` tells us that your problem is that you do not have a usable Vulkan driver installed for your GPU. DXVK is trying to use lavapipe as a last ditch attempt to run at all.

You need to fix your NVIDIA driver install. Closing as not a Proton issue.
