### ISSUE TITLE
Coral Island

### ISSUE THREAD

**Issue by napperley** [ValveSoftware/Proton#7261]
# Compatibility Report

- **Game:** Coral Island
- **Steam AppID:** 1158160

[Proton Log](https://gist.github.com/napperley/ff35a460750c9568d25fbf988ae13e5a)

## System Information

- **GPU:** GT 730
- **Video Driver Version:** nvidia-driver-470
- **Kernel Version:** 5.4.0-166-generic
- **Proton Version:** 8.0.4

[Hardware Information](https://gist.github.com/napperley/c8fa3fdf6c64eccc25af1565afeab7ec)
[Steam Runtime Information](https://gist.github.com/napperley/33f92522352ea5c930d6e725eaeb0520)

## I confirm:

- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms

In the Steam client it shows the game as running for a few seconds before exiting, even though the game hasn't been started by Proton.

## Reproduction

1. Start the Steam client for Linux
2. Go to Library -> Home
3. Right click on Coral Island and click on the Play button

**Comment by kisak-valve** [comment]
Hello @napperley, Proton 8.0 and newer requires that the video driver provide Vulkan 1.3 and the NVIDIA 470 series video driver provides Vulkan 1.2. Additionally, using `PROTON_USE_WINED3D=1` is not considered supported.

You might get lucky using Proton 7.0 or older, but sorry, your hardware is not supportable in general going forward with Proton.

Having written that, `dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory` in the Proton log points in a very different direction and that issue is being tracked at #7209.

Closing because we're unable to support the hardware and in favor of the older issue report.
