### ISSUE TITLE
INFRA (251110) crashing with Steam but working when running proton directly

### ISSUE THREAD

**Issue by Elektordi** [ValveSoftware/Proton#728]
Hello,

I have a strange bug with INFRA (251110) which is a Source2007 based game.
Some maps crashes the game during loading (Biggest ones afaik)

But the strange thing is, if I start the game with "PROTON_DUMP_DEBUG_COMMANDS=1 %command%", then exit the game (or wait for it to crash), than I run `/tmp/proton_run`, there is no problem anymore. (But steam runtime and overlay are not loaded)
And it's definitely the same Proton version on both runs.

I already tried to disable overlay from steam, but no change.
And when game crash, there is nothing useful in console logs, last line is `Sending full update to Client Elektordi (Elektordi can't find frame from tick -1)` but also present in log in working maps.

I'll continue to investigate, but in case someone have an idea here...

**Comment by dragonfly-lover** [comment]
did you try both from bpm and from desktop window?

**Comment by kisak-valve** [comment]
Hello @Elektordi, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Elektordi** [comment]
Here is the gist: https://gist.github.com/Elektordi/0cfa84f6c654db8f3ccfc8d280bb2c39
And same crash using big picture mode.

Also tried to raise ulimit before starting steam, same problem.

**Comment by Elektordi** [comment]
I also tried to export whole env of game (except LD_LIBRARY_PATH) to the generated proton_run script, game behaves strangely (no sound, lags...) but no crash. So it has to come the fact that steam is running it...

**Comment by kisak-valve** [comment]
You may have better luck with nvidia 396.51 or newer.

**Comment by Elektordi** [comment]
Just tested with nvidia 396.44, everything is now working inside and outside Steam. Thanks for your help!

**Comment by nhkode** [comment]
On the steam deck the game crashes reliably if in the video options set "Memory Available" to Medium or High
Chapter 5

**Comment by nhkode** [comment]
On the steam deck the game hangs reliably when loading certain levels if in the video options "Memory Available" is set to Medium or High. I believe one of those is the default. When set to Low the game seems playable just fine. First map where it's reproducible I believe was the third area right after entering the elevator down the dam. It also happens when loading most of the later maps.

[infra.zip](https://github.com/ValveSoftware/Proton/files/8418597/infra.zip) contains the proton log for a run with "Memory Available" set to Medium and a run where it was set to High.

Tested on Steam Deck OS build 20220227.3, Steam Version 16487719744, Proton 7.0-1 full [System information](https://gist.github.com/nhkode/5f7be175533a452ee983f3cf2272d21e)

**Comment by kisak-valve** [comment]
Hello @nhkode, since @Elektordi has chosen to close this issue report and there's no other open compatibility report for this game, please open a new compatibility report with your findings.
