### ISSUE TITLE
Games installed to an external library will not launch

### ISSUE THREAD

**Issue by thelabcat** [ValveSoftware/Proton#7359]
Proton experimental. Old-school RuneScape, Lethal Company, and Among Us all run perfectly when installed to the default /home location. But, when I install them to an external drive, they don't launch at all. The button says they are, but then it goes back to saying "play" again.

Linux native titles launch from the external location just fine. I can move the Windows only titles back-and-forth, and they reliably only work when installed to the default location.

**Comment by kisak-valve** [comment]
Hello @thelabcat, what filesystem are you using with the secondary Steam Library folder?

**Comment by thelabcat** [comment]
NTFS.

**Comment by kisak-valve** [comment]
Using Proton with NTFS is known to be finicky, and is a long standing issue being tracked in several issue reports going back to #11. The general recommendation is to use a Linux native filesystem with Proton instead of it.

You might get lucky with the workarounds mentioned at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows.

**Comment by thelabcat** [comment]
I'll have to, because otherwise, I'm in trouble.

**Comment by thelabcat** [comment]
Okay, thanks.
