### ISSUE TITLE
A question about PROTON_REMOTE_DEBUG_CMD option

### ISSUE THREAD

**Issue by SheffeyG** [ValveSoftware/Proton#7377]
I am using PROTON_REMOTE_DEBUG_CMD launch option to make the debug work with the game in steam deck, and I want to make the debug program work after the game with a delay, so I tried `PROTON_REMOTE_DEBUG_CMD=delay.sh` and `PROTON_REMOTE_DEBUG_CMD=delay.bat`, sadly, both scripts don't work, I am confusing which one is correct? or is there another way to do it?
here is the bat and sh scripts:
```bat
@echo off
timeout /t 5 > nul
start "" "\home\deck\debug.exe"
```
```sh
sleep 5 && /home/deck/debug.exe
```

**Comment by ghost** [comment]
@SheffeyG I see a few issues at play here:

1. The BASH Shell Script (delay.sh) isn't going to execute since the Wine container (aka Windows) doesn't know how to handle it.
2. BAT files can execute, but you need to include the full quoted path to the BAT file when defining the PROTON_REMOTE_DEBUG_CMD variable. Assuming the bat file is in the same directory as the debug.exe, here is what you would use:
`PROTON_REMOTE_DEBUG_CMD="/home/deck/delay.bat"`
3. In the bat file, you are calling "start" to execute "debug.exe" from a path format that Windows doesn't understand. You need to use a valid path. In case you didn't know, Steam OS mounts / to z:\. So that should mean you would want to use "z:\home\deck\debug.exe" . Example of proper bat code:
```
@echo off
timeout /t 5 > nul
start "" "z:\home\deck\debug.exe"
```

**Comment by SheffeyG** [comment]
@AlexSmith268 Your suggestion make sense.
I test that bat script, but it doesn't  delay as I expect (maybe the `timeout` statement is wrong?)
And the debug.exe program doesn't pop up with `start "" "z:\home\deck\debug.exe"` tho the path is viable, but it works when I do `start "explorer.exe"`
Then I relized I can do this
```
@echo off
start "" "explorer.exe"
```
so I can run the executable var run the file explorer. I am still figuring a better way to do this, and thanks for your help!
