### ISSUE TITLE
A problem with Doom (1993) on proton

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#7399]
When I starting play on proton, unfortunately, I used to seen all logo like usual, and now it starts incorrectly show color bars instead. Can you fix it if I please?

![Screenshot from 2024-01-07 06-39-00](https://github.com/ValveSoftware/Proton/assets/156383913/262b9b12-363f-488d-8cc6-6f8b7347102d)

**Comment by kisak-valve** [comment]
Hello @Romactu, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1534#issuecomment-1888219530.

(To be fair, the game was borderline unsearchable on this issue tracker due to the game devs renaming it yet again.)

**Comment by ghost** [comment]
I also tried Worms W.M.D with proton (due to linux native version is unplayable) it shows me a same problem when it's trying to show me team17 logo and worms wmd logo on loading and it's been like that for over a year without troubleshooting it. Yes, even on my steam deck, and yes, I tried the game on geforce now or on windows 11 previously, it works just fine. So I need that to be fixed as well.

![Screenshot from 2024-01-11 17-19-05](https://github.com/ValveSoftware/Proton/assets/156383913/54d4a5ca-952b-420e-85d9-786aee389e0d)

**Comment by kisak-valve** [comment]
Add a note on the relevant compatibility report (#2953) with a Proton log.
