### ISSUE TITLE
Add support for GalliumNine

### ISSUE THREAD

**Issue by shanefagan** [ValveSoftware/Proton#745]
**Rationale**

GalliumNine gives good performance for the games that work and for the drivers that support it. Allowing users to leverage that power is a big win for performance. (I know not a Steam game but it gives a good indication of performance) SC2 goes from 100 FPS on my radeon RX480 to 300 fps ish with GalliumNine. 

**Implementation**

The patch is already available on [Github ](https://github.com/sarnex/wine-d3d9-patches)to add the functionality to WINE, the only problem is how it is implemented in the config really and making sure failover works correctly.

**Comment by Elkasitu** [comment]
Duplicate of #66

**Comment by nstgc** [comment]
For what its worth: https://www.phoronix.com/scan.php?page=news_item&px=Wine-D3D9-Gallium-Nine-Opposed

Also, remember as you read that, that ValvE has hired someone (or someoneS) to work on Mesa.

Also: https://github.com/disks86/VK9

I'm very much of the opinion that its better to do it right the first time. VK9 will be a thing. This isn't like "native or nothing" where we can say "a wrapper is good enough" because native may never happen. VK9 will happen.

**Comment by shanefagan** [comment]
Yeah fair enough, if VK9 is how they sort it then cool, actually for SC2 it would probably be better than GalliumNine anyway, just I was favouring something that could have been an answer right now over something that would be an answer in a year.
