### ISSUE TITLE
Update binutils to 2.42 in Proton 9.0 SDK

### ISSUE THREAD

**Issue by guihkx** [ValveSoftware/Proton#7518]
*(This is not a bug, it's a request, and it's unrelated to Steam or a game in particular)*

Long story short: I'm making my own, personal build of Proton, but with the main difference that I'm trying to include DXVK 1.10.x, because my GPU doesn't support Vulkan 1.3.

However, the binutils version [included](https://github.com/ValveSoftware/Proton/blob/1ef9a3674bae0e50ece8b8d074fc76ae94dacb82/docker/Makefile#L12) in the Proton SDK/SteamRT image fails to link one of the DXVK dlls to [due this bug](https://sourceware.org/bugzilla/show_bug.cgi?id=30079), which has been fixed in 2.41.

I also know that I don't have to build my own version of Proton; I can simply replace some DirectX dlls that Proton ships and I'm good to go. But that's not fun, is it? :)

I'm not even sure if what I'm attempting to do will work in the end, but at the moment I'm stuck at building DXVK 1.10.x, and I can't find a way around it unless I build my own Proton SDK, which I want to avoid having to do...

Anyway, given that Proton 9.0 is a major release, I figured this could be a good time to update binutils.

If this is not possible, feel free to close this one.

Thanks!

**Comment by roadapathy** [comment]
Hey friend! What GPU do you have that isn't compatible with Vulkan 1.3? Very old GPUs are supported like the AMD RX 400 series, for example.

I'm compiling Proton too but Proton 9 failed near to the end of the building process. I don't want to bother the Proton team here until I exhausted every possible solution. Proton 8 builds just fine on Xubuntu 23.10.

My experience with DXVK on my AMD RX 6700 TX has been bad. If I install it at all, if it's on my system anywhere, games slow down and become less stable. So I never have it on the system but maybe it's needed for older GPUs like you said?

Since I have an AMD GPU, I compiled the latest Kernel. With Valve's Proton, the Linux Kernel, and some other graphic libraries, I compile those with -march=native which I can add to the Makefile/Makefile.in. So if anybody questions you "Hey, why are you doing that? Why not just use the ...." then I say just ignore them. You're rocking it!

**Comment by guihkx** [comment]
Hey @roadapathy,

>What GPU do you have that isn't compatible with Vulkan 1.3? Very old GPUs are supported

I have a GTX 660, so it's "extra" very old... :)

>My experience with DXVK on my AMD RX 6700 TX has been bad. If I install it at all, if it's on my system anywhere, games slow down and become less stable

That honestly sounds unusual, otherwise I think we'd have other people reporting that too?

>So I never have it on the system but maybe it's needed for older GPUs like you said?

Well, at least on my machine, I have terrible performance in DX9-DX11 games *without* DXVK (i.e. aka with WineD3D, aka the OpenGL implementation). So, for me, DXVK is a must have.

>So if anybody questions you "Hey, why are you doing that? Why not just use the ...." then I say just ignore them. You're rocking it!

Exactly, thanks! I'm glad someone else also gets it. :D

**Comment by roadapathy** [comment]
Ahhh. That's an old Nvidia GPU. I think you'd be better off using the proprietary drivers that Nvidia recommends. It claims you need 470.239.06

I don't know how you install your GPU drivers but I usually drop down to recover mode on boot, mount the drives (usually just update Grub option from the boot menu), then drop down to the shell/CLI, find the /Downloads directory, and install the Nvidia driver. 

Maybe this will help?

My GPU is the AMD RX 6700 TX so the driver is a module within the Kernel. So if I compile the Kernel, and modify the Makefile to include -march=native, then the GPU driver is build optimized for my CPU. It's really nice. These are things the Windows people could never do so I think it's cool.

**Comment by guihkx** [comment]
>I think you'd be better off using the proprietary drivers that Nvidia recommends. It claims you need 470.239.06

Yep, I already am. But that version doesn't support Vulkan 1.3, only 1.2. That's why I must use DXVK 1.10.x...

**Comment by guihkx** [comment]
Done in https://github.com/ValveSoftware/Proton/commit/9b10a7670a15c6e9f56de6f03cff13c0420dff59.
