### ISSUE TITLE
Proton 9 Beta Steam Deck compatibility issues (black screen with audio)

### ISSUE THREAD

**Issue by MrWalshy** [ValveSoftware/Proton#7527]
Issue:

Some games are launching with a black screen and audio when using Proton 9 Beta 1, issue does not exist when using Proton 8.0-5.

Attempted:
- Launching via desktop and game mode. Desktop gives four quadrants, the bottom left and top right showing the desktop. The top left and bottom right are black. Game audio still plays, controls responding. Game mode is a full black screen.
- Disabling and enabling frame limiters.
- Disabling and enabling V-Sync.
- Disabling and enabling locked GPU clock.
- Switching game config between Windowed, Windowed Borderless, and Fullscreen.

Steam Deck:
- LCD Model
- SteamOS 3.6 (Main)

Games affected:
- Cyberpunk 2077 (launcher displays fine, black screens on clicking Play button)
- The Witcher 3 (both DX11 and 12 versions, launcher works fine as with CP)
- Dying Light 2
- Assassin's Creed Origins

Games booting fine:
- Dying Light 1
- Fallout 4
- Brawlhalla
- Skyrim SE
- Valheim (interestingly, the first few DX launches were black screen with audio. Then tried Vulkan, which worked fine. Retrying the DX version after this then worked fine.)
- Medieval Dynasty (DX12)

Log file for Cyberpunk, [steam-1091500.log](https://github.com/ValveSoftware/Proton/files/14408276/steam-1091500.log), let me know if any others are wanted.

**Comment by kisak-valve** [comment]
Hello @MrWalshy, these games should be evaluated for regressions in the upcoming Proton release separately. Please add notes to each game's compatibility report with a Proton log for that game and details of what you've found. (#4450 #607 #5542 and #1757)

If left open, then this issue report will quickly become a catch all for all unrelated feedback on Proton 9.0.

**Comment by kisak-valve** [comment]
Skimming over the log that was shared, it might be interesting to test Cyberpunk 2077 with the game's launch options set to `WINEDLLOVERRIDES="amd_ags_x64=n" %command%` and see if that does anything for you.

**Comment by alasky17** [comment]
@MrWalshy I looked into CP2077 and could only reproduce the black screen on SteamOS Main, not SteamOS stable. It would be great if you could confirm if they are all SteamOS Main specific.  I'm hoping that this is all one bug after all.  🤞

**Comment by MrWalshy** [comment]
@alasky17 Can confirm that I had only checked these games with Steam OS 3.6 (Main) at the time of writing the post.

Just reverted to the stable branch 3.5. That does fix the issue and Proton 9 then works with CP2077, DL2, TW3, and AC Origins :)

@kisak-valve Thank you, the property unfortunately does not help with it on 3.6

**Comment by alasky17** [comment]
@MrWalshy Thank you for confirming that! Turns out, this is a known regression with SteamOS main that is already being worked on.  There is a reason it is not called stable :D  Leaving as closed since this is already understood and being fixed.  It would be great if you could update any individual issues as well (I only saw the CP2077 one) so we don't accidentally forget and investigate a second time.

**Comment by MrWalshy** [comment]
@alasky17 I hadn't thought about it being related to the OS given Proton 8 was working fine 🤦 Thank you! I'll update the Cyberpunk issue comment now.

I'm just wondering, should I make comments on the other games as well but also include that it's a known issue or will it be fine to leave them?

**Comment by alasky17** [comment]
@MrWalshy If you haven't left comments yet, then no I don't think that is necessary since it did end up being one meta-issue (as far as I can tell, since they were all fixed by the SteamOS downgrade). 

FWIW, apparently it is some problem between newer dxvk/vkd3d-proton and newer radv.  So when I looked into CP2077 it did appear to be a vkd3d-proton regression that was only happening on SteamOS main for some reason.  Definitely not obvious that the bug was in SteamOS main itself.  

Also - thank you for clearly noting that you were using SteamOS main - that saved a ton of headache as that became my first suspect after I couldn't repro :D

**Comment by w1lddog2** [comment]
Thank god i read this. I was going nuts looking for a solution.
Many games using proton 8-xxx, proton 9 hotfix and experimental had the same issue black screen with sound, the game was not crashing just no image.
I was using Main too. I switched to stable and they work once again.

**Comment by Kokodayo-CN** [comment]
Hi there
It seems Muse Dash also has the same issue when launched using Porton Experimental, Porton 9 Beta AND Porton 8.0-5 (even the game is tested under 8.0-5), with no video output but only audio output, and can only show the mouse with fps stuck at 24/26, and the game simply refuses to launch when using lower version of Porton
