### ISSUE TITLE
All Proton games fail to launch from library, but seem to work fine when launched outside Steam

### ISSUE THREAD

**Issue by AkiraMorilas** [ValveSoftware/Proton#7541]
#### Your system information

* Steam client version (build number or date): 
Steam Client Build Date:  Sat, Jan 13 1:52 AM UTC -08:00
Steam Web Build Date:  Fri, Jan 12 6:02 PM UTC -08:00
* Distribution (e.g. Ubuntu): openSUSE Tumbleweed
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:  
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14465631/steam-logs.tar.gz)
* GPU: AMD Radeon RX 6600

#### Please describe your issue in as much detail as possible:
When pressing the PLAY button in the library view, the button shows CANCEL for a time(depends on game), then shows STOP for approximately 1,5 seconds, before reverting to PLAY again. No error is displayed at any point.
However, I tried to launch some games outside of the Steam client and they work fine outside of not having any save data(Holocure and Micro Mages shown in attached screenshots).
![Screenshot_20240301_214744](https://github.com/ValveSoftware/steam-for-linux/assets/134231050/790845e3-b359-4a02-89c6-b2afdbfc6d27)
![Screenshot_20240301_213023](https://github.com/ValveSoftware/steam-for-linux/assets/134231050/305a447c-c82b-4ed7-9cab-b3a3312f54ac)

However, games that are wine-wrapped out of the box(like Earth 2150) don't launch outside of Steam either.

I tried EVERY version of the Proton Runtime with at least Holocure, and several versions with other games.

#### Steps for reproducing this issue:

1.  Press PLAY button
2.  Game does not play

**Comment by VortexAcherontic** [comment]
Looking at your logs it looks like your Proton installs are outside your home directory but on an external drive `/run/media/...` if I am not mistaken here?

- What file system does your external drive have? If it is NTFS (eg windows default file system) it often causes trouble
- independent of the file system of the external device does it help if you transfer proton to your home directory and then run the games?

**Comment by AkiraMorilas** [comment]
It's internal(I just mounted it there because I misunderstood some things moving to openSUSE after years of Debian/Mint/other Debian-based distros), but yes it's NTFS, carried on from a dualboot setup years ago. I'll try moving some games and proton to home directory tomorrow, I'll need to make some room first.

**Comment by ecen** [comment]
I am having a similar issue to this on KDE Neon. Noticed it about 5 days ago. No games can be launched in Steam via proton. (Have not attempted to launch outside of Steam). All the games I have tested (Baldur's Gate 3 and Deep Rock Galactic to give two examples), previously worked perfectly.

**Current symptoms**:
- No games can be launched via proton.
- Games not launched via proton works fine.
- In Proton 8.0-5 and later, the game is shut down immediately, generating no logs with the `PROTON_LOG=1 %command%`  launch option.
- In proton7.0-6 and earlier, steam shows a blue "STOP" button and generates logs for a bit, but no game window ever openes.
   - [steam-1086940-6.3-8.log](https://github.com/ValveSoftware/Proton/files/14517125/steam-1086940-6.3-8.log)
   - [steam-1086940-7.0-6.log](https://github.com/ValveSoftware/Proton/files/14517126/steam-1086940-7.0-6.log)


**Attempted fixes, in order**:
1. System update. Got upgraded from Plasma 5 to 6, which uses Wayland by default. Previously I was using X. Issue persists.
2. Reinstall Steam. Steam client from .deb package has scaling issues under Wayland. Issue persists.
3. Did a clean re-install of KDE Neon.
4. Attempted install steam from steam_latest.deb. This required me to first manually install `zenity` via apt-get, since it was missing but required. Steam client has scaling issues. Issue persists.
5. Uninstalled Steam and reinstalled from snap. Steam client does not have scaling issues, but game launching issue persists.
6. Moved Deep Rock Galactic from separate drive to system drive where Steam is installed. Issue persists.


**System**
OS: KDE neon 6.0
GPU: AMD Radeon RX 7800 XT
Kernel: 6.5.0-21-generic (64-bit)
Storage: Steam Installed on the system ext4 drive. Games library on separate ext4 drive mounted under `/media/battleship` with the following fstab options `defaults,noatime,discard 0 1`

**Comment by 1player** [comment]
FWIW, I'm having the same issue with Deep Rock Galactic, but other games seems to work fine.

**Comment by 1player** [comment]
I forced Deep Rock Galactic to Proton 8 and now it starts. Do you have by any chance the Proton 9 beta installed? That might be the cause.

**Comment by jomarocas** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/7541#issuecomment-1982128478

any update for this? i have the same issue, i remove kde i use gnome with x11 and none games run, i try to make something different with remove ntfs-3g.

**Comment by AkiraMorilas** [comment]
Sorry it took so long, a few things happened and got in the way.
I can now confirm that after moving to a non-Windows drive the games just work.  I guess I can close now.
