### ISSUE TITLE
Organization: Move whitelist request and game-specific issues to separate repos

### ISSUE THREAD

**Issue by akien-mga** [ValveSoftware/Proton#76]
First of all congrats for a great release and for the work you've done here, it's an incredible milestone for Linux gaming.

I see that after 12 hours the issue repo is already filling up pretty fast, which is great, but being familiar with managing open source projects, I wonder if that's the best workflow for the development of Proton on one hand, and for improving SteamPlay compatibility on the other hand.

I would suggest to create new repositories/issue trackers for:
- Whitelist requests; all issues should have the same form, following a configured `ISSUE_TEMPLATE.md`, which would make it clear what game was tested (including its Steam ID for disambiguation), on what platform, etc.
- Game-specific bug reports; same thing, there should be a specific issue template for those.

This tracker (`ValveSoftware/Proton`) would be for actual software issues in Proton, buildsystem stuff, enhancement and feature requests, etc. It should be kept primarily for Proton developers and contributors.

WDYT?

**Comment by vanyasem** [comment]
In the meantime there's a thread on Steam:
https://steamcommunity.com/app/221410/discussions/0/1734336452575505938/

And also a Google Sheets document: https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/htmlview?sle=true#gid=0

**Comment by kisak-valve** [comment]
Hello @akien-mga, since I'm labeling the issues during initial review, there's not much of an issue with mixing these issue reports.

Some convenience links:

[Whitelist requests only](https://github.com/ValveSoftware/Proton/issues?q=is%3Aopen+is%3Aissue+label%3A%22Whitelist+Request%22)

[Games needing workarounds](https://github.com/ValveSoftware/Proton/issues?q=is%3Aopen+is%3Aissue+label%3A%22Game+compatibility+-+Unofficial%22)

[Whitelist requests and unofficially supported games excluded](https://github.com/ValveSoftware/Proton/issues?page=1&q=is%3Aopen+is%3Aissue+-label%3A%22Game+compatibility+-+Unofficial%22+-label%3A%22Whitelist+Request%22&utf8=%E2%9C%93)

**Comment by mirh** [comment]
Mhh, I dunno.. It starts to become confusing when geniuses start to mass report everything and the kitchen sink. 
Already half of the first page is wishlists - let alone half of the reminder being bugs in unofficial games.
