### ISSUE TITLE
DXVK Games Crash

### ISSUE THREAD

**Issue by dbob16** [ValveSoftware/Proton#7730]
# Compatibility Report
Games using DXVK

## System Information
- GPU: AMD Radeon 7800 XT
- Video driver version: Mesa 1:24.0.6-2
- Kernel version: 6.8.9-arch1-2
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/dbob16/aeffe2f164696ca6665898055a12354b
- Proton version: All Versions

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Log file

Log file from Fallout 4 crash to desktop attached below:

[steam-377160.log](https://github.com/ValveSoftware/Proton/files/15302339/steam-377160.log)

## Symptoms

Any game using DXVK constantly crashes to desktop. It is sudden and usually happens on loading screens in Fallout 4, and randomly on other games. For instance, Riders Republic does this so often that it's unplayable.

If I isolate it using the PROTON_USE_WINED3D11=1 argument, which reverts it to DX2OpenGL, it works albeit laggy. At least it doesn't crash like that.

## Reproduction

Playing any game new enough to play using DXVK.

**Comment by ghost** [comment]
Can confirm that on my PC, after of one of updates in video stack (as I suppose is a culprit to the issue), everything started to perform poor and always crushing (Overwatch 2, Dead by Daylight, Apex Legends are affected by that) and thus, using anything else than DXVK fixed my issue, also, why I do think this issue happened in video stack is because all people which had AMD+AMD GPU PCs, have similar issues with other games as well, so either AMD video stack is buggy or Proton/DXVK related issue, I am in favor of both failing in some parts and together - they may create some type of error which causes crashes

**Comment by GsK380** [comment]
Can confirm that on my PC, after of one of updates in video stack (as I suppose is a culprit to the issue), everything started to perform poor and always crushing (Overwatch 2, Dead by Daylight, Apex Legends are affected by that) and thus, using anything else than DXVK fixed my issue, also, why I do think this issue happened in video stack is because all people which had AMD+AMD GPU PCs, have similar issues with other games as well, so either AMD video stack is buggy or Proton/DXVK related issue, I am in favor of both failing in some parts and together - they may create some type of error which causes crashes

**Comment by kisak-valve** [comment]
Hello @dbob16, this is a kernel regression which was tracked and fixed at https://gitlab.freedesktop.org/drm/amd/-/issues/3343. You can reboot into an older kernel (6.6.30 does not count as older) until the commit that fixed the issue is more commonly available.

**Comment by dbob16** [comment]
Updated to kernel 6.9.1. Still crashing.

**Comment by kisak-valve** [comment]
Please share an updated Proton log.

**Comment by dbob16** [comment]
It's definitely changed though. It crashes less often, but now after it has crashed, the game won't open until I've rebooted my computer. So it may take me a bit to grab a log that's not hundreds of MB.

**Comment by dbob16** [comment]
[steam-377160.log](https://github.com/ValveSoftware/Proton/files/15367365/steam-377160.log)

When it tries to launch after a crash.

**Comment by dbob16** [comment]
[steam-377160.log](https://github.com/ValveSoftware/Proton/files/15367396/steam-377160.log)

Got it to crash pretty quickly that time.

**Comment by kisak-valve** [comment]
Thanks, from your log:
```
[Gamescope WSI] getWindowRect: xcb_get_geometry failed for window 0x160002d.
X connection to :2 broken (explicit kill or server shutdown).
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":2"
X connection to :2 broken (explicit kill or server shutdown).
X connection to :2 broken (explicit kill or server shutdown).
      after 470610 requests (470609 known processed) with 1 events remaining.
X connection to :2 broken (explicit kill or server shutdown).
```
These look like the lines to focus on. I read it as gamescope WSI and/or X is getting kicked out from underneath of Proton, and the game is having a bad time as a result. This hints that there's a video driver or maybe gamescope issue and you should follow up in that direction.

I would test how the game behaves with `ENABLE_GAMESCOPE_WSI=0 %command%` in its launch options to try turn off the gamescope WSI layer.

---
Your header only log in https://github.com/ValveSoftware/Proton/issues/7730#issuecomment-2119067836 hints that something went wrong before the game itself had a chance to run. If you completely close Steam, then run `steam-runtime` from a terminal, are there any hints in the terminal spew when you tell Steam to start the game in the quick fail scenario?
