### ISSUE TITLE
Rivals of Aether II (2217000)

### ISSUE THREAD

**Issue by pixelprogrammer** [ValveSoftware/Proton#8200]
# Compatibility Report
- Name of the game with compatibility issues: Rivals of Aether 2
- Steam AppID of the game: 2217000

## System Information
- Distro: Fedora Linux 40 (Workstation Edition)
- Kernel: 6.11.3-200.fc40.x86_64
- RAM: 16 GB
- GPU Driver: 4.6 Mesa 24.1.7
- GPU: Intel Mesa Intel Arc A750 (DG2)
- CPU: Intel Core i7-10700F @ 2.90GHz
- Link to full system information report as [Gist](https://gist.github.com/pixelprogrammer/93da8bf6377d730f23fbaba7f7558b2a):
- Proton version: Experimental

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

## Proton Log file
[steam-2217000.log](https://github.com/user-attachments/files/17544921/steam-2217000.log)

## Symptoms
- Game opens with white screen with text that says "Fatal Error"

## Reproduction
- Set compatibility mode to Experimental
- Open Game
- Should see crash window

## References
- https://github.com/ValveSoftware/Proton/issues/8164#issuecomment-2439901808
- https://www.protondb.com/app/2217000 (filter by Intel GPU)

**Comment by pixelprogrammer** [comment]
So I got this to work with Proton version 7.0-6 but version 9 would give the fatal crash error.

**Comment by exalented** [comment]
> So I got this to work with Proton version 7.0-6 but version 9 would give the fatal crash error.

Regression in 8.0-5 and onward using the i915 driver. Same Arc card.

**Comment by liftboost** [comment]
Native Wii U GameCube adapter support does not work. Seems to be implemented over some user-mode usb interface. Heard someone said they got it to work on a distro with an older kernel but they didnt go into detail how. Not remapping through an input API, native usb

**Comment by exalented** [comment]
> Native Wii U GameCube adapter support does not work [in proton 7]..

We used to need this until SDL 2.0.12: https://github.com/ToadKing/wii-u-gc-adapter
This is in the AUR.
```
$ wii-u-gc-adapter
Detaching kernel driver
adapter 0x5cfa5be870f0 connected
connecting on port 0
$ #run the game and it should work now
```

**Comment by liftboost** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8200#issuecomment-2489770470

This is not native and remapping to virtual controllers will not have the same level of accuracy or special features (button prompts, default mappings, possible stick calibration) as the game's direct usb implementation. The game implements gamecube adapter support over libusb (or whatever the windows equivalent of usb userland driver is) like dolphin does.

**Comment by alasky17** [comment]
@pixelprogrammer @exalented The Intel GPU crash should be fixed in proton-experimental.  Please let me know if this is not fixed -- I also have a favor to ask while you are retesting.  Could you see if the video that plays before the main menu if you don't hit/click anything (it is a skippable video after the developer logos) is playing properly for you on the Intel GPUs?  In my testing, it was missing a lot of frames and not playing smoothly at all and I am curious if this is the case for all Intel GPUs or only my very low powered and ancient iGPU.  In my case, WINE_USE_OLD_MEDIA_SOURCE=1 %command% made the video play smoothly.

**Comment by pixelprogrammer** [comment]
Just tested it. Game was running similar to the version of proton that was working and the video at the start was not skipping frames for me.

**Comment by exalented** [comment]
Yup works really good. No issues with video playback either using the i915 driver.
**To fix gamecube controller mappings**:
- clone this project which fixes your Z button (grab) and makes the correct mappings: https://github.com/joseph-cheng/wii-u-gc-adapter
- cd wii-u-gc-adapter
- make
- ./wii-u-gc-adapter

**Comment by pixelprogrammer** [comment]
Is it safe to say this issue can be closed now?

**Comment by alasky17** [comment]
@pixelprogrammer @exalented I just realized I gave y'all the wrong launch option to test :( It should be WINE_OLD_MEDIA_SOURCE=1 %command% without USE. If you have a few minutes to make sure that one also doesn't cause any video playback changes with that video, that would be amazing :) 

@pixelprogrammer WRT closing the issue - since there is only one issue per game on this tracker, it is not necessary to close as other folks might use this issue in the future for other bugs they see (like the Native Wii U GameCube adapter support discussion above).  Since you are the original reporter and this thread is still mainly about your originally reported issue, you can close if you'd like and leave it to someone else to open a new issue for the game.

**Comment by pixelprogrammer** [comment]
> @pixelprogrammer @exalented I just realized I gave y'all the wrong launch option to test :( It should be WINE_OLD_MEDIA_SOURCE=1 %command% without USE. If you have a few minutes to make sure that one also doesn't cause any video playback changes with that video, that would be amazing :)
> 
> @pixelprogrammer WRT closing the issue - since there is only one issue per game on this tracker, it is not necessary to close as other folks might use this issue in the future for other bugs they see (like the Native Wii U GameCube adapter support discussion above). Since you are the original reporter and this thread is still mainly about your originally reported issue, you can close if you'd like and leave it to someone else to open a new issue for the game.

Ok, I will do one more test with that command first just to see if I get the stuttering issues, if not I will close this one out.

**Comment by Kartoffelsaft** [comment]
Creating / Joining lobbies in this game is almost completely broken for me. Creating waits for a bit then just says "Unknown Error", and joining will put you in a lobby that says it has -1/0 players. Oddly enough a friend using a steam deck doesn't have this issue and matchmaking is flawless for me.

I switched to 7.0-6 and it fixed the issue but restarting the game unfixed it, so that was likely a fluke. Seems to me like it will just randomly work once occasionally.

Related: https://steamcommunity.com/app/2217000/discussions/0/4703539342753250627/

Curious if anyone else is experiencing this issue?

**Comment by pixelprogrammer** [comment]
> Replying to https://github.com/ValveSoftware/Proton/issues/8200#issuecomment-2542596571

You should create a separate issue for this game. This issue is related specifically to the crashing on start with Intel Arc GPUs.

**Comment by pixelprogrammer** [comment]
> WINE_OLD_MEDIA_SOURCE=1 %command%

Just tested this command and didn't notice any stuttering in the opening video. Also tested it without any command, and it was still fine for me.

Closing this issue since the latest updates resolved my issue and the game is playable now.

**Comment by Kartoffelsaft** [comment]
> > Replying to [#8200 (comment)](https://github.com/ValveSoftware/Proton/issues/8200#issuecomment-2542596571)
> 
> You should create a separate issue for this game. This issue is related specifically to the crashing on start with Intel Arc GPUs.

Hmm, it was my understanding that the proton github issue tracker is per-game, not per-bug (if you search `is:issue is:closed` there's plenty of issues closed to enforce this). So I posted it here.

Either way, I'm quite confident now that the bug is unrelated to proton, and just a bug with the game, as most others with the issue are on windows.

**Comment by pixelprogrammer** [comment]
> > > Replying to [#8200 (comment)](https://github.com/ValveSoftware/Proton/issues/8200#issuecomment-2542596571)
> > 
> > 
> > You should create a separate issue for this game. This issue is related specifically to the crashing on start with Intel Arc GPUs.
> 
> Hmm, it was my understanding that the proton github issue tracker is per-game, not per-bug (if you search `is:issue is:closed` there's plenty of issues closed to enforce this). So I posted it here.
> 
> Either way, I'm quite confident now that the bug is unrelated to proton, and just a bug with the game, as most others with the issue are on windows.

I think you're right. My bad. This is how it normally works but I just reread a previous comment and learned its not how its used here.
