### ISSUE TITLE
[Feature Request] passing kernel-based anti-cheat

### ISSUE THREAD

**Issue by LFRon** [ValveSoftware/Proton#8320]
# Feature Request

## I confirm:
- [√ ] that I haven't found another request for this feature.
- [ √] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Nowadays many games include kernel-based anti-cheat like EA Sports ERC and Naraka: Bladepoint (永劫无间) new test server.However,wine and proton seems does not support it,which causes games like EA Sports WRC and so on couldn't run the games.Could Valve developers make proton and wine compatible with these kernel-based anti-cheat?Thanks!😍

**Comment by SecularSteve** [comment]
Don't be an idiot making impulsive posts there kid.

It's already been a topic for years, and only as close as the developers allow it.
Valve has been co-operating with BattlEye since the very beginning, and all it takes is one click from the developer's end.

Games like Apex Legends, PUBG, Fortnite and GTA V are only one click away from allowing players back in, but they deliberately keep them out due to (in my opinion) mostly prejudice against Linux users.

That's a whole other can of worms where Linux users are alleged to have the highest proportional percentage of cheaters, but it's more of a case of deliberate profiling so they can have a scapegoat to keep their markets under control.

But that's simply my opinion. The point is, this post is pointless because it's already been worked on for so long, and outright illegal to bypass them by any means that aren't official.

Take my advice, and think before you post next time. The internet's a wild place, and not many will go as easy on you probably.

---

別像個白癡一樣在那裡衝動地發帖子，孩子。

這已經是多年前的話題了，只有在開發人員允許的情況下才會接近。
Valve 從一開始就與 BattlEye 合作，只需要從開發者端點一下就可以了。

像《Apex Legends》、《PUBG》、《Fortnite》和《GTA V》這些遊戲只需要按一下就能讓玩家回到遊戲中，但他們刻意將玩家拒諸門外，原因是（在我看來）大多數是對 Linux 使用者的偏見。

這是另一個完全不同的問題，Linux 使用者被指稱是作弊者比例最高的使用者，但這更像是刻意以貌取人，好讓他們有替罪羊來控制市場。

但這只是我的看法。重點是，這篇文章是沒有意義的，因為它已經被研究了這麼久，而且以任何非官方的方式繞過他們是完全非法的。

聽我的建議，下次發帖前先想清楚。網際網路是個狂野的地方，可能沒有多少人會對你這麼容易。

**Comment by kisak-valve** [comment]
Hello @LFRon, as inconvenient as it might be for some, anything that requires privilege escalation including injecting kernel modules is summarily out of scope for the Proton project and your request could also be interpreted as a request to do harm to the entire Linux ecosystem.

This request as presented is a non-starter.

As a side note, by their nature, the implementation details of any anti-cheat mechanism can't really be discussed publicly without compromising that approach to solving the problem in some way. Attempting to rephrase this request simply to force it to be an open topic will be met with the same out-of-scope response because any public issue tracker isn't a suitable place to help improve this particular topic.
