### ISSUE TITLE
Dark and Darker (2016590)

### ISSUE THREAD

**Issue by nmlynch94** [ValveSoftware/Proton#8331]
# Compatibility Report  
- Name of the game with compatibility issues: Dark and Darker
- Steam AppID of the game: 2016590

## System Information  
- GPU: NVIDIA GeForce RTX 3070
- Video driver version: nvidia-565-77
- Kernel version: 6.11.11-300.fc41.x86_64
- Link to full system information report as [Gist](https://gist.github.com/nmlynch94/cde8dda8978b79d336c13ea94fd5b103)
- Proton version: Experimental

## I confirm:  
- [x] that I haven't found an existing compatibility report for this game. A previous report exists here https://github.com/ValveSoftware/Proton/issues/8208 but appears unrelated to this crash.
- [x] that I have checked whether there are updates for my system available.

[steam-2016590.log](https://github.com/user-attachments/files/18208050/steam-2016590.log)

## Symptoms  
When launching DaD, you arrive on the title screen. When the game tries to connect to the servers, it then crashes.

## Reproduction  
1. Open Dark and Darker
2. Wait for "Connecting" screen to show
3. Crash

**Comment by meppega** [comment]
It was the game's fault, it's working for me since "Early Access Hotfix 74", the issue was indeed related to audio and caused crashes/issues even on my Windows machine.

Pretty sure it's irrelevant now, but I am also using
OS: Nobara Linux 40 (KDE Plasma)
KERNEL: 6.11.9-200.fsync.fc40.x86_64
CPU: AMD Ryzen 5 1600 Six-Core
GPU: NVIDIA GeForce GTX 1660 Ti
GPU DRIVER: NVIDIA 565.77
RAM: 16 GB

Custom Proton: GE-Proton9-21
Steam launch settings: LD_PRELOAD="" STEAMDECK=1 %command%

Just checked, the game also works on stable Proton 9.0-4

**Comment by nmlynch94** [comment]
I am seeing the same as the person above. Will close since it's been addressed with today's patch.
