### ISSUE TITLE
Thumper (356400)

### ISSUE THREAD

**Issue by toby3d** [ValveSoftware/Proton#850]
Steam: https://store.steampowered.com/app/356400/

Graphics work fine, better than Wine. But:
- In the control settings menu, when you switch to the gamepad, the control is completely lost after a couple of seconds.
- Since the launch, the sound cracks and stutters, the restart of the pulseaudio does not help.

**Comment by toby3d** [comment]
Also, vibration in this game doesn't work for my Steam Controller.

**Comment by mimattr** [comment]
# Compatibility Report
- Name of the game with compatibility issues: **Thumper**
- Steam AppID of the game: **356400**

## System Information
- GPU: **GTX 970**
- Driver/LLVM version: **NVIDIA 415.25**
- Kernel version: **4.4.0-141-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **3.16-6 Beta**

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-356400.log](https://gist.github.com/mimattr/324c69c8ff4b478263794bc0091889d6#file-steam-356400-log-L3169)

## Symptoms
Consistent application freezes during launch process due to failed shader compilation (`DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque`)

## Reproduction
1. Select the title within your `Library` using the Steam client and press the `Play` button

**Comment by mimattr** [comment]
@toby3d Do you still have issues with the latest **Proton 5.13-2** and **SteamVR 1.15.10** release?

**Comment by toby3d** [comment]
@mimattr I apologize for the long response. I checked the game and the controller vibration - everything works flawlessly.

**Comment by baracoder** [comment]
I had to add `-force_win8` as lunch flag like mentioned [here](https://steamcommunity.com/app/356400/discussions/1/1864993478908345453/) to get any of my gamepads (Xbox model 1708, Sony PS5 model CFI-ZCT1W) recognized, steam input has to be enabled, rumble does not work

**Comment by radgeRayden** [comment]
This shouldn't be closed.
Experiencing audio cracking.
