### ISSUE TITLE
[whitelist] Mysterium (556180)

### ISSUE THREAD

**Issue by jvalrog** [ValveSoftware/Proton#902]
[My specs](https://gist.github.com/jvalrog/93c304fabb18142bbec0c6e839db06f9)

### What works:

* Sound/Music settings
* Fullscreen/Windowed
* Different resolutions
* Language selection
* In-game menus
* In-game store menu
* Alt-tabbing
* Quitting
* Steam overlay
* History mode
* ~~Multiplayer mode with Asmodee login~~ <- half true

### What doesn't work:

* There is no mouse pointer in the Steam overlay at first but alt-tabbing fixes the issue.

**Comment by jvalrog** [comment]
I'm adding that I'm getting an error when trying multiplayer. While you can log in your Asmodee account and chat with people, the game tries to update something related to the AI and it doesn't work.

I'm attaching the steam log.

[steam-556180.log](https://github.com/ValveSoftware/Proton/files/2345339/steam-556180.log)

**Comment by jvalrog** [comment]
Ok, multiplayer now works now with Proton 3.7-6.

**Comment by aw-was-here** [comment]
This only worked for me after setting PROTON_USE_WINED3D11.  Otherwise, I would get a crash.

**Comment by kisak-valve** [comment]
Found in the 2018-11-13 white list update.

**Comment by BenWiederhake** [comment]
The thing about `PROTON_USE_WINED3D11` should be much more prominent. I didn't know about it, only got crashes of various kinds. Steam Support sent me here, they couldn't do anything. I was about to create a new bug report because it didn't work, and stumbled across this.

With `PROTON_USE_WINED3D11=1 %COMMAND%` it seems to work. Maybe set a flag to do that automatically for this game, or tell Steam Support to recommend trying setting `PROTON_USE_WINED3D11`?

**Comment by kisak-valve** [comment]
Hello @BenWiederhake, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by BenWiederhake** [comment]
Sure, if it helps others, here you go [EDIT: Link removed for privacy] .

Again, `PROTON_USE_WINED3D11=1 %COMMAND%` seems to work fine for me.

**Comment by kisak-valve** [comment]
Looks like your A8-5600K has is a Terascale 3 generation integrated video chipset. All Terascale cards do not support Vulkan, which is used by DXVK to render DirectX 9, 10, and 11 (and vkd3d for DirectX 12) in Proton. Because your system does not support Vulkan, it's effectively unsupported by Proton. This isn't game-specific.

`PROTON_USE_WINED3D` (and the older `PROTON_USE_WINED3D11`) tells Proton to use wine's DirectX to OpenGL render path, but it comes with a significant performance penalty and is also not considered supported.

**Comment by BenWiederhake** [comment]
Thanks! I don't like the result, but at least now I know what's going on.
